=== Marx viết sách thay đổi thế giới

Động lực chính của Marx cố gắng làm cho phong trào quốc tế thứ nhất vĩ đại trên
toàn thế giới đó là sự khao khát viết lại những lý thuyết đã được áp dụng vào thực
tế xuyên suốt quá trình đấu tranh của mình.
Trong nhiều năm, Marx đã ấp ủ hai dự án con cưng: phong trào quốc tế và những
"quyển sách". Cả hai dự án này đã làm Marx suy kiệt, hao mòn sức khoẻ. Bệnh gan
cũ tái phát trong thời gian dài khiến phát ban nổi nhọt, nguy cơ lan khắp cơ thể.
Bệnh tật quấy rầy, gây khổ sở phiền muộn cho những ngày còn lại cuộc đời Marx.
Những phàn nàn về đau đớn, thất vọng chịu đựng bệnh tật được trút vào bức thư
gửi cho Engels:
"Thật là tột cùng của kinh tởm, sau cả đêm không ngủ được, tôi phát hiện thêm
hai cái nhọt sang trọng trên ngực". Marx viết tiếp: "Bây giờ tôi phải tận dụng
triệt để thời gian để làm việc như những con ngựa kéo. Những chiếc nhọt sưng
tấy kia vẫn nằm đó nhưng chỉ là vấn đề nhỏ, không làm ảnh hưởng đến trí não tôi
được". Sau vài lần bị lên cơn mạnh, Marx viết: "Lần này thực sự nghiêm trọng rồi,
gia đình không biết nó nghiêm trọng thế nào. Nếu nó tiếp tục 3 hay 4 lần nữa thì
chắc là tôi sẽ ra đi. Thân thể đã bị tàn phá nặng nề ngoại trừ cái đầu, tôi vẫn
rất yếu một cách đáng ghét...Tôi có thể ngồi dậy không vấn đề gì cả, nhưng khi nằm
tôi vẫn còn khả năng để đào xới những công việc này". footnote:[Ruhle, Otto, Karl Marx, pp. 262.]

"Công việc" mà Marx nhắc đến đó là những nghiên cứu, chuẩn bị cho tập đầu cuốn
_"Tư Bản - Capital"_. Marx bị thuyết phục rằng cuộc cách mạng sẽ không thể thành
công nếu như quần chúng lao động không có triết học cách mạng về lịch sử, kinh
tế và tiến bộ xã hội. Marx viết _"Tư Bản - Capital"_ để cho thấy tại sao cần phải
có bạo lực phá bỏ trật tự hiện tại - không chỉ chứng minh là đúng mà còn là việc
không thể tránh khỏi. Chúng ta sẽ phân tích luận điểm này ở chỗ khác, nhưng ở
điểm này cũng đủ chỉ ra thấy Marx nhìn nhận công việc viết lách như một nhiệm vụ
không dễ chịu cho lắm, nó cần phải được hoàn thành trước khi cộng sản quốc tế đâm
chồi nảy lộc.

Suốt năm 1865, Marx vật lộn cho ra bản copy cuối cùng của tập đầu tiên để sẵn
sàng cho việc xuất bản. Marx nói với Engels muốn kết thúc việc này nhanh chóng, nó đã là
cơn ác mộng thực sự hoàn hảo.

Marx thường tận hưởng giai đoạn nghỉ ngơi ngắn sau mỗi đợt ốm, viết cho Engels: "
Hãy coi cuốn sách chết tiệt này như là những vấn đề phải đối mặt. Cuối cùng thì
nó cũng hoàn thành vào cuối tháng 12". Engels đảm bảo với Marx sẽ lo toan nốt việc
còn lại mang cuốn sách đến với công chúng. "Ngày mà các bản thảo trở thành những
bản in thực sự, tôi sẽ uống cho đến say trong vinh quang!" Engels viết.

Phải đến tận tháng 3 năm 1867 tất cả các bản hiệu đính chỉnh sửa mới hoàn
thành. Marx làm việc với phía Đức để xuất bản cuốn sách bằng tiếng mẹ đẻ. Không
lâu sau đó các ấn phẩm được bắt đầu phân phối rộng rãi.

Nhưng khi xuất hiện trong các quầy sách, sự thành công đã không như Marx
và Engels mong đợi. Đường lối lý luận hoàn toàn dành cho quần chúng lao động, không
có sức thuyết phục đối với những nhà cải cách xã hội trí thức.
Điều đó đã để lại cho một lớp thế hệ trí thức sau này phải xin lỗi, xấu hổ cho những
gì đã họ đã tấn công, phá huỷ trật tự tồn tại vạn vật.
