=== Khép lại những năm tháng

Đến năm 1875, kinh nghiệm rút ra từ những cuộc đấu tranh của mình không làm cho
Marx thoả mãn. Quốc tế tan rã, những quyển sách viết nhằm biện minh cho chính sách
mình làm là đúng thì giờ đã phủ đầy bụi trên các kệ sách trong cửa hàng khắp Lục địa.
Marx tiếp tục viết thêm hai tập nữa, nhưng ngọn lửa trong con người Marx đang lụi
tàn. Sau cái chết của Marx, công việc còn lại của Engels là xuất bản nốt tập hai
vào năm 1885, tập ba vào năm 1894.

Những năm tháng khép lại cuộc đời Marx thật vô nghĩa và cô đơn. Thất bại thảm hại
khiến Marx quay về với gia đình làm điểm tựa. Jenny luôn ở đó mang đến cho Marx
niềm an ủi và dễ chịu. Dưới sự dạy dỗ của mình, Marx để lại cho những đứa trẻ vết
sẹo mang theo cả cuộc đời. Cô con gái Eleanor đã tự tử sau một thời gian thống khổ
buồn tủi cùng người yêu Edward Aveiling khi bị Marx can thiệp vào chuyện tình cảm
lứa đôi. Một người con gái khác là Laura kết hôn với một bác sĩ thoái đảng, sau
đó đã cùng nhau tự tử theo một nguyện ước giữa hai người.

Đến năm  1878 gần như Marx không đả động gì đến công việc. Niềm tin sắt đá đã bị
tan vỡ thành từng mảnh. Các nhà lãnh đạo lao động phớt lờ Marx, còn những nhà
cải cách thì chế giễu, nhạo báng. Những lời nói của Marx cũng không còn có trọng
lượng gì cả ở trong nước lẫn nước ngoài.

Tinh thần của Marx đã đạt đến cực điểm tan vỡ khi sự nghiệt ngã của thời gian
giáng thẳng xuống người thân yêu duy nhất của mình ngoài Engels - đó là bà Marx.
Người vợ dịu dàng, quý bà lịch lãm và người bạn đời đồng hành chịu khó chịu khổ
đã mất vì ung thư vào ngày 2 tháng 12 năm 1881. Mười ba tháng sau, Jenny cô con
gái Marx yêu quí đã đột ngột ra đi. Sau này Engels viết: Marx người hùng, kể
cả khi đã chết. Marx cũng chỉ sống với Jenny được hai tháng ngắn ngủi.
Vào 2 giờ 45 phút, buổi chiều ngày 14 tháng 3 năm 1883, Marx chết trong khi ngồi
một mình trên ghế.

Ba ngày sau đó, có sáu hay bảy người gì đó đưa quan tài của Marx ra nghĩa trang
Highgate tại Luân Đôn, và duy nhất chỉ một người bạn đi theo - Friedrich Engels
đọc điếu văn tang lễ. Đó đích thực là bài điếu văn Marx muốn được nghe thấy - những
điều mà Marx chỉ có được khi nằm xuống và sẽ không bao giờ có được trong cuộc sống:
sự vinh danh ca tụng rực rõ chói lọi.
