=== Lời Kết

Sự nghiệp đầy biến động, thăng trầm không ngừng nghỉ của Marx đã kết thúc. Đó là
cuộc đời thương tâm, đầy ắp tham vọng cháy bỏng, sự tuyệt vọng thường trực và liên
tục thất bại. Bất kể nhìn từ góc độ nào dù là bạn hay kẻ thù, có lẽ bị kịch thật
sự của cuộc đời Marx được tìm thấy ở những lý do khó hiểu, gần như là bản năng tự
nhiên gieo mầm sự tự huỷ diệt trong tất cả các dự án mình gây dựng.

Sản phẩm tạo ra dưới ngòi bút của Marx dường như vô tận, dày cộp, phức tạp hoặc
đau đầu. Những ai không thể hấp thụ được hết sẽ không cảm thấy được Marx đã thổi
vào chủ nghĩa cộng sản chính bản chất tự nhiên của con người Marx.
Sự thù hận với chính quyền thể hiện rõ trong lời kêu gọi cuộc cách mạng thế giới.
Vì không có khả năng hoặc chối bỏ cạnh tranh với kinh tế tư bản nên Marx lên án
công khai gay gắt, nặng nề và khẳng định tiên đoán sự sụp đổ của kinh tế tư bản
là không thể tránh khỏi.
Cảm giác bất an trong sâu thẳm hình thành trí tưởng tượng hão huyền, một niềm tin
không lay chuyển về sự ra đời bộ máy diễn giải lịch sử mới, tạo nên tiến bộ và
thiên niên kỷ Cộng sản sẽ là tất yếu.
Thái độ cá nhân đối với tôn giáo, đạo đức và cạnh tranh sinh tồn khiến Marx mong
đợi đến một thời kì nhân loại sẽ không còn tôn giáo, đạo đức, và cũng không còn
phải cạnh tranh để tồn tại.
Marx muốn sống trong một xã hội không còn giai cấp, không nhà nước , không cạnh
tranh, nơi mà con người chỉ cần làm theo khả năng và hưởng thụ vật chất theo nhu
cầu.

Một tính cách khác được Marx chia sẻ với những đứa con cộng sản trí thức
(intellectual off-spring -- Communism) đó là cần phải giữ khoảng cách để được ngưỡng mộ,
kể cả với bạn bè. Vì lý do này nhiều nhà viết tiểu sử hiểu Marx như hai con người
khác nhau. Mọi người có thể cảm thấy rất ngưỡng mộ lý thuyết của Marx nếu như không
ở bên cạnh, nhưng nếu tiếp xúc gần hơn, Marx trở nên một thực thể hoàn toàn khác.
Bakuin đã gọi Marx là _"nhà kinh tế tối thượng và nhà xã hội thiên tài của thời đại"_
nhưng sau đó đưa ra đánh giá về Marx:
_"Người đàn ông mà sự ích kỉ đã tiệm cận với điên loạn..."_

Marx yêu bản thân nhiều hơn bạn bè, hay tín đồ, và chẳng có tình bạn nào
có thể đặt lên trên sự huyễn hoặc tự cao tự đại của bản thân mình...Marx không bao giờ
tha thứ cho bất kì sự vi phạm nào dù là nhỏ nhất. Để được yêu quý, mọi người phải
tôn sùng, coi Marx là thần tượng và muốn có được sự khoan dung từ Marx, ít nhất
mọi người phải cảm thất sợ hãi.
Marx thích được vây xung quanh bởi đám người cúi đầu, biết nghe lời và những kẻ
nịnh bợ. Những kẻ này đều giống nhau, tuy có một số khác đáng chú ý hơn
trong đám thân cận. Nhìn chung có thể nói trong đám thân cận này chẳng có sự thẳng
thắn hay tình huynh đệ gì cả, chỉ đầy âm mưu và những thứ xã giao.
Có sự đấu tranh ngấm ngầm và thoả hiệp giữa những kẻ yêu bản thân, trục lợi cá nhân
và nơi những thứ huyễn hoặc ảo tưởng có đất diễn, không có bất kì nơi nào cho cái
gọi là tình anh em bằng hữu.
Mọi người phải tự bảo vệ, sợ bị hy sinh, bị thủ tiêu. Trong vòng xoay của Marx giống
như một xã hội tự ngưỡng mộ lẫn nhau mà ở đó Marx là tối cao ban phát
danh dự, nhưng trong vòng xoay đó Marx cũng là kẻ giả tạo bất biến và ác ý,
không bao giờ có sự cởi mở thẳng thắn, dốt nát bức hại những người mình nghi ngờ,
hoặc những người không cho thấy sự kính trọng tôn sùng như Marx mong đợi. Không có
một giới hạn nào cho sự đê tiện và bẩn thỉu được thực thi một khi mệnh lệnh bức hại
được Marx đưa ra.

Việc thường xuyên rót vào đầu những tín đồ của mình chất xúc tác a-xít huỷ diệt
sự khoan dung và lòng vị tha có thể được giải thích một phần vì sự hoàn toàn chắc chắn
của Marx tin tưởng lý thuyết mình đã pha chế, sáng tạo ra là một viên hồng
ngọc quý giá của sự thật vũ trụ này.

Trong những ngày hoàng kim sức mạnh dồi dào, Marx thường đẩy lui sự phản kháng
với tuyên bố lay sơn cùng sự tự tin tối thượng:
_"Lịch sử tiến hoá trong tay các bạn!"_. Marx hét về phía những người ủng hộ.
_"Chủ nghĩa tư bản, được mang đến bởi quy luật lịch sử tiến hoá, nó sẽ bị phá
huỷ bởi vận động không thể tránh khỏi của chính những quy luật này.
Tầng lớp tư sản, thương gia, là chủ nhân của hệ thống tư bản đã xuất hiện trên
sân khấu của lịch sử. Chúng sẽ phải biến mất khi hệ thống kia bước khỏi vũ đài lịch sử.
Các bạn, những người vô sản, các bạn đang nuôi sống, vận hành cho xã hội tư
sản bằng những trái ngọt thành quả trong nghành công nghiệp. Nhưng xã hội chủ nghĩa
sẽ là kết quả hữu cơ cần thiết của tư bản chủ nghĩa, bản chất của kết quả sau
phản ảnh bản chất của cái đi trước. Kết thúc chủ nghĩa tư bản, bắt đầu chủ nghĩa
xã hội là kết quả logic tất nhiên. Các bạn những người vô sản, cùng chung tay hợp
lực đánh đuổi chủ nghĩa tư bản, phải cần thiết hành động để kết thúc bọn tư sản.
Các bạn chỉ cần làm đúng nhiệm vụ được giao phó. Tất cả bạn cần là sẵn sàng!.
Lịch sử sẽ làm điều này dễ dàng nhất cho bạn. Bạn không cần phải ấp ủ một ý tưởng
nào, vạch kế hoạch hay khám phá một  Nhà nước tương lai nào. Bạn không cần phải
dự đoán thế giới một cách giáo điều. Bạn chỉ cần đặt tay lên những nhiệm vụ đang
chờ đợi bạn. Ý nghĩa việc các bạn sẽ làm sẽ thấy được trong cuộc chiến đấu tranh
giai cấp không ngừng nghỉ, có chủ đích, thống nhất. Vương miện sẽ được trao cho
chiến thắng của cách mạng xã hội chủ nghĩa."_

Khi Marx chết, trước những giờ phút khép lại cuộc đời, không có nhiều ý kiển được
gửi đến hỏi xem Marx còn nhớ gì về những thứ mình đã phấn đấu, tạo ra một "cuộc giải
phóng chính nghĩa" thất bại. Trong khi Tây Âu coi nhẹ cuộc cách mạng bạo
lực chỉ là một phần lịch sử cải cách xã hội thế kỉ 19 thì ở phía Đông, gã khổng
lồ đang ngủ say bị đánh thức thô bạo bởi lời kêu gọi hưởng ứng cách mạng của Marx.
Tất nhiên đó là nước Nga.

Trước khi nghiên cứu cuộc cách mạng Nga, chúng ta quay trở lại đánh giá tóm tắt một số
lý thuyết Marx và Friedrich Engels đã để lại như một di sản cho các môn đồ của
Cộng Sản Quốc Tế, nếu không thì có thể sẽ khó hoặc không thể hiểu được.
Lý thuyết này có thể giải thích nhiều sự kiện của cách mạng Nga và một số hoạt động
của cộng sản sau này.
