=== Gia đình Karl Marx

Gia đình Marx sống tại Luân Đôn trong tình trạng cực kì nghèo khổ kể từ đây.
Sự kết hợp đột ngột kì lạ của cảm xúc được Marx bộc lộ trong những bức điện
tín suốt thời gian này. Một mặt Marx rất xúc động lo lắng cho vợ con không có được
điều kiện sống cơ bản tốt nhất. Marx thú nhận với Engels qua thư rằng những giọt
nước mắt than thở trong đêm của vợ đã vượt quá sức chịu đựng.
Nhưng cùng trong bức thư ấy, Marx hồ hởi vui sướng giải thích làm thế nào có thể
quản lý toàn bộ thời gian nghiên cứu lịch sử, kinh tế chính trị và các vấn đề xã hội,
làm thế nào để trả lời các câu hỏi cho tất cả các vấn đề của thế giới.

Năm 1852 con gái nhỏ Francisca qua đời. Hai năm sau đánh dấu sự ra đi của đứa
con trai, Edgar và tiếp hai năm sau đó thêm một đứa trẻ mất ngay khi sinh.

Một số đoạn trong các bức thư của bà Marx cho thấy sự trung thành phi thường của
người phụ nữ bất lực nhìn những đứa con đói ăn đang chết mòn dần quanh mình trong khi
cha chúng thì tối ngày vùi đầu ở thư viện bảo tàng Anh.

[quote, Mrs.Marx]
Hãy để tôi mô tả lại một ngày cuộc sống thực sự diễn ra như thế nào...Tôi
phải tự xoay xở nuôi nấng, chăm sóc những đứa con trong cơn đau ngực và lưng hành
hạ, dịch vụ thuê mướn vú nuôi ở đây đắt đỏ quá sức chi trả.
Thiên thần bé nhỏ tội nghiệp của tôi uống những giọt sữa đang cạn kiệt dần pha đầy
những khổ đau tủi nhục trong đau đớn tột cùng ngày lẫn đêm.
Kể từ khi xuất hiện trên trái đất này, chúng chưa có nổi một đêm ngon giấc, nhiều
lắm cũng chỉ ngủ được 2 hay 3 tiếng mỗi đêm. Những cơn ho co thắt thường xuyên
đặt chúng giữa sự sống và cái chết. Khi cơn đau lên đỉnh điểm, cơ thể bé bỏng gắng hết sức
còn lại mút chặt làm núm ngực của tôi sưng lên rỉ máu, những
tia máu đỏ hồng thường xuyên trào lên khoé miệng nhỏ bé của thiên thần tội nghiệp.
Một ngày khi đang ngồi trong phòng, bà chủ nhà bỗng nhiên xuất hiện...
Chúng tôi không có nổi 5 bảng để trả ngay lúc đó, hai người môi giới đã xông vào
lấy hết đi đồ đạc những gì chúng tôi có: giường, quần áo, thậm chí là cả cũi trẻ
con, đồ chơi của con gái bé bỏng.  Họ đe doạ sẽ lấy đi tất cả trong 2 tiếng đồng
hồ nữa - thật may mắn họ đã không làm như vậy. Nếu điều đó xảy ra có lẽ tôi đã
phải nằm trên sàn lạnh cóng bên cạnh những đứa trẻ đang bị đông cứng.
Chúng tôi phải rời đi ngày hôm sau, đó là một ngày mưa lạnh. Chồng tôi cố gắng
tìm một chỗ ở tạm nhưng mọi người đều ái ngại khi biết còn bốn đứa trẻ nheo nhóc
nữa cũng đang cần sự che chở. Cuối cùng thì một người bạn đã giúp đỡ, chúng tôi
trả nợ những gì chúng tôi đã vay mượn. Tôi nhanh chóng bán hết đồ đạc giường tủ
để lo thuốc men, bánh mỳ và sữa cho gia đình. footnote:[Ruhle, Otto, Karl Marx, pp. 202-204.]

Những năm tháng thế này cứ thế trôi qua. Hàng trăm bức thư, theo đúng nghĩa đen,
đã được trao đổi giữa Marx và Engels, gần như tất cả trong số đó nói về việc tiền
bạc lấy ở chỗ này hay chỗ khác. Đặc trưng thường thấy trong các bức thư của Engels
như là: "Đính kèm theo là giấy bưu điện yêu cầu 5 bảng", còn khi đó thì Marx
bắn ra những đoạn bực dọc: "Mẹ tôi chắc chắn là sẽ phản đối bất kì hoá
đơn nào đổ lên đầu bà ấy", hay như: "Trong 10 ngày, chúng tôi sống như những kẻ
mất hồn trong cái nhà này", hoặc là: "Anh sẽ đồng ý rằng tôi đã ngán đến tận cổ
cái món dưa chuột muối của bọn tư sản".

Cuộc sống bế tắc nhiều cay đắng bỗng loé lên một tia hy vọng. Trong suốt thời gian
thất vọng và suy sụp khi Engels không thể lo chu cấp, Marx đã tới Hà Lan gặp một
người chú giàu có. Ông ta đã hào phóng cho Marx số tiền không nhỏ, 160 bảng.
Số tiền này đủ để Marx có thể bắt đầu lại, trang trải hết nợ nần. Nhưng với số tiền
trong tay, Marx đi quyết định đi vòng quanh Đức, thăm mẹ tại Treves, tới Berlin
gặp bạn bè cũ đi uống, chụp ảnh, thư giãn. Phần lớn thời gian ở đó, Marx đóng vai
như một quý ông thành đạt, nhàn nhã. Sau hai tháng, quý bà Marx chào
đón người đàn ông đi du lịch trở về. Tưởng chừng như mọi nợ nần, hoá đơn sẽ được
trả hết, đồ đạc, quần áo mới sẽ được sắm, bà Marx tá hoả khi nhận ra rằng 160 bảng
chẳng còn lại một xu.
