=== Phong trào quốc tế thứ nhất

Năm 1862, một cuộc triển lãm quốc tế được tổ chức tại Luân Đôn, diễu hành những
thành tựu đạt được từ cuộc cách mạng công nghiệp. Những người tổ chức mong muốn
tạo ra một bầu không khí thiện chí mang tầm quốc tế. Do đo họ mời tất cả các
nước tham gia không chỉ mang trưng bày sản phẩm mà còn mời đại diện của công nhân
các nước đến trao đổi ý tưởng, thể hiện thiện chí với tất cả những người công nhân
muốn tham gia.

Từ năm 1860 những người lãnh đạo đảng lao động tại nước Anh đã có được sức mạnh đáng
kế, và nhân dịp triển lãm này họ nhận ra rằng đây là cơ hội tuyệt vời để thành lập tổ
chức lao động công nhân quốc tế. Họ tận dụng tối đa cơ hội này để kết bạn với tất
cả các nhà lãnh đạo đảng lao động đến từ Đức, Pháp, Ba Lan và Hà Lan. Trong thời gian
ngắn họ đã thành lập được văn phòng thường trú quốc tế với trụ sở đặt
tại Luân Đôn. Một trong những nhà lãnh đạo của phong trào là người thợ may có tên
Eccarius, cựu cánh tay phải của Marx trong suốt thời gian hoạt động của Liên Đoàn
Cộng Sản. Và tất nhiên Marx được Eccarius mời ra nhập phong trào ngay từ lúc nó
bắt đầu.

Ngay lập tức Marx đặt quyết tâm cho mình - nhưng trong giới hạn. Đó là một phần
bài học rút ra từ thất bại của Liên Đoàn Cộng Sản. Tổ chức mới được gọi dưới cái
tên "Hiệp Hội những người Lao Động Quốc Tế - International Workingmen's Association",
nhưng thường được tham chiếu dưới tên khác là "Quốc Tế Thứ Nhất - First International".
Chừng nào Marx còn kiểm soát được cảm xúc cá nhân thì Marx rất có năng lực thực
hiện ảnh hưởng thích hợp đến những nhà lãnh đạo lao động ở các nước khác.
Cẩn thận đứng sau bức màn điều khiển mọi thứ, Marx đã có thể truyền tải gần như
tất cả các ý tưởng của mình cho những chương trình mang chiều hướng mềm mỏng
ôn hoà hơn được đề xuất bởi "những nhà cải cách xã hội có đầu óc".
Lối cư xử có vẻ hoà nhã như thế này không phản ánh đúng tự nhiên như bản chất con người
của Marx và Marx cũng thừa nhận với Engels rằng mình đã bị ép phải thoả hiệp để giữ hoà
bình:

[quote, Karl Marx]
Đề nghị của tôi được tất cả hội đồng tiểu ban thông qua. Nhưng chỉ một việc tôi
đã phải cam kết cho vào phần mở đầu của quy định hai đoạn về "quyền" và "nghĩa vụ",
và cả về sự thật, đạo đức, sự công bằng. Cho vào thì cho thôi, nhưng nó không thể gây
bất kể tác hại gì...Sẽ đến lúc cho phép những phát biểu cứng rắn trước khi phong
trào thức tỉnh trở lại. Chúng ta phải mạnh mẽ về chất, nhưng cần vừa phải, tiết chế về
hình thức. footnote:[Ruhle, Otto, Karl Marx, pp. 248-249]

Mặc dù rất quyết tâm với nguyên tắc "tiết chế, vừa phải" này, tuy nhiên không lâu
sau thì những cảm nghĩ thật sự của Marx cũng bộc lộ ra bên ngoài. Marx lo lắng hai
việc: thứ nhất, cần phải tạo ra học thuyết cứng rắn cho các nhà giải phóng cách mạng
có khả năng truyền lửa tới những công nhân làm việc tại những ngành công nghiệp quan trọng
một tinh thần sẵn sàng hành động; thứ hai là cần loại bỏ những ai có tiềm năng đe doạ
vị trí lãnh đạo của Marx trong phong trào mới. Những gì Marx thực sự đang suy ngẫm
dự tính bấy lâu đó là việc _thanh trừng trong đảng_.

Người đầu tiên cảm nhận được sức mạnh thanh trừng này đó là nhà lãnh đạo đảng lao động
người Đức - Herr von Schweitzer. Tất cả những học trò của Marx và Engels dường
như đồng ý rằng không có sự khoan dung nhân nhượng hay thương xót nào đối với những
đồng chí được cho là cần loại bỏ khỏi đảng. Chiến dịch tuyên truyền cáo buộc Schweitzer
làm việc cho link://++https://en.wikipedia.org/wiki/Otto_von_Bismarck++[Bismarck]
- mệnh danh người đàn ông thép của Đức. Mặc dù đây là sự bịa đặt
trắng trợn nhưng uy tín của Schweitzer cũng vì thế mà bị phá huỷ. Thậm chí ngày
nay một số sử gia sử dụng cáo buộc của Marx làm cơ sở cho tuyên bố Schweitzer là
kẻ phản bội phong trào lao động.

Một trụ cột khác trong đảng rơi vào chiến dịch thanh trừng là
link://++https://en.wikipedia.org/wiki/Mikhail_Bakunin++[Mikhail Bakunin],
người Nga đầu tiên quan tâm đến những hoạt động cách mạng đã chạy trốn khỏi nhà tù
ở Nga rồi lánh nạn qua sống tại Geneva.

Bakunin trở nên rất nhiệt thành, sốt sắng ủng hộ các nguyên tắc của Marx, và khả
năng lãnh đạo của Bakuin bắt đầu bị thu hút bởi những yếu tố nhất định từ các nguyên
tắc này. Đó là một thảm hoạ chết người. Marx ngay lập tức quyết định tiêu diệt  Bakunin.
Về kỹ thuật sử dụng thì cũng chẳng có gì khác như đã làm đối với Schweitzer, chỉ có điều
là Marx cùng Engels buộc tội Bakuin làm gián điệp cho Nga Hoàng - Russian Czar.
Chiến lược này chỉ có hiệu quả trong chốc lát, vì vậy sau đó họ tung tin cáo buộc Bakuin
đã biển thủ 25.000 francs (sau này được chứng minh là hoàn toàn giả mạo).
Cuối cùng để kiểm soát những cái chết nhân đạo, Marx đã yêu cầu thành công quốc
tế loại bỏ Bakuin ra khỏi Hiệp hội. Bằng cách này, Marx tự cảm thấy rằng  mình
đã tiêu diệt được người cuối cùng có thể đe doạ nghiêm trọng đến sự lãnh đạo của
mình. Marx không hề biết rằng mặc dù bị thanh trừng nhưng Bakuin vẫn trung thành
với lý luận của Marx. Thậm chí Bakuin còn dịch nhiều cuốn sách của Marx sang tiếng Nga,
gieo mầm cho một đất nước đầu tiên trong xã hội hiện đại bị cai trị bởi chế độ
độc tài cộng sản.

Sự lo sợ thanh trừng kẻ thù cá nhân của Marx trong phong trào Quốc tế đã tạo ra
nghi ngờ mạnh mẽ, mất tin tưởng lẫn nhau và bất hoà trong đảng, dẫn tới sự phá huỷ
hoàn toàn của tổ chức này. Thực tế thì sự kết thúc của Quốc Tế Thứ Nhất đã trở
nên gần hơn theo gót việc thanh trừng Bakuin. Liên minh công đoàn thương mại tại Anh
quốc bắt đầu cấm phong trào cách mạng quốc tế và các nhóm công nhân trên toàn Lục địa
cũng bắt đầu phớt lờ những bắt buộc của Hiệp hội này. Cuối cùng vào ngày 8 tháng
9 năm 1873, đại hội lần cuối của tổ chức "Hiệp Hội những người Lao Động Quốc Tế - International Workingmen's Association"
được diễn ra tại Geneva, 13 vị khách mời đã đồng ý tham dự nhưng không xuất hiện
vào phút chót. Đối với tất cả những mục tiêu và dự định thực tế, Quốc Tế Thứ Nhất
đã chết.
