[abstract]
== Giới thiệu

=== Sự nổi lên của những người Marxist

Thật là khủng khiếp và đáng sợ khi một con người thèm muốn tạo ra nhân loại
theo cách riêng của mình. Điều này đã trở thành mục đích và tham vọng tột cùng
của Karl Marx. Ông ta muốn tạo ra một xã hội không phải để những người khác
bình đẳng với mình, thực tế thì hoàn toàn ngược lại.

Marx hy vọng xây dựng một hình ảnh giống như pho tượng vĩ đại với Karl Marx là bộ não,
người kiến tạo và tất cả người khác phục vụ mình như chân tay, tai mắt, mồm miệng.
Marx quan sát thế giới và mơ đến một ngày nhân loại bị ép buộc vào một hình ảnh xã
hội khổng lồ hoàn toàn tuân theo giấc mơ của Marx về một xã hội hoàn hảo.

Để đạt được mục đích của mình, Marx yêu cầu hai thứ: thứ nhất phải huỷ diệt
hoàn toàn sự phản kháng, làm sụp đổ toàn bộ hệ thống chính phủ hiện thời, sụp đổ toàn
bộ nền kinh tế và toàn bộ xã hội. Sau đó Marx viết: __"Tôi sẽ bước qua đống đổ nát
của đấng sáng tạo!"__. Điều thứ hai: cần thiết phải tạo ra một hình mẫu nhân loại mới.

Marx hình dung ra một nhóm người được huấn luyện với phản xạ có điều giống như
nhóm chó được link://++https://vi.wikipedia.org/wiki/Ivan_Petrovich_Pavlov++[Pavlov]
nghiên cứu, chỉ cần có hiệu lệnh từ chủ nhóm này hành động ngày lập tức không
cần suy nghĩ. Marx muốn một cuộc chạy đua của nhân loại con người sẽ không còn
phụ thuộc vào ý chí tự do, nguyên tắc chuẩn mực, đạo lý, hay lương tâm làm thước đo
để hành động. Có lẽ một cách vô thức, Marx đã đang tạo ra một chủng người được lập
trình để suy nghĩ giống như những kẻ tội phạm.

Tạo ra một cuộc chạy đua như này đã là giấc mơ của những kẻ khát thèm quyền
lực tột độ trong hơn 4000 năm lịch sử trải qua. link://++https://en.wikipedia.org/wiki/Nimrod++[Nimrod]
đặt nền móng cho thiết kế ý tưởng, link://++https://en.wikipedia.org/wiki/Plato++[Plato]
chau chuốt nó, link://++https://vi.wikipedia.org/wiki/Henri_de_Saint_Simon++[Saint Simon] thăng hoa nó
và Karl Marx hiện thực hoá nó.

Ngày nay những kẻ với đầu óc tội phạm được lập trình đã đủ đông trên trái
đất để có thể xâm chiếm các quốc gia hay lục địa khác, thay đổi luật pháp và đường
ranh giới, ra lệnh chiến tranh hay hoà bình. Họ có thể được gọi là Homo-Marxian
hay _người theo chủ nghĩa Marxist_. Họ khẳng định rất rõ ràng một cách đáng sợ,
họ sẽ trở thành những người thống trị của thế kỉ 20.

Những người theo chủ nghĩa Marxist đang gây ra sợ hãi, hoang mang cho phần còn lại
của nhân loại bởi vì với đầu óc tâm lý tội phạm được cài đặt sẵn sẽ không hành động
hay cư xử như những người bình thường vẫn tư duy.

Lấy ví dụ, nếu một người có ý tốt mời một kẻ tội phạm chuyên nghiệp tới ăn tối ở
nhà mình thì ánh mắt xảo quyệt của vị khách kia sẽ có khả năng đảo xung quanh
quan sát kỹ lưỡng những đồ đựng thức ăn bằng bạc sáng bóng đắt tiền, và đồ ăn
ngon khác nhau, hoàn toàn bỏ qua sự chân thành và tình cảm ấm áp mà chủ nhà đang
muốn cố gắng truyền tải.

Trong thực tế, tâm lý tội phạm rất có thể sẽ kết luận chủ nhà không chỉ có trái
tim yếu đuối mà còn có lý trí yếu đuối. Cuối cùng anh ta sẽ tự thuyết phục mình
đưa ra quyết định một người yếu đuối như thế không xứng đang có được
nhiều thứ tốt đẹp như vậy. Và sau đó anh ta sẽ dành tất cả thời gian còn lại của
buổi tối suy nghĩ tìm cách làm sao có thể quay trở lại ngay trong bóng đêm tối nay,
cuỗm hết những thứ đồ giá trị, đắt tiền của vị chủ nhà tốt bụng.

Bất cứ ai đã quen thuộc với lịch sử lãnh đạo Cộng sản trong suốt hơn 100 năm qua
ngay lập tức sẽ nhận ra kiểu cách tư duy này trong công việc. Điển hình là sự lạm
dụng tình bạn một cách tráo trở vô đạo đức chơ trẽn đối với Hoa Kỳ trong thế
chiến thứ hai.

Những người theo chủ nghĩa Marxist gây hoang mang, khó hiểu cho những người làm
việc cùng, bởi vì họ luôn có vẻ không logic hợp lý, rất khó đoán định hành vi.
Tuy nhiên trong thực tế, họ đã hạ giá trị tư duy của mình xuống mẫu số chung
thấp nhất mà một cách bình thường tự nhiên ai cũng có thể nghĩ được.
Họ dùng thứ luật rừng của những kẻ sống sót ích kỷ tạo ra kiểu sống độc quyền.
Xét về những khía cạnh này thì những con người đó hợp lý gần như đến độ chính xác
toán học. Trong khủng hoảng hay tĩnh lặng, phản ứng của họ luôn cơ bản là nhất quán
và do đó có thể dự đoán được.

Người Marxist tự nghĩ rằng họ hoàn toàn được tạo ra từ bụi đất trên trái
đất này nên họ giả vờ như không còn có vai trò nào khác nữa. Họ phủ nhận bản thân về
khả năng tồn tại linh hồn, từ chối chấp nhận sự bất tử của sinh mệnh. Họ tin rằng
họ không có Đấng Sáng Tạo, và không có mục đích hoặc lý do gì khác cho sự tồn tại
ngoại trừ một sự tích luỹ ngẫu nhiên của các lực ngẫu nhiên tình cờ trong tự nhiên.

Vì không có đạo đức chỉ dẫn nên họ tiếp cận vấn đề một cách trực tiếp và khá đơn
giản. Tự bảo vệ được đưa ra như là biện minh duy nhất cho hành vi của chính mình
và "`động cơ ích kỷ`" hoặc "`sự ngu dốt`" là cách duy nhất họ giải thích cho
hành vi của người khác.
Với người Marxist việc ký kết 53 hiệp ước và vi phạm 51 trong số đó không phải là
đạo đức giả, mà theo họ đó là chiến lược. Việc vâng lời theo ý kiến chỉ đạo từ cấp
trên nhằm che dấu sự thật không phải là sự lừa gạt, mà là công cụ cần thiết của
chính phủ.
Người Marxist tự thuyết phục bản thân không có việc gì ác hay xấu xa nếu như
nó đáp ứng được cho sự tiện lợi, hiệu quả. Họ tự giải thoát bản thân khỏi hạn
chế ràng buộc về danh dự và nguyên tắc đạo lý mà nhân loại trước đây đã cố gắng
sử dụng làm cơ sở cho các mối quan hệ hài hoà của con người.

Lịch sử đã chứng minh với tình trạng tâm lý như vậy, người Marxist có thể
thuộc nhóm người luôn cảm thấy bất an. Họ tin rằng họ là một hiện
tượng ngẫu nhiên trong một vũ trụ, không có mục đích, nên họ thèm muốn vô độ nhằm
thống trị mọi thứ. Họ thừa nhận họ không cảm thấy an toàn cho tới khi thực hiện
xong tất cả việc này. Họ không chỉ phải chinh phục nhân loại, mà còn tự gán cho
mình nhiệm vụ chinh phục không gian, vật chất, và chế ngự tất cả lực lượng thực
tại trong vũ trụ, nhằm mang lại sự trật tự mới, thoát khỏi hỗn loạn tự nhiên.
Họ nói họ phải làm việc đó vì con người là sinh vật duy nhất tồn tại,
có khả năng ngẫu nhiên và rất may mắn làm được những công việc trí tuệ, sáng tạo.
Họ tin người Marxist thuộc loại người tiến bộ nhất nên phải chấp nhận trách nhiệm
của sinh mệnh tối thượng. Họ hoàn toàn thẳng thắn trong tuyên cáo phát biểu rằng
người Marxist sẽ trở thành chủ nhân cuối cùng, Chúa của trái đất và sau đó là
của toàn bộ vũ trụ.

Dưới ảnh hưởng tác động của cái gọi là mở rộng lý thuyết tham vọng, rất nhiều
người không theo chủ nghĩa Marxist bị sập bẫy trong cơn thuỷ triều giàu cảm xúc của
lý tưởng huyễn hoặc này, và đồng thời tự nguyện cuốn theo dòng chảy tới bến bờ,
hy vọng sẽ là miền đất hứa của sự thánh thiện nhân tạo.
Tuy nhiên trong những năm gần đây, một số lượng lớn những con người hành hương
này đã mạo hiểm cuộc sống để quay trở lại hiện thực. Mọi người trở về với
cùng một câu chuyện giống nhau. Người Marxist được cho là cư xử chính xác giống
như những sinh vật trưởng thành trong rừng nhiệt đới, và chính họ tin như vậy.
Họ nghi ngờ, lo sợ mọi người khác và họ phản ứng với từng vấn đề như thể sự tồn
tại của mình đang bị đe doạ.

Mặc dù người Marxist đòi hỏi quyền được cai trị nhân loại, nhưng họ đã bỏ qua
nhưng bài học cơ bản nhất được học trong hàng ngàn năm kinh nghiệm của loài người.
Những người hành hương trở về đem theo một bằng chứng: người Marxist đã đảo ngược
hướng đi của lịch sử. Họ biến người khác chống lại chính họ.

Con người đã nhận ra chính mình thông qua những cuộc khủng hoảng trong lịch sử.
Những người Marxist đã có thể không xuất hiện trên trái đất này tại một thời điểm
phi logic hơn. Trong thời đại khi các tiến bộ công nghệ mang lại sự thoải mái tiện
nghi cho nhân loại thức ăn, quần áo, nhà cửa thì những người Marxist lại thể hiện
như một sư đe doạ quân sự cho những thành tựu hoà bình này. Cảm giác bất an khiến
họ phải đòi hỏi yêu cầu được quyền kiểm soát độc quyền tất cả các vấn đề của nhân
loại trong khi mà gần như các dân tộc khác lại muốn tạo ra một Liên Hợp Quốc đích
thực, dành riêng cho hoà bình và sự thịnh vượng chung toàn thế giới.

Người Marxist không che dấu mục đích cuối cùng: họ sinh ra để cai trị thế giới.
Họ biết rằng họ vẫn chưa trưởng thành, giống như những đứa trẻ vị thành niên
nên họ không thể nuốt sống toàn bộ nhân loại bằng một miếng tham lam. Do đó họ
phải tự thoả mãn từng miếng nhỏ, tại từng thời điểm và chúng ta sẽ nhìn
thấy sau này họ nuôi dưỡng một cách trật tự "`thời gian biểu cho sự chấn áp`", dõi
theo với một sự kiên định chết người. Theo những lời tiên tri của Cộng sản, thời
gian cho thế giới tự do đang dần cạn kiệt.

Tình trạng khó khăn tiến thoái lưỡng nan này đẩy phần còn lại của nhân loại đang
trong sợ hãi, chưa bị chế ngự vào tình thế buộc phải chọn một trong ba khả năng
có thể cho hành động tương lai:

. Họ có thể ngoan ngoãn chịu trận.
. Họ có thể cố gắng cùng tồn tại.
. Họ có thể bắt đầu hành động kéo những kẻ bắt nạt hung hăng kia xuống đất.

Giống như người viết lo lắng, sẽ không có một câu trả lời tuyệt đối nào cho những
con người tự do phải đưa ra lựa chọn cuối cùng trên con đường hành động của mình.
Trong thực tế chỉ có một lựa chọn cho phép đó là luật sinh tồn.
Cúi đầu chịu trận chắc chắn không phải là giải pháp của những con người đang cảm
nhận được nhịp đập rộn ràng của sự tự do tuôn chảy trong tĩnh mạch.
Và chẳng ai sẽ dám chấp nhận lời đề nghị của Cộng sản như một giải pháp dài hạn
bởi vì không ai có thể biết được đằng sau chương trình nguy hiểm chết người
"`cùng cộng sinh`" là cái gì.

Vậy cái gì còn lại?

Vài năm trước khi còn làm việc tại FBI, người viết đã dần nhận ra rằng những
chuyên gia về chủ nghĩa Marxist từ lâu đã biết có nhiều cách để chấm đứt chủ
nghĩa Cộng sản máu lạnh. Nếu những con người yêu tự do cùng hành động đúng một
thời điểm thì việc này có thể hoàn thành mà không cần phải có một cuộc chiến tranh lớn
nào. Đó là lý do tại sao cuốn sách này ra đời dưới sự thuyết phục rằng con người
hiện đại sẽ trở nên ngu ngốc nếu như họ chấp nhận hiện tượng người Marxist như
một thực thể bất biến trên trái đất.

Có rất nhiều lý do lịch sử dễ hiểu, được thiết lập rõ ràng giải thích tại sao mọi
ảnh hưởng chính đáng, tích cực nên được đưa ra để loại bỏ những rào cản trên con đường dẫn
đến tiến bộ loài người. Điều này phải được thực hiện vì cả lợi ích của những người
Marxist cũng như phần còn lại của toàn bộ nhân loại. Họ là nạn nhân của những thử
nghiệm nhân tạo, mắc kẹt trong vòng quay tự duy trì sự phủ nhận loài người.
Chừng nào những người yêu tự do vẫn chiếm đa số trên trái đất thì vẫn sẽ còn
cơ hội tốt phá vỡ vòng quay này.
Tuy nhiên để đạt được mục đích, những con người tự do phải đạt được sự đoàn
kết, thông minh, năng động mạnh mẽ, ít nhất cũng phải mạnh mẽ giống như những mục
đích ảo tưởng hão huyền nhưng cực kì kiên định của những người Marxist.

Để kết thúc nghiên cứu, một danh sách các chính sách được đưa ra nếu áp dụng
đúng thời điểm thì có thể loại bỏ được những rào cản chủ nghĩa Marxist đã ném
ra trên con đường nhân loại đang đi. Những chính sách đó coi như một giải pháp tự động
thúc đẩy hiểu biết về lịch sử, triết học và mục đích cuối cùng của chủ nghĩa Marxist.

Nếu số lượng người nghiên cứu vấn đề này ngày càng đông đảo, lan toả trên toàn thế
giới trên một mặt trận thống nhất rộng lớn, thì cuộc đua sẽ có thể hoàn toàn dành
được thành quả vĩ đại phi thường khi kết thúc thế kỷ 20.

*Tự do trong thời đại của chúng ta cho tất cả mọi người*
