[preface]
== Lời mở đầu

Một trong những hiện tượng tuyệt vời của thời hiện đại đó là sự thành công không
thể tin được của thuyết âm mưu Cộng sản nhằm nô lệ hoá nhân loại. Một phần trong
kết quả của sự thành công này đã dẫn tới hai loại vô minh dốt nát. Thứ nhất:
sự vô minh không hiểu biết cần có những yêu cầu cần thiết gì cho việc thiết lập
hiến pháp duy trì tự do. Thứ hai: sự thiển cận thiếu hiểu biết về lịch sử, triết
học và chiến lược của chủ nghĩa cộng sản thế giới.

Nghiên cứu được thiết kế để mang đến những thực tế bao quát rộng lớn về chủ
nghĩa cộng sản gói gọn trong một cuốn sách này, được chắt lọc từ hơn một trăm
cuốn sách và bài luận, rất nhiều trong số đó được viết bởi chính những người cộng
sản. Cuốn sách cố gắng biểu đạt những Người Cộng Sản dựa trên yêu tố chân thực, ngây thơ
nhất của chính bản chất cộng sản, nhưng lược bỏ sự tuyên truyền và dối trá của họ.
Đó chính là lý do tiêu đề của cuốn sách này mang tên: *"`Cộng Sản Trần Trụi`"*.

Sinh viên ở phương Tây có xu hướng né tránh sự mơ hồ phức tạp của chủ
nghĩa cộng sản bởi vì họ có cảm giác như đang mò mẫm tìm trong chân không những
thứ chưa hề được biết đến. Do vậy trong nhiều năm trước, mục tiêu của tác giả
cố gắng để làm rõ những khái niệm để sinh viên có thể sẵn sàng hiểu được và bớt sợ
hãi hơn. Điều kinh khủng nhất trong sự sợ hãi của loài người đó chính là "sự sợ
hãi về những thứ không biết đến", tác giả mong muốn lan toả rộng rãi trong cộng
đồng nhằm giúp loại bỏ vũ khí của người giải phóng cách mạng cộng sản dưới bất
kì lợi thế tối cao nào, trước khi những sinh viên - bức tranh toàn cảnh của chủ nghĩa
Marxist - trở thành "`chủ nghĩa vật chất hiện đại trong hành động`"

Một nghiên cứu toàn cảnh về chủ nghĩa cộng sản có thể dễ dàng thoái hóa thành một
danh sách dài các ngày tháng, tên tuổi và quan điểm mà không giúp sinh viên đạt được sự hiểu
biết sâu sắc về lịch sử và triết học của chủ nghĩa Marxist. Nghiên cứu
này nỗ lực thực hiện để thể hiện chủ nghĩa Cộng sản một cách giống như thực thế sống,
hơi thở sống, những lực rung động trên trái đất chân thực nhất như bản thân cộng sản vậy.
Sự phát triển chính trị, triết học, lý thuyết kinh tế và những tên tuổi lớn của
Cộng sản thế giới đã được trình bày trong bối cảnh lịch sử của họ.

Kể từ khi ngày càng nhiều quan chức Cộng sản vỡ mộng, đào tẩu thoát ra khỏi Bức
Màn Thép đã vén lên nhiều bí ẩn từng bị che đậy trước đây, sự thật chính xác
về những suy nghĩ, nội tâm của những con người từng kiên định đi theo chủ nghĩa
Marxist. Do đó nghiên cứu này muốn trình bày nền văn minh Marxist mà không tham
chiếu đến những thứ tuyên truyền của nó, chỉ đề cập đến những lĩnh vực thực tế
hàng ngày, những lịch vực mà có hàng triệu con người đang gián tiếp cố gắng tìm
hiểu ý nghĩa thực sự của cuộc sống dưới chế độ Cộng sản là gì.

Bài trình bày có thể khó nghe hay khắt khe đối với những người chưa có cơ hội
nghiên cứu chủ nghĩa Marxist với tuổi đời hơn trăm năm. Nhưng đó là bởi vì biểu
hiện thực tế xuyên suốt ra bên ngoài của chủ nghĩa Cộng sản vốn nó đã là như vậy.
Marx thiết kế nó như vậy. Việc nghiên cứu đơn độc tách rời đôi lúc có thể rất khó
cho sinh viên nắm bắt được tinh thần, bản chất của chủ nghĩa Cộng Sản trong hành
động. Những cựu binh Triều Tiên, người tị nạn trốn khỏi bức màn thép, đại sứ trở
về từ Moscow, hay những người từng trải nghiệm về thể xác cũng như tinh thần trong
thế giới Cộng sản có thể thấy nghiên cứu này chỉ thể hiện được một phần nào và có
phần quá thận trọng.

Người đọc nên chú ý bản chất phức tạp tự nhiên của chủ nghĩa Cộng sản sẽ gây khó
khăn khi muốn đọc nhanh. Đôi khi toàn bộ khối lượng lớn nội dung được diễn giải thành
một vài đoạn nhỏ, nó sẽ hữu ích cho người đọc nếu có đủ thời gian để khám phá các
chương kỹ thuật hoặc triết học một cách kỹ lưỡng trước khi tiếp tục.
Để giúp người đọc xác định các điểm quan trọng nhất trong bài viết, ở mỗi đầu
chương trình bày danh sách sơ bộ các câu hỏi nhấn mạnh các ý chính.
Tác giả hy vọng sẽ không gây khó hiểu hay mập mờ cũng như mất mát nội dung trong
khi cố gắng tóm tắt ngắn gọn nhất có thể.

Tôi mắc nợ rất nhiều người đã hỗ trợ, đề xuất gợi ý, cung cấp dữ liệu kĩ thuật
liên quan đến công việc chuẩn bị cho nghiên cứu này. Tôi cũng nhận được sự giúp
đỡ rất có giá trị từ các thành viên, nhân viên hành chính trong khoa tại Đại Học
Brigham Young nơi tôi đã công tác và hoàn thành công trình nghiên cứu. Tôi cũng
mắc nợ rất nhiều cộng sự cũ của tôi tại FBI, những người cùng với tôi nghiên
cứu triết học cộng sản, lật đổ cộng sản và gián điệp cộng sản trong suốt 16 năm.

Các hình họa tiết minh hoạ ấn tượng hướng đến từng chương trong suốt cuốn sách này
đến từ nghệ sĩ nổi tiếng người Mỹ, Arnold Friberg. Họ sử dụng khả năng tuyệt vời
của mình thể hiện những ý tưởng phức tạp trở thành biểu tượng hình ảnh đơn giản, mạnh mẽ.
Bộ sưu tập tuyệt vời của ông về bức tranh Kinh Thánh "`Mười điều răn`" làm
cho nhà sản xuất Cecil B. DeMille đã được hoan nghênh rộng rãi trong chuyến lưu
diễn triển lãm toàn cầu. Tôi rất tự hào khi những trang bản thảo nghiên cứu của tôi
đã được nâng tầm giá trị lên một bậc từ bàn tay đầy tài năng của một người bạn tuyệt
vời như vậy.

Chịu trách nhiệm cho chiếc áo khoác nổi bật và thiết kế ấn tượng của cuốn sách là
một cộng sự khác thân thiết Keith Eddington.
Velora Gough Stuart và Louise Godfrey đã giúp tôi hoàn thành đánh máy bản
thảo, các dữ liệu nghiên cứu cho dự án - một công việc có phần tẻ nhạt và nhàm chán.

Phần lớn công sức đóng góp cho việc hoàn thành cuối cùng đến từ vợ tôi,
người quản lý tuyệt vời công việc của tám đứa con trong khi cha chúng tập trung
nghiên cứu viết lách.
Tôi rất biết ơn tất cả những người đã đóng góp thời gian, kỹ năng và động viên tôi
để mang công việc đi đến thành quả cuối cùng.

*W. Cleon Skousen*
_Salt Lake City_
Utah, ngày 1 tháng 11 năm 1958
