=== Kế hoạch hành động của Cộng sản

Khi phân tích nền văn minh hiện đại, Marx và Engels đã đưa ra kết luận rằng xã
hội tư bản đang nhanh chóng đạt đến cực điểm chắc chắn xảy ra cách mạng. Họ lý
luận như sau: Sau khi phá bỏ được phong kiến, xã hội tư bản đã thế chỗ. Đầu tiên
thì xã hội tư bản bao gồm thành phần cơ bản sở hữu đất đai hay cửa hàng riêng
của họ. Họ được phép thu lợi nhuận kinh tế từ những gì họ làm ra. Sau đó cuộc
cách mạng công nghiệp diễn ra, những cửa hàng tư nhân này bị thay thế bởi các
nhà máy, công xưởng sản xuất. Sản phẩm tạo ra không còn là thuộc sở hữu của những
cửa hàng tư nhân nữa, mà thu về nhà máy nơi tập hợp toàn bộ năng lực của mỗi cá
nhân lại để sản xuất ra hàng hoá.
Engels nói, sản xuất đã trở thành sản phẩm xã hội, không còn là sản phẩm tư nhân
nữa, nhà máy đã trở thành một tổ chức xã hội do đó sẽ thật sai lầm nếu những cá
thể tư nhân tiếp tục sở hữu nhà máy công xưởng. Sẽ không có bất kì cá thể tư nhân
nào nên được hưởng lợi nhuận từ những sản phẩm mà đòi hỏi tất cả mọi người cùng
sản xuất.

Những nhà phê bình chất vấn: "Vậy những người công nhân được trả lương được hiểu
thế nào, họ cũng được chia sẻ lợi nhuận đấy chứ?"

Marx và Engels không tin rằng tiền lương là sự đền bù thích hợp cho lao động trừ
khi các công nhân nhận được tất cả những gì thu được từ lợi nhuận bán hàng. Bàn
tay những người công nhân lao động làm ra tất cả hàng hoá nên họ phải nhận được
tất cả những giá trị mà hàng hoá đó đem lại. Quản lý, vận hành nhà máy chỉ là
loại "`công việc bàn giấy tự nhiên`" và trong tương lai gần, tầng lớp lao động nên
đứng dậy chiếm lấy nhà máy công xưởng (phương tiện xản suất), tự vận hành theo
cách của mình.

"`Vậy thì những khoản đầu tư của tư bản không cho phép họ thu chút lợi nhuận gì sao?
Nếu không có sự rủi ro mạo hiểm của họ thì sẽ không hình thành nhà máy hay công
xưởng, có phải vậy không?`"

Marx và Engels đáp lại chất vấn này, tất cả sự giàu có được tạo ra bởi công nhân
lao động. Tư bản chẳng tạo ra gì hết. Họ tin lý do tích luỹ sự giàu có của tư bản
là bởi vì tư bản đã tước đi trái ngọt thành quả lao động từ những người công nhân lao
động, dưới những hình thức như: lãi suất, cho thuê hay lợi nhuận. Những "`giá trị
thặng dư`" của công nhân lao động bị tư bản lấy đi trong quá khứ nên bị tịch thu lại
trong hiện tại.

Bây giờ thì Marx và Engels dám dự đoán xu hướng sự phát triển cuối cùng trong nền
văn minh tư bản hiện đại. Họ nói, cũng giống như những cửa hàng tư nhân bị xoá
sổ bởi các nhà máy công xuởng, các mô hình nhà máy nhỏ sẽ bị tiếp quản, sát
nhập bởi các mô hình lớn hơn. Sự độc quyền tư bản sẽ tiếp tục cho tới khi được
tập trung hoá trong tay một số ít người, trong khi đó số lượng công nhân bị bóc lột
sẽ tăng theo tỷ lệ. Một số người ngày càng trở nên giàu có hơn, còn tầng lớp bị
bóc lột trở nên ngày càng nghèo đi. Họ dự đoán những người được gọi là tầng lớp
trung lưu, sở hữu cửa hàng, kinh doanh nhỏ sẽ bị bóp nghẹt trong nền kinh tế vì
không thể cạnh tranh nổi với những mô hình kinh doanh cực lớn được sát nhập lại.
Chính phủ sẽ là công cụ quyền lực, những ngân hàng lớn và chủ sở hữu công nghiệp
sẽ được dùng để bảo vệ sự giàu có bệnh hoạn, đàn áp quần chúng bị bóc lột nổi
dậy.

Nói một cách khác, tất cả các tầng lớp trong xã hội bị ép buộc vào cuộc đối đầu
giữa hai giai cấp phản kháng thù địch: giai cấp bóc lột tư bản, sở hữu tài sản
và giai cấp bị bóc lột không tài sản - những người công nhân lao động.

Tiến bộ về công nghệ trong lĩnh vực công nghiệp tư bản sẽ chắc chắn làm nổ ra
cuộc cách mạng giữa hai giai cấp - Marx và Engels dự đoán tiếp.
Sự phát minh ra nhiều thứ máy móc hiện đại, hiệu quả sẽ lấy đi công việc của nhiều
công nhân lao động, khiến họ thất nghiệp, gia đình chết đói hoặc chỉ ở ngưỡng
sống sót. Khi ngưỡng tới hạn bị vượt qua, sự căm ghét, thù hận và phản kháng thù
địch sẽ thúc đẩy những con người công nhân lao động tổ chức đơn vị quân đội tiêu
diệt kẻ thống trị trong bạo lực, tịch thu tài sản cả nhân, phương tiện sản xuất
và vận hành theo cách của họ.

Đến đây là điểm mà những người Cộng sản và những người theo Xã hội chủ nghĩa
(Socialists) rẽ theo hướng khác nhau. Những người theo xã hội chủ nghĩa ngay từ
ban đầu họ duy trì quan điểm rằng kiểm soát tập trung đất đai và công nghiệp có
thể đạt được thông qua luật pháp hoà bình. Marx bác bỏ ngay giấc mơ viển vông
này. Tuy nhiên thì Marx cũng nhanh chóng nhìn thấy được một số lợi thế khi thúc
đẩy luật pháp tập trung hoá quyền lực kinh tế trong chính chủ tập trung. Marx
không coi đó như là "`chiến thắng của những người theo chủ nghĩa xã hội`", mà chỉ
coi đó không khác gì hơn liệu pháp tâm lý làm giảm nhẹ cuộc cách mạng đang đến.

Marx đặc biệt nhấn mạnh rằng để thành công cuộc cách mạng này phải hoàn toàn tàn
nhẫn, không khoan nhượng.
Nó không phải là một "`cải cách`" bởi vì cải cách luôn luôn kết thúc bằng cách
"`thay thế một nhóm người bóc lột bằng nhóm người khác`" và do đó các nhà cải cách
cảm  thấy "`không cần phải tiêu diệt bộ máy nhà nước cũ, trong khi cuộc cách mạng
vô sản loại bỏ tất cả nhóm người bóc lột ra khỏi quyền lực và đặt quyền vào tay
lãnh đạo của những người đói khổ, bị bóc lột... do đó phá hủy bộ máy nhà nước cũ
và thay thế nó bằng bộ máy mới là không thể tránh khỏi.`"
footnote:[Quoted from Problems of Leninism, by Joseph Stalin, pp. 16-17]

Marx tiếp tục biện minh cho việc sử dụng bạo lực để mang lại một xã hội mới, bởi
vì Marx cảm thấy nếu để cho các nguyên tắc đạo đức song hành, cuộc cách mạng sẽ
bị phá bỏ. Marx chỉ ra nguyên nhân thất bại trong cuộc Cách mạng Xã hội chủ nghĩa
suốt năm 1871: "`Hai lỗi lầm đã cướp đi chiến thắng ngọt ngào. Những người vô sản
đã dừng lại giữa đường, thay vì tiếp tục tước đoạt những kẻ chiếm đoạt thì họ
lại mang theo giấc mơ thiết lập nên công lý tối thượng trên toàn đất nước...Lỗi
thứ hai là sự ảo tưởng không cần thiết của những người vô sản: _thay vì huỷ diệt
kẻ thù thì họ lại cố gắng hết sức cảm hoá kẻ thù trên cơ sở ảnh hưởng những giá
trị đạo đức._`" footnote:[Karl Marx, The Civil War In France, p. 80.]

Marx cố gắng xoa dịu cơn cuồng phong bạo lực trong học thuyết của mình khi đưa
ra phát biểu rằng Marx sẽ hoàn toàn hài lòng nếu như mô hình tư bản có thể tự
chuyển đổi sang mô hình xã hội Cộng sản bằng cách thức hoà bình; tuy nhiên, Marx
chỉ ra điều này là khả thi chỉ khi những nhà tư bản tự nguyện đầu hàng, dâng toàn
bộ tài sản cho đại diện của công nhân lao động mà không xảy ra vũ lực. Một cách
logic, Marx kết luận việc này khó có khả năng xảy ra, do đó bạo lực cách mạng là
không thể tránh khỏi.

Marx và Engels cũng bị thuyết phục rằng cuộc cách mạng phải được diễn ra trên
phạm vi quốc tế. Họ biết tất cả các quốc gia sẽ không đồng loạt sẵn sàng tại cùng
một thời điểm, nhưng các cây viết Marxist nhấn mạnh: "`... _chủ nghĩa xã hội không
thể thành công hoàn toàn tại một quốc gia nếu như không có chiến thắng cách mạng
của tất cả quốc gia khác_.`"
footnote:[Program of the Communist International, pp. 34-35]
