=== Chế độ Độc tài Vô sản

Kể từ khi họ tin rằng một cuộc cách mạng là không thể tránh khỏi, câu hỏi tiếp
theo mà Marx và Engels đặt ra: có nên đợi đến khi cách mạng đi vào các sự kiện
bình thường hay nên thực hiện các bước để thúc đẩy cuộc cách mạng và đẩy nhanh sự
tiến hóa của xã hội tiến lên chủ nghĩa cộng sản?
Marx và Engels quyết định nhiệm vụ của họ phải cho thấy cuộc cách mạng đang được
gây dựng, ủng hộ mạnh mẽ. Tại sao kéo dài sự chịu đựng? Xã hội hiện tại đã bị
huỷ hoại. Dưới ánh sáng dẫn đường của những nguyên lý Marx - Engels, có lẽ hàng chục
thế hệ bị bóc lột và bất công có thể được cứu thoát bằng cuộc chạy đua mà ở đó
toàn bộ các giai đoạn tiến hoá xã hội được dồn nén vào trong một thế hệ bạo lực
điều chỉnh lại.

Họ tin việc này có thể được hoàn thành xong trong ba bước:

Thứ nhất:: Quét sạch toàn bộ trật tự cũ. "`Có một cách đơn giản hoá, rút ngắn,
tập trung cho cái chết đau đớn của chế độ xã hội cũ, kể cả phải tắm máu để ra đời
một thế giới mới - đó là _Khủng bố Cách Mạng_.`"
footnote:[Quoted from the Neue Rheinische Zeitung, by J.E. LeRossignol in From Marx To Stalin, p. 231.]

Thứ hai:: Đại diện tầng lớp lao động sau đó thiết lập nên chế độ _Độc tài Vô sản_.
Joseph Stalin miêu tả những việc cần phải hoàn thành trong giai đoạn thiết lập
độc tài:
. Đàn áp hoàn toàn giai cấp tư sản cũ.
. Tạo ra lực lượng quân đội quốc phòng hùng mạnh, dùng làm bàn đạp để đoàn kết
chặt chẽ lại toàn bộ nhưng người vô sản khắp mọi nơi, để phát triển, chiến thắng
cho cách mạng trên tất cả các quốc gia.
. Củng cố sự thống nhất quần chúng để ủng hộ chế độ Độc tài.
. Loại bỏ tư hữu, thiết lập chủ nghĩa xã hội toàn thế giới, và chuẩn bị tất cả
nhân loại cuối cùng chấp nhận chế độ Cộng sản toàn trị.
footnote:[Joseph Stalin, Problems of Leninism, pp. 26-27]

Thứ ba:: Bước cuối cùng là giai đoạn chuyển giao từ xã hội chủ nghĩa lên Cộng sản
toàn trị. Chủ nghĩa xã hội được đặc trưng bởi sở hữu nhà nước về đất đai và các
phương tiện sản xuất. Marx và Engels tin rằng ngay sau khi ý thức giai cấp biến
mất, sẽ không còn bất kì chống đối nào phải vượt qua, nhà nước sẽ dần dần tàn lụi, và
tài sản "`chung`" sẽ tự động thuộc về nhân loại.
Sau này Lenin giải thích làm thế nào chế độ Độc tài Vô sản mở đường cho giai đoạn
cuối này.
Lenin nói chế độ Độc tài là _một tổ chức tạo ra cho việc sử dụng bạo lực một cách hệ
thống, được vận hành bởi duy nhất một tầng lớp chống lại số còn lại, hoặc vận hành bởi
một nhóm người chống lại tất cả...Nhưng để phấn đấu lên Xã hội chủ nghĩa, chúng ta
tin rằng nó sẽ phải phát triển thành chế độ Cộng sản, và bên cạnh đó, sẽ biến mất nhu cầu
cần đến vũ lực, cưỡng chế giữa người với người, hay giữa các bộ phận xã hội với nhau,
bởi vì lúc đó con người sẽ phát triển, quen với việc tuân theo những điều
kiện cơ bản của sự tồn tại trong xã hội, không cần đến vũ lực và cưỡng chế_.
footnote:[V.I. Lenin, Imperialism: The State and Revolution, p. 187]

Thậm chí trong giai đoạn sau của chủ nghĩa xã hội, Lenin còn hình
dung ra một thế giới không cần đến toà án, luật sư, thẩm phán, giới chủ,
người đại diện được lựa chọn, hay thậm chí không còn cảnh sát. Tất cả sẽ bị quét
sạch, cuốn đi vào thế giới âm u quên lãng, vô dụng, đặc trưng cho trật tự cũ kỹ
của chủ nghĩa tư bản suy đồi.
Lenin nói sự đồng nhất tự phát của quần chúng được xã hội hoá sẽ làm tất cả cơ quan bộ
máy của hệ thống tư bản cũ trở nên vô dụng. Lenin cũng cảm thấy được xã hội mới
sẽ làm biến đổi bản chất con người khi mà những phản kháng, chống đối trong xã hội
trở thành "`ngoại lệ hiếm hoi, có thể kèm theo trừng phạt nhanh chóng nhưng rất nặng nề
(những công nhân vũ trang - con người thực tế của sự sống, không phải loại trí thức
đa cảm, sẽ không cho phép bất cứ ai châm trọc nhạo báng họ),
và việc cần thiết tuân thủ những quy tắc cơ bản của đời sống xã hội thường ngày
sẽ sớm trở thành thói quen.
Cánh cửa sau đó sẽ mở ra cho giai đoạn chuyển giao lên chủ nghĩa Cộng sản từ thấp
nhất tiến lên giai đoạn cao hơn - Cộng sản toàn trị (full Communism).`"
footnote:[V.I. Lenin, Imperialism: The State and Revolution, p. 759]
