=== Tiến bộ nhân loại trong quan hệ đấu tranh giai cấp

Marx và Engels tự trả lời câu hỏi riêng của mình bằng cách đưa ra khẳng định rằng,
thời kì đầu sớm nhất, phương thức sản xuất và phương tiện phân phối luôn luôn sinh
ra hai tầng lớp con người cơ bản: những người sở hữu phương tiện sản xuất làm
chủ, là người khai thác, bóc lột và những người không sở hữu gì cả, phải bán sức
lao động để tồn tại. Yếu tố xung đột giữa hai nhóm này được Marx và Engels xác
định giống như lực cơ bản trong lịch sử, thúc đẩy tiến hoá xã hội với kết quả,
thành tựu ngày càng tăng trưởng.

"`Lịch sử tồn tại xã hội cho đến nay là lịch sử đấu tranh giai cấp: con người tự
do và nô lệ,  quý tộc và tiện dân, địa chủ và nô bộc, chủ nghiệp đoàn và người
làm thuê, hay ngắn gọn hơn là người áp bức và bị áp bức. Họ đứng bên hai chiến
tuyến đối lập nhau, chiến đấu không ngừng nghỉ, mỗi lần kết thúc hoặc là đem lại
sự tái tạo mới mang tính cách mạng cho một xã hội ở phạm vi lớn, hoặc là sự huỷ
hoại chung, phổ biến của tranh đấu giai cấp.`"
 footnote:[Marx-Engels, Communist Manifesto, p. 12]

Ở đây một lần nữa Marx và Engel đang áp dụng nguyên lý biện chứng. Tất cả những
xã hội trong quá khứ là kết hợp của lực lượng đối lập hoặc giai cấp đối lập -
bóc lột và bị bóc lột. Sự đối đầu dữ dội giữa các giai cấp, lực lượng đối lập này
luôn luôn tạo ra lực vận động, thúc đẩy xã hội tiến lên một bước phát triển mới.
Họ chú thích thêm, quá trình chuyển giao thường kèm theo giải phóng cách mạng và bạo lực.

Vậy thì trên con đường của nhân loại cứ nhất thiết phải luôn đi theo vòng xoay
vô tận của sự xung đột, đối đầu giữa hai giai cấp đối lập trong xã hội hay không?
Cứ nhất thiết phải luôn có cuộc cách mạng tạo ra trật tự mới, để rồi đến lượt
mình chính trật tự mới tạo ra lại bị phá huỷ bởi cuộc cách mạng mới, tạo ra trật tự
mới khác? Marx và Engels hình dung ra một ngày con người hợp nhất lại thay vì đối
đầu, hoà bình thay vì chiến tranh. Tất nhiên hy vọng này vi phạm rõ ràng lý thuyết
biện chứng của chính họ nói rằng chẳng có gì trong tự nhiên có thể ở trạng thái
nghỉ ngơi - vạn vật là đồng nhất, kết hợp của các lực đối ngẫu.

Thêm vào đó, Marx và Engels lý luận rằng bởi vì họ đã khám phá ra quy luật không
thể lay chuyển của lịch sử, với một cỗ máy tự cải tiến đấu tranh giai cấp,
họ sẽ sử dụng cuộc đấu tranh giai cấp khủng khiếp cuối cùng với mục đích loại trừ
vĩnh viễn tất cả những thứ gây ra các xung đột trong quá khứ của xã hội.
Vậy thì cái gì là yếu tố kinh khủng gây ra trong tất cả xã hội trước đây sự ích
kỷ, lòng đố kị, đấu tranh giai cấp và chiến tranh? Marx và Engels cùng đồng ý
tất cả những thứ đó có thể truy xét về cùng một nguồn gốc, đó là _quyền tư hữu_.
Nếu họ dùng một cuộc nổi dậy cách mạng giai cấp cuối cùng để bãi bỏ quyền tư hữu,
thì điều đó có nghĩa là đấu tranh giai cấp sẽ trở nên không cần thiết nữa, chẳng
còn gì để chiến đấu nữa.
