=== Diễn giải của Cộng sản về lịch sử  

Ngày nay rất ít người có cơ hội được ngồi nói chuyện, lắng nghe quan điểm của
những người Cộng sản chuyên nghiệp. Các bạn sinh viên nếu có cơ hội được gặp mặt thì sẽ
ấn tượng mạnh ngay lập tức, người Cộng sản dành sự tôn kính cho những gì cha ông
đã làm được trong quá khứ. Đó là bởi vì Marx cùng Engels nghĩ rằng những nghiên
cứu của họ trong quá khứ đã dẫn đến khám phá ra "quy luật không thể lay chuyển"
giống như sợi chỉ đỏ xuyên suốt chiều dài lịch sử. Họ tiếp tục tin rằng có thể
dự đoán một cách chắc chắn và tích cực hình mẫu tiến bộ của nhân loại nếu bám theo
sợi dây chỉ đỏ dẫn đường này.

Vậy thì Marx và Engels đã phát hiện ra những gì trong suốt quá trình nghiên cứu
về lịch sử của  mình? Đầu tiên họ khẳng định tự bảo vệ là bản năng tối cao nhất
trong mỗi con người, do đó tất cả hình mẫu hành vi biểu hiện của con người được
chi phối bởi khát vọng dành giật từ tự nhiên nhu yếu phẩm cần thiết cho sự sống
của loài người. Đây là một quá trình biện chứng - con người đấu với thiên nhiên,
và đã đi đến một kết luận vĩ đại: tất cả phát triển lịch sử là kết quả của
"Kinh tế Định hướng" - nỗ lực của con người để sống sót. Họ nói tất cả những gì
con người làm, từ việc tổ chức nên chính phủ, thiết lập luật pháp, ủng hộ quy
chuẩn đạo đức cụ thể hay việc thực hành tôn giáo, thì đều chỉ là kết quả của
sự mong muốn, khát vọng bảo vệ phương thức sản xuất đang được áp dụng  bảo đảm
an toàn thiết yếu cho sự sống.
Họ cũng tin rằng, nếu như có lực lượng cách mạng nào đó thay đổi phương thức sản
xuất thì ngay lập tức giai cấp thống trị sẽ bắt đầu tạo ra một xã hội kiểu mới,
được thiết kế để bảo vệ trật tự kinh tế mới.

"`Có cần thiết phải học sâu có bằng cấp để hiểu được rằng ý tưởng, cách nhìn và quan điểm,
hay nhận thức của con người sẽ thay đổi khi các điều kiện vật chất tồn tại thay đổi?
Cái ý tưởng lịch sử này chứng minh điều gì khác hơn khi nói rằng: sự thay đổi
chất trong sản xuất kéo theo sự thay đổi về nguyên liệu sản xuất.`"
footnote:[Marx-Engels, Communist Manifesto, p. 39]

Để có thể nhìn nhận được giá trị của họ ở điểm này chúng ta cần hiểu quan điểm
cơ học của Marx và Engels về hoạt động ý thức của con người. Họ phát biểu rằng,
sau khi não bộ nhận được thông tin gây ấn tượng từ bên ngoài, nó sẽ tự động thúc giục
cá nhân hành động (đây là Lý thuyết Hành động). Họ không tin rằng kiến thức có thể
có được mà không cần thúc đẩy chủ thể phải làm gì cả. Lấy ví dụ, khi con người
trở nên nhận thức được rằng chế độ nô lệ là cái cách cần thiết để sản xuất vụ mùa,
xây dựng nhà cửa và thoả mãn rất nhiều thứ khác, thì nhận thức này thúc đẩy giai
cấp thống trị tạo ra một hình thái xã hội bảo vệ cho những người chủ sở hữu nô lệ.
Và trong thời hiện đại khi không còn nô lệ nữa, Marx và Engels tin rằng những nhà
tư sản - tầng lớp sở hữu nhiều tài sản đã làm những việc giống hệt như vậy theo
bản năng, tạo ra một xã hội để bảo vệ các lợi ích tư bản mà thôi. Họ đã nói với
những người tư sản trong tuyên ngôn Cộng sản:
_"Ý tưởng của các người là thúc đẩy lớn mạnh điều kiện sản xuất tư sản và sở hữu
tư sản, cũng giống như phát triển hệ thống luật lệ của các người. Ý tưởng
này cũng chính là nguyện vọng của giai cấp tư sản, đưa tất cả vào luật pháp
cái nguyện vọng mà những đặc tính, hướng đi của nó được quyết định bởi điều kiện
kinh tế cho sự tồn vong của chính giai cấp tư sản."_
footnote:[Marx-Engels, Communist Manifesto, p. 35]

Từ điểm này có thể thấy Marx và Engels không tin con người có thể tuỳ ý chọn lựa
bất kì một trong các hình thái xã hội khác nhau nào, mà tin rằng chỉ những người
cổ suý, thúc đẩy phương thức sản xuất chiếm ưu thế mới được lựa chọn. Bản năng rất
tự nhiên được tô điểm giá trị vật chất yêu cầu nhóm người này suy nghĩ và hành động
như vậy. _"Con người có được lựa chọn hình thái này hay hình thái kia của xã hội
không? Chắc chắn là không."_ footnote:[Karl Marx, Poverty of Philosophy, p. 152]
Theo Marx thì  những gì chúng ta gọi là "`tự do ý chí`" được diễn giải không hơn
không kém chính là sự nhận biết được những lực lượng ép buộc, thúc đẩy một cá nhân
phải hành động và trong quá trình hành động, anh ta không được tự do thay đổi đường
hướng lựa chọn theo bản năng tự nhiên vạch sẵn trong con người anh ta.

"`Chủ nghĩa Cộng sản không có khái niệm về sự tự do giống như một khả năng để
lựa chọn đúng sai, phải trái, mà sự tự do là khả năng phát huy toàn bộ năng
lượng của con người khi họ đã chọn ngã rẽ.`"
footnote:[ N. Berdyaev, Vital Realities, p. 175.]

Một cách diễn giải khác, ý thức của con người tiếp nhận kiến thức từ hoàn cảnh
kinh tế đang tồn tại, và "chọn lựa" rẽ theo hướng đi cần thiết để bảo vệ phương
thức sản xuất hiện hành. Sau đó con người sẽ tự do, nhưng bị gói gọn trong ý nghĩa
rằng họ sẽ phải tiêu hao phần lớn sức lực, năng lượng để xây dựng một chính phủ
thượng tầng, luật pháp, đạo đức và tôn giáo nhằm duy trì hoàn cảnh kinh tế cơ bản.
Nền tảng của tất cả các hoạt động xã hội đặt trên khái niệm "Kinh tế Định hướng".
Phương thức sản xuất trong cuộc sống thực dụng quyết định đặc điểm chung xã hội,
chính trị và đời sống tinh thần.
footnote:[Karl Marx, Contribution to Critique of Political Economy, p. 11]

Marx và Engels nghĩ rằng họ đã khám phá ra thứ gì đó quan trọng sống còn cho lợi
ích nhân loại hơn đơn thuần chỉ là giải thích triết học lịch sử. Thực tế họ tin
nền _Kinh tế Định hướng_ là lực lượng sáng tạo cơ bản của tiến bộ loài người.
Với phát hiện quan trọng này họ cảm thấy nếu như ép buộc được nhân loại chịu ảnh
hưởng của nền kinh tế sản xuất hoàn thiện cao, thì tự động sẽ tạo ra một xã hội
hoàn thiện cao và đến lượt xã hội này sẽ tự động tạo ra loại chủng người cao cấp
hơn. Nói cách khác, họ muốn đi ngược lại với cách tiếp cận của Do Thái Giáo và Thiên
Chúa Giáo: nỗ lực cải tiến nhân loại để cả tiến xã hội. Ở điểm này họ lại tái
khẳng định một lần nữa phán quyết của họ: con người chỉ là sản phẩm của xã hội, không
phải là người tạo ra xã hội.
"`Nguyên nhân cuối cùng được tìm kiếm của sự thay đổi xã hội, cách mạng chính trị là
ở nền kinh tế của từng thời đại cụ thể, chứ không phải ở trong đầu não con người,
cũng không phải sự sáng suốt của con người nhìn nhận về chân lý bất diệt và công lý.`"
footnote:[Friedrich Engels, Socialism -- Utopian and Scientific, p. 54]

Marx và Engels do đó đã ủng hộ công khai thay đổi trong cấu trúc kinh tế, cách hợp
lý duy nhất để cải tiến xã hội và tinh chỉnh lại trí tuệ của nhân loại.
Nhưng làm cách nào để hệ thống sản xuất, phân phối mới được cái tiến có thể đến
với con người? Những phương cách lịch sử gì mà nền _Kinh tế Định hướng_ vô thức đi
theo đưa nhân loại đến trạng thái tiến bộ hiện nay?
