=== Cộng sản giải quyết vấn đề thế giới

Bây giờ chúng ta đến phần mà nhiều người sẽ thấy quen thuộc hơn. Ít nhất nhiều
người nghe về kế hoạch hành động của Cộng sản nhiều hơn là nghe về triết học
Cộng sản mà chúng ta đi qua ở phần trước. Dưới đây là những câu hỏi liên quan đến
giải pháp của những người Marxist cho các vấn đề quốc tế mà các bạn sinh viên nghiên
cứu về chủ nghĩa Cộng sản cần phải trả lời được:

****

. Tại sao Marx và Engels nghĩ rằng họ đã khám phá ra quy luật không thể lay chuyển
trong lịch sử, giúp dự đoán con đường đi cho sự phát triển nhân loại tương lai?

. Nền "Kinh tế Định hướng - Economic Determinism" là gì?
"`Lý thuyết Hành động - Activist Theory`" là gì?
Theo Marx và Engels có tồn tại cái gọi là "`tự do ý chí - free will`"?
Con người có thể lựa chọn hình thức xã hội mà mình muốn hay chỉ là nạn nhân của
_lực lượng vật chất_ xung quanh?

. Marx và Engels giải thích như thế nào về sự tiến bộ loài người giống như một
sản phẩm của đấu tranh giai cấp?

. Lý thuyết Cộng sản về tư hữu là gì?

. Tại sao tư hữu được coi là nguồn gốc của mọi sự xấu xa?

. Marx và Engels giải thích như thế nào về nguồn gốc của Nhà nước? Tại sao họ nói
nó là "`bất tự nhiên`"?

. Họ giải thích thế nào về nguồn gốc của Tôn giáo, đạo đức thánh thiện và triết
lý của luật pháp?

. Những việc được cho là cần phải hoàn thành dưới chế độ Cộng sản "``Độc tài Vô sản`"
là gì?

. Tại sao Cộng sản nói rằng "`xã hội chủ nghĩa`" chỉ là giai đoạn tạm thời trong
quá trình phát triển nhân loại?

. Họ đề xuất phát triển một nền văn minh không giai cấp, xã hội không nhà nước
như thế nào?

****
