=== Nguồn gốc và ý nghĩa kinh tế của tôn giáo

Marx và Engels tin rằng sự khai thác tôn giáo là một thứ xấu xa ghê tởm mọc ra từ
_quyền tư hữu_. Tất nhiên họ cũng nhận ra gốc rễ tôn giáo có thể đã có từ lâu
trước khi hình thành sự tư hữu và họ cho rằng vì tôn giáo không phải là nguồn gốc
của thần thánh, nên chắc chắn nó được phải phát triển lên từ những lo sợ, hoảng
loạn, hoang dã của loài người thời kì ban đầu, trong nỗ lực cố gắng lý giải các
lực thiên nhiên hay trải nghiệm tâm lý ví dụ như những giấc mơ.
Khi sự tư hữu nổi lên giống như nền tảng của xã hội thì họ tin rằng tôn giáo
đã được nắm lấy, thay thế cho cỗ máy, công cụ đàn áp nhằm dập tắt sự nổi loạn của
giai cấp bị khai thác, bị bóc lột.

Theo Marx, chính tầng lớp tư sản đã muốn những người công nhân, lao động làm việc
cho họ được dạy dỗ sự khiêm nhường, nhẫn nhịn kham khổ trường kì, chịu đựng sự sai
trái đổ lên đầu họ với hy vọng kiếp sau sẽ được hoàn trả.
Marx nói tôn giáo được tạo ra để làm thứ thuốc phiện phục vụ cho tầng lớp bị áp
bức. Công nhân lao động được yêu cầu "không phán xét", hãy làm tròn trách
nhiệm của mình, phục tùng nghe lời chủ.
"`Tôn giáo là tiếng ai oán thở dài của những sinh vật bị áp bức, là cảm xúc của
một thế giới không có trái tim, giống như tinh thần trong trạng thái vô hồn.
Tôn giáo là liều thuốc phiện của nhân loại.`"
footnote:[Selected Essays of Marx, p. 16]

Những việc này lý giải sự xuất hiện chiến lược bài trừ tôn giáo mạnh mẽ trong
chương trình hành động của Cộng sản:

"`Một trong những nhiệm vụ quan trọng hàng đầu của cuộc Cách mạng Văn hoá tác động,
ảnh hưởng tới quần chúng rộng lớn đó là chiến đấu với tôn giáo - liều thuốc phiện
của loài người -  một cách hệ thống, không lay chuyển`".
footnote:[Program of the Communist International, International Publishers, New York, 1936, p. 54]

"`Chẳng có gì nghi ngờ một thực tế rằng nhà nước mới USSR được lãnh đạo bởi Đảng
Cộng Sản với một chương trình thấm nhuần tinh thần quân đội vô thần`".
footnote:[E. Yaroslavsky, Religion in the USSR, p. 59]

"`Chúng ta đã đàn áp những giáo sĩ phản động chưa? Có, chúng tôi đã làm. Những
đáng tiếc là vẫn chưa hoàn toàn thanh trừng hết.`"
footnote:[Joseph Stalin, Leninism, Vol. 1, p. 387]
