=== Nguồn gốc và ý nghĩa kinh tế của đạo đức

Đến điểm này Marx và Engels cảm thấy đã thiết lập được lý giải tại sao sự xấu xa
của tư hữu phải chịu trách nhiệm cho nguồn gốc phát sinh tầng lớp phản kháng thù
địch, hình thành Nhà nước, khai thác, lợi dụng tôn giáo. Tiếp theo họ sử dụng
cách lý giải tương tự để tiếp cận vấn đề nguồn gốc và ý nghĩa kinh tế của đạo
đức. Engels và Marx phủ nhận tất cả những giá trị cơ bản cấu thành nên chuẩn mực
đạo đức "đúng sai" được hình thành từ giáo dục, răn dạy của Do Thái Giáo và Thiên
Chúa Giáo. Lenin tóm tắt lại những ý tưởng Cộng sản khi nói:

"Chúng ta không thừa nhận nguyên tắc đạo lý, chuẩn mực đạo đức theo nghĩa như thế nào?
Theo cái cách mà những người tư sản thuyết giảng, đạo đức được hình thành từ những
điều răn của Chúa. Tất nhiên chúng ta không tin vào Chúa, chúng ta biết rất rõ các giáo sĩ,
địa chủ, và những người tư sản tuyên bố họ nói thay lời của Chúa chỉ nhằm để bảo
vệ tài sản, lợi ích của họ, của những con người bóc lột. Chúng ta phủ nhận tất
cả những giá trị đạo đức mang đến từ cái gọi là đấng tối cao, siêu nhân hay không
phân biệt giai cấp, đó là sự lừa gạt, giả dối, trục trặc trong nhận thức của người
lao động và nông dân vì lợi ích của địa chủ, tư bản."
footnote:[V.I. Lenin, Religion, pp. 47-48.]

Những người Marxist tin rằng lời răn của Chúa "Người sẽ không ăn cắp - Thou Shalt
Not Steal" và "Ngươi sẽ không ham muốn - Thou Shalt Not Covet" là ví dụ điển hình
của tầng lớp cai trị cố gắng dùng nó để áp đặt, bắt ép quần chúng tôn trọng tài sản
có được nhờ bóc lột, từ bỏ ham muốn giàu có và tài sản của giới chủ.
Như Engels đã nói:

"Ngươi sẽ không ăn cắp - Cái luật đạo đức này là thứ luật lệ vĩnh cửu chăng?
Chắc chắn là không."
footnote:[V.I. Lenin, Religion, p. 47]

Họ gọi những thứ rao giảng đạo đức "`giai cấp`" này là chuẩn mực được thiết kế để bảo
vệ cho tầng lớp chiếm hữu tài sản.

Việc bác bỏ các giá trị chuẩn mực đạo đức Do Thái Giáo và Thiên Chúa Giáo, Engels
muốn cố gắng thể hiện chủ nghĩa Cộng sản đơn thuần chỉ là đang tiến lên một cấp
độ cao hơn, nơi nhu cầu xã hội sẽ là động lực thúc đẩy duy nhất cho hành vi, cư
xử của con người: "`Chúng ta nói rằng đạo đức của chúng ta là tất cả những gì phục
vụ cho lợi ích đấu tranh giai cấp vô sản`". Mặc dù cố gắng khéo léo che đậy sự
thật quan trọng ý tưởng đạo đức Cộng sản, nhưng cái kim trong bọc lâu ngày cũng
phải bị lòi ra:

"`Do đó, chúng ta phủ nhận, từ chối bất kì nỗ lực nào áp đặt đạo đức giáo điều lên chúng ta...`"
footnote:[Friedrich Engels, quoted in the Handbook of Marxism, p. 249]

Nói cách khác, chủ nghĩa Cộng sản cam kết gánh vác bắt đầu công việc thay thế đạo đức
Do Thái - Thiên Chúa giáo bằng một thứ mà ở đó đạo đức hoàn toàn vắng mặt không
tồn tại. Và đó chính xác là nhưng điều rút ra từ những lời dạy, rao giảng của
những nhà lãnh đạo Cộng sản, được thể hiện thành lời của một người Marxist-Mỹ
hiện đại:

"`Với người Cộng sản, kết quả cuối cùng biện minh cho hành động. Bất kể biện pháp
là gì, đúng luật, có đạo đức hay không cũng không ảnh hưởng, miễn là nó có hiệu
quả. Người Cộng sản biết rằng luật lệ hay kể cả những chuẩn mực đạo đức là do kẻ
thù loài người tạo ra...Kết quả là họ ta phớt lờ mọi thứ trong giới hạn họ có thể
làm, miễn nó phù hợp với mục đích của mình. Người Cộng sản đề xuất phát triển
một quyền lực vĩ đại, hơn hẳn những gì kẻ thù tư bản có, bất chấp bỏ qua, không
đếm xỉa đến những khái niệm của tư bản về tính hợp pháp, sự công bằng, quyền, v.v.`"
footnote:[William Z. Foster, Syndicalism, p. 9]

Đến đây Marx và Engels đã hoàn thành những mục đích ban đầu nghiên cứu chuyên sâu
về lịch sử. Họ cảm thấy đã lý giải thành công nguồn gốc của rất nhiều sự hình thành
khác nhau trong xã hội bằng cách chỉ ra rằng mọi thứ đều là sản phẩm của nền
_Kinh tế Định hướng_, và tư hữu là nguồn gốc của sự bất mãn, xung đột, bất bình
đẳng và bất công của con người.
Công việc duy nhất còn lại bây giờ của những bậc thầy kiến trúc sư là làm thế nào
để áp dụng những kiến thức này vào "`kế hoạch hành động`", giải quyết vĩnh viễn
những căn bệnh xã hội, kinh tế, chính trị cho tất cả nhân loại.
