=== Quyền tư hữu

Tại sao Cộng sản tin tư hữu là nguồn gốc của tất cả xấu xa?

Engels đã viết ông ta tin rằng từ thời sơ khai, con người đã tuân theo nguyên
tắc sở hữu chung tất cả đồ vật ngoại trừ những thứ thuộc về cá nhân như quần áo,
vũ khí. Cuộc sống canh tác, trồng trọt và bày đàn giúp con người
tạo ra lương thực, vật dụng nhiều hơn mình cần cho bản thân, và từ đó họ trao
đổi những phần dư thừa đổi lấy những thứ khác mà họ thiếu. Engels nói những thứ
hàng hoá, vật dụng dùng để trao đổi được gắn với người
sở hữu chúng một cách tự nhiên, và từ đó khái niệm _tư hữu_ được ra đời.
footnote:[See Friedrich Engels, The Origin of the Family, Private Property and the State.]

Engels sau đó đưa ra nhận định những người sở hữu đất đai hoặc các phương tiện
sản xuất khác sẽ thu được phần lớn lợi nhuận từ nguồn lực kinh tế của cộng đồng,
và cuối cùng sẽ đặt họ vào vị trí có thể thuê người khác làm việc cho mình.
Họ sẽ có thể ra lệnh trả lương, quyết định giờ làm việc và điều kiện lao động cho người
làm thuê, đảm bảo sự tự do của chính họ và trạng thái xã hội trong khi khai thác,
bóc lột tầng lớp đói khổ.
Engels nói, ngoài những thứ tư hữu thì còn nở rộ tầng lớp phản kháng thù
địch, kéo theo bọn tuỳ tùng theo đóm ăn tàn, tham lam, ích kỉ, kiêu ngạo, chủ nghĩa
đế quốc và chiến tranh. Tư hữu cũng dẫn tới sự cần thiết tạo ra một _Nhà nước_.
