=== Nguồn gốc Nhà nước

Engels khẳng định khi tầng lớp vô sản bị bóc lột đến điểm nguy hiểm xảy ra
bạo động, thì tầng lớp thống trị tạo ra một cơ quan quyền lực để duy trì
"trật tự và luật lệ" - một hệ thống những luật lệ để bảo vệ tài sản cá nhân và lợi
thế của tầng lớp bóc lột. Đây chính là một trật tự mới: _Nhà nước_.

"`Nhà nước...đơn thuần là một sản phẩm của xã hội tại một giai đoạn xác định của
tiến hoá. Việc tạo ra bất kì loại chính phủ nào đều là sự thú nhận rằng xã hội này
đã trở nên vô vọng, bị chia rẽ, vướng vào những mâu thuẫn không thể hoà giải, không
còn khả năng đẩy lùi.`"
footnote:[Friedrich Engels, The Origin of the Family, Private Property]

Do vậy, Nhà nước được thiết kế để trì hoãn ngày phán xét. Chính phủ là "công cụ
quyền lực" - gắn vào xã hội một cách bất bình thường - được tạo ra từ yêu cầu
của tầng lớp bóc lột, với mục đích tạo áp lực liên tục nhằm bảo vệ tầng lớp cầm
quyền và tài sản nó sở hữu.
Marx và Engels lý luận nếu họ có thể loại bỏ được tư hữu thì sẽ không còn đấu
tranh giai cấp, và tiếp đó nhà nước sẽ không thực sự cần thiết nữa, sẽ bị lụi tàn
dần dần.
