=== Cộng sản toàn trị không giai cấp không nhà nước

Tất cả những người Marxist đều hy vọng mãnh liệt vào một xã hội mới, nơi sẽ tạo
ra sự biến đổi bản chất con người, một việc cần thiết trước khi chế độ Cộng
sản toàn trị trở thành hiện thực.
Mọi người phải quên đi cái thời kì mà thu nhập được đảm bảo chỉ đến từ giới chủ
sở hữu tài sản hay từ năng suất lao động. Nói một cách khác, tiền lương sẽ bị
bãi bỏ. Phải quên đi giai đoạn mà một số ít người nhận được phần thu nhập
rất lớn, trong khi số khác thì nhận được rất ít. Phải từ bỏ hy vọng rằng khác
biệt về năng suất hay chất lượng phục vụ sẽ mang lại khác biệt về bậc lương nhận
được. Phải quên đi sự khác biệt về trình độ, kĩ năng đào tạo, hay khả năng thể
chất và tinh thần. Mọi người phải chuyển hoá với ghi nhớ: nếu một người làm tốt
nhất những công việc phù hợp nhât với anh ta, thì anh ta cũng xứng đáng có được
thu nhập ngang bằng với những người khác mà không cần quan tâm đến khác biệt về
năng suất hay sản phẩm tạo ra.
Đây chính là những gì mà chủ nghĩa Cộng sản hứa hẹn:
_"Làm theo năng lực và hưởng thụ theo nhu cầu"_ . Mỗi cá nhân phải từ bỏ động
cơ lợi nhuận tiền bạc cũ kỹ đi, hãy trở thành con người với nhận thức hướng đến
xã hội, làm việc tối đa cho lợi ích chung của xã hội, và hãy vừa lòng với những
gì nhận được tuỳ theo nhu cầu, coi đó là phần thưởng cho đóng góp của mình.

Marx và Engels dự tính dưới hệ thống này, đầu ra của sản xuất sẽ cực kì lớn, đến
mức chúng có thể tự quản lý, vận hành không cần thị trường, tiền tệ và giá cả.
Hàng hoá sẽ được chất thành đống khắp mọi nơi trung tâm, tất cả mọi người lao
động được cho phép tự do lấy tuỳ theo nhu cầu.
Marx cùng Engels cảm thấy rằng chẳng có động lực đặc biệt gì để lấy nhiều hơn
những thứ cơ bản cần thiết cho nhu cầu sử dụng một lần, vì hàng hoá dư thừa quá
nhiều nên người lao động có thể bổ sung bất kì lúc nào muốn. Những dịch vụ cũng
giống như vậy được phân bổ, cung cấp tại những nơi tiện lợi, mọi người có thể
yêu cầu dịch vụ ngay khi họ cần.

Các cây viết Marxist giải thích: sống trong một hoàn cảnh thật dễ chịu như vậy
thì bộ máy chính phủ của Nhà nước sẽ không cần thiết nữa.

"`Chỉ có chủ nghĩa Cộng sản mới làm cho nhà nước trở nên tuyệt đối không cần thiết,
ở đó không ai bị áp bức, _không ai_ với nghĩa là một giai cấp, một hệ thống tranh
đấu của một bộ phận dân chúng. Chúng ta không phải là những nhà cải cách không
tưởng, tin vào một xã hội vận hành trên mức hoàn hảo, và ít nhất chúng ta không
chối bỏ khả năng tồn tại của một số bộ phận cá nhân thái quá cần bị đàn áp.
Nhưng ban đầu thì cũng chưa cần đến ngay cơ quan hay bộ máy đàn áp đặc biệt, những
con người tự vũ trang sẽ giải quyết việc này một cách đơn giản, sẵn sàng giống
như bất kì đám đông nào của nhóm người văn minh không cho phép phụ nữ bị xúc phạm.
Và thứ hai, chúng ta biết nguyên nhân xã hội cơ bản của sự thái quá, bất mãn...
đó là sự bóc lột quần chúng, ham muốn của chúng, sự nghèo đói của chúng. Loại bỏ
những nguyên nhân cốt lõi này sẽ khiến cho những sự việc thái quá hay bất mãn
chắc chắn sẽ bắt đầu tàn lụi dần đi. Chúng ta không biết nó sẽ diễn ra nhanh chóng
như thế nào, kế tiếp theo nó là gì, nhưng chúng ta biết nó sẽ bị héo tàn và kéo
nhà nước cũng sẽ héo tàn theo.`"
footnote:[E. Burns, Handbook of Marxism, p. 747]

Một điểm quan trọng nhận thấy là lý thuyết Cộng sản coi những người vô sản giống
như một nhánh duy nhất của nhân loại. Họ được giả định như một giống loài đặc biệt,
sẽ nở rộ trong cuộc sống kinh tế dễ chịu, hiệu quả nếu như có thể được giải phóng khỏi
chính phủ áp bức. Chính phủ thì được xem là không hơn gì công cụ của tầng lớp đàn
áp tư bản và do vậy chính phủ sẽ bị xoá sạch nếu như tầng lớp tư bản bị tiêu diệt.
Những người lãnh đạo Cộng sản luôn tự tin rằng khi vô sản lên chiếm quyền kiểm
soát họ sẽ không muốn đàn áp bất kì ai nữa, do đó nhu cầu thiết lập chính phủ
sẽ không tồn tại.

Một điểm khác cũng đáng chú ý, Lenin muốn vô sản là những "`con người vũ trang`".
Viễn cảnh này không làm Lenin sợ hãi gì hết. Lenin không giảm đi sự tự tin nói
những người vô sản sẽ không bao giờ lạm dụng quyền lực như những gì tư bản đã làm.
Hơn nữa, Lenin cho rằng người vô sản có khả năng nhận ra công lý tức thì như một
bản năng của họ. Không chỉ dùng vũ khí dập tắt những hành vi phi xã hội trong
cộng đồng bằng hành động tự phát nổ ra trên diện rộng, mà Lenin còn tin rằng họ,
những con người vô sản, sẽ chân thành ngăn chặn thói ích kỷ, có chiều hướng phản
xã hội trong chính bản thân họ.
Họ sẽ dần có "`thói quen`" sống trong mệnh lệnh chung của tập thể xã hội, lớn lên quen
với việc tuân theo những điều kiện xã hội sinh tồn không cần vũ lực hay cưỡng chế.

Lenin nói, với sự biến mất của bộ máy chính phủ, các hình mẫu Cộng sản không giai
cấp, xã hội không nhà nước được thiết lập trên toàn bộ thế giới, và cuối cùng thì
"`là lúc có thể nói về tự do`"
footnote:[E. Burns, Handbook of Marxism, p. 745]
