=== Kế hoạch cho một nền dân chủ tại Nga bị phá huỷ

Điều quan trọng nhất trong việc Nga Hoàng thoái vị chỉ đơn thuần là một thực tế
của lịch sử, và điều này chẳng có liên quan gì tới những người Bolshevik hay Cộng
sản gì cả. Cuộc cách mạng được khởi xướng bởi chính những người giống như thời kỳ
1905 đã nổi dậy chống lại Nga Hoàng. Họ đại diện cho tầng lớp tinh hoa nhất của
nước Nga thời đó, những nhà quý tộc giải phóng tự do, trí thức, doanh nhân,
hàng triệu nông dân nghèo cùng công nhân lao động. Những người lãnh đạo Bolshevik
không có vị trí nào quan trọng trong đó. Lenin đang lưu vong tại Thuỵ Sĩ, Trotsky
lưu vong ở Hoa Kỳ, còn Joseph Stalin thì bị tù đày lao động khổ sai tại Siberia.
Thật không may cho sự tuyên truyền sau này, những người Bolshevik sẽ không bao
giờ có thể kể công cho cuộc cách mạng tháng 3 năm 1917 dẫn tới sự sụp đổ của đế
chế Nga Hoàng được.

Sự khoan hồng của chính phủ lâm thời đã cho phép những người Bolshevik được quay
trở lại, tất cả tù nhân chính trị được thả tự do khỏi Siberia và những kẻ lưu
vong chính trị ở nước ngoài được mời trở về. Ngay khi nước Anh nghe tin Lenin
được cho phép trở về, họ đã cảnh báo đồng minh Nga rằng đó là một sai lầm nghiêm
trọng. Thực tế, cách duy nhất Lenin có thể quay trở lại Nga là thông qua sự hỗ
trợ của các đặc vụ Đức. Lý do cho sự hợp tác này của Đức là dễ hiểu.

Người Đức trở nên lo lắng về triển vọng trổi dậy, quay trở lại của người dân Nga,
và do đó họ tìm kiếm cơ hội tạo ra tinh thần hoang mang mất đoàn kết trong nội
bộ chính quyền lâm thời. Cuộc nói chuyện trao đổi ngắn ngủi với Lenin tại Thuỵ
Sĩ đã thuyết phục người Đức tin rằng Lenin chính là quân bài để hoàn thành nhiệm
vụ này. Không lâu sau đó, người Đức đã đưa Lenin cùng vợ và một số người Nga lưu
vong tới Thuỵ Điển thông qua Đức, giúp Lenin dễ dàng hơn để tới thủ đô Nga ngay
lập tức.

Khi Lenin tới Petrograd (tên mới của St. Petersburg, sau này đổi thành Leningrad),
đám đông nhiệt liệt đón chào giống như sự thông cảm giữa những đồng sự của cuộc
cách mạng. Nhân viên hộ tống quân đội giúp Lenin leo lên nóc một chiếc xe bọc thép
nơi đám đông đang chờ đợi nghe thấy những lời tuyên dương cho thành công của họ.
Nhưng khi những lời nhảm nhí (lip-clipped words) bắt đầu tuôn ra, họ nhận ra rằng
sự khen ngợi ca tụng cho thành công không có chỗ ở đây. Lối diễn thuyết khoa trương
khiêu khích theo đúng nghĩa đen đã biến thành tuyên bố mới cho một cuộc chiến tranh.

Lenin cay nghiệt bác bỏ những cố gắng của chính phủ lâm thời để thiết lập chế độ
cộng hoà. Lenin yêu cầu một chế độ Độc tài Cộng sản của gia cấp vô sản và kêu gọi
đấu tranh giành lại đất đai và ngay lập tức thúc ép người dân Nga tuân theo
nguyên tắc kinh tế của chủ nghĩa xã hội toàn trị. Lenin phản bác tất cả những cố
gắng tiếp tục theo đuổi chiến tranh và nói rằng hoà bình ngay lập tức với Đức nên
được đàm phán. (Sau này Lenin bị cáo buộc cố gắng kéo Nga ra khỏi cuộc chiến nhằm để
làm tròn nghĩa vụ với người Đức)
