==== Nước Nga cự tuyệt chủ nghĩa Cộng sản thông qua bầu cử

Trước khi chính phủ lâm thời bị hạ bệ thì ngày 25 tháng 11 đã được ấn định là ngày bầu cử quốc gia
để chọn ra hội đồng nhân dân hay quốc hội. Chính những người Bolsheviks đã tạo áp lực đòi hỏi
cuộc bầu cử này, do đó Lenin đã không dám hoãn bỏ nó mặc dù cuộc bầu cử đến trong thời điểm
mà Lenin đang cố gắng tập trung quyền lực cho riêng mình. Cuộc bầu cử đã diễn ra đúng như lịch
ấn định.

Kết quả của cuộc bầu cử này là một thảm hoạ kinh hoàng cho Lenin với kì vọng có được sự ủng hộ
đông đảo của quần chúng. Hơn 75%  dân số đã bỏ phiếu chống lại Lenin.  Rõ ràng điều này có nghĩa
là những người đại diện được nhân dân bầu ra sẽ chống lại chế độ Bolsheviks, và tất nhiên Lenin đã
có quyết định hành động khi những người đại diện cho nhân dân tụ họp vào ngày 18 tháng 1 năm 1918.

Lenin đã yêu cầu Hội đồng nhân dân trao lại chức năng lập pháp cho  "`Hội đồng Soviet`" bị  Bolsheviks
kiểm soát và sau đó bỏ phiếu để tự giải tán. Điều này tất nhiên là thật lố bịch và phi pháp, và họ không
thể chấp nhận. Lenin phải sử dụng đến chiêu trò cuối cùng - vũ lực. Ngay buổi sáng sớm hôm sau,
rất nhiều cảnh vệ có vũ trang xông vào sảnh họp ra lệnh cho các chính khách giải tán. Với những khẩu
súng trường cùng lưỡi lê sắc lẹm nhọn hoắt trong tay cảnh vụ, họ hiểu rằng không còn sự lựa chọn
nào khác và rời đi một cách miễn cưỡng.

Hành động vi phạm pháp luật trắng trợn này đã gióng lên hồi chuông chết chóc cho công cuộc dân
chủ tại nước Nga. Lenin cũng thừa biết rằng thủ đoạn bẩn thỉu này trước sau thì cũng sẽ bị những kẻ
thù tận dụng tuyên truyền nhằm hạ uy tín của mình. Vì vậy tất cả những cuộc đảo chính sau này của
Hồng vệ binh đều mang đến những ảo tưởng đạt được kết quả thông qua các tiến trình dân chủ thông
thường. Với thời điểm hiện tại thì mục đích đã đạt được, những người Cộng sản đã tiêu diệt được nguy
cơ cận kề hình thành nên chính phủ đại diện cho nguời dân Nga, cái chính phủ mà người dân Nga đã
từng biết đến mà không phải do Bolsheviks lãnh đạo.
Và  bây giờ mọi người dân bắt đầu sẽ học được điều gì đó về Chế độ độc tài của giai cấp vô sản.
