=== Cuộc cách mạng Nga tháng 3 năm 1917

Vào ngày 8 tháng 3 năm 1917, khi tinh thần nổi dậy tại nước Nga đã vượt qua ngưỡng
chịu đựng, lập tức tự bùng nổ gây ra làn sóng phẫn nộ chính trị sau thời kì Nga
Hoàng và đế chế của ông ta. Bạo lực tương đối ít, cảm giác nổi loạn khắp mọi nơi,
chỉ cần có tín hiệu đưa ra sẽ khiến cho hơn một phần tư triệu người xuống đường
tuần hành tại thủ đô. Khi đám đông chiếm được thủ đô, cuộc cách mạng tự động quét
sạch đế chế Nga Hoàng.

Cuộc cách mạng này có ý nghĩa to lớn đối với toàn bộ thế giới. Chúng ta nhớ lại
rằng mùa xuân năm 1917 là giai đoạn cực kỳ quan trọng của Thế chiến thứ nhất.
Hoa Kỳ vừa mới tham chiến, Pháp, Anh và Ý gần như kiệt sức.
Bởi vì mặt trận phía Tây gần như không cùng nhau tập trung chống lại sự tấn công
của quân Đức nên việc sụp đổ mặt trận phía Đông cùng với guồng máy chiến tranh với
vài triệu quân Nga có thể là thảm hoạ rất rõ ràng cho lực lượng quân Đồng Minh.

Cuộc nổi dậy tại Nga giữ một vai trò hết sức quan trọng đối với nước Đức.
https://www.history.com/topics/world-war-i/kaiser-wilhelm-ii[Kaiser] biết rằng
nếu Nga rút quân khỏi cuộc chiến thì lực lượng lớn quân Đức tại mặt trận phía
Đông sẽ có thể được chuyển sang mặt trận phía Tây. Đó sẽ là một lợi thế rất lớn
của quân Đức giúp cho họ có thể đập tan bất kỳ sự kháng cự nào.

Nhưng những con người đứng đằng sau cuộc nổi cách mạng Nga không bao giờ có ý định
để cho mặt trận phía Đông sụp đổ. Họ nổi dậy chống lại Nga Hoàng để bảo vệ nước
Nga chứ không phải đệ hạ bệ ông ta. Ngay khi chính phủ lâm thời thành lập, một
loạt các chương trình được công bố tạo ra chính phủ dân chủ, dựa trên hiến pháp,
thúc đẩy báo chí tiếp tục đấu tranh mạnh mẽ. Việc này đã khôi phục lại niềm tin,
hy vọng cho các Đồng minh phương Tây. Hoa Kỳ, Anh, Pháp và Italy ngay lập tức công
nhận chế độ mới, và trái tim của tất cả những con người tự do khắp mọi nơi hướng về
ngôi sau tự do dường như đang trỗi dậy bừng sáng lên trước nhưng người dân Nga
đang hân hoan mừng rỡ.

Đối với Nga Hoàng, rất khó để ông ta nhận ra được những gì đã xảy ra. Thời gian
đầu của cuộc cách mạng, Nicolas II từ chối thừa nhận rằng chính phủ đã bị tan rã.
Khi những cuộc biểu tình bắt đầu diễn ra, Nicolas II đã giải tán Duma (hội đồng nhân dân)
và ra lệnh cho quân lính tiêu diệt đám đông. Tuy nhiên chỉ trong vòng một tuần,
các bộ trưởng đã hối thúc ông ta thoái vị bởi những việc ông ta làm là vô vọng.

Phải cho tới khi chính những tướng lĩnh hối thúc thoái vị thì cuối cùng Nicolas II
cũng mới chịu chấp nhận. Ông ta và gia đình bị quản thúc tại cung điện Hoàng gia
bên ngoài Petrograd. Mặc dù người dân đã chịu đựng nhiều đau khổ dưới thời kì cai
trị của Nga Hoàng nhưng không vì thế mà chính phủ lâm thời có ý định giết ông ta.
Họ dự tính sẽ gửi ông ta và cả gia đình sang Anh ngay khi điều kiện thời chiến
cho phép.

Với sự hỗ trợ của Nga Hoàng, chính phủ lâm thời đã khởi xướng chương trình cải cách
rộng lớn trong nước và đồng thời củng cố lại sức mạnh quân đội. Trên chiến trường,
quân lính đã bắt đầu đáp trả, thể hiện một tinh thần chiến đấu mới và chỉ trong vài
tháng chương trình cải cách trong nước đã mang lại tiến bộ đáng chú ý trên mặt trận
tại quê nhà. Lần đầu tiên trong lịch sử, người dân Nga đã thấy triển vọng về một
chế độ dân chủ tự do đang cai trị họ. Hoàng tử Lvov - người đã tham gia vào cuộc
nổi dậy cùng dân chúng đã tuyên bố đầy tự tin: _"Hãy coi chúng ta là những người hạnh phúc nhất , thế hệ này đã tìm thấy điều đó trong giai đoạn hạnh phúc nhất của lịch sử đát nước Nga."_
