=== Nguồn gốc Bolsheviks

Vào năm 1903, Lenin cùng với vợ thành lập trụ sở tại London, họ cảm thấy rằng
họ đang mang vác sứ mệnh mà Marx đã ra đi để lại. Marx đã yên nghỉ được 17 năm
nhưng hai vợ chồng Lenin thường xuyên ghé thăm nghĩa trang nơi Marx được chôn cất.

Tháng 7 cùng năm đó, đại hội Dân chủ-Xã hội-Nga nhóm họp tại London. Có 43 khách
mời đến từ Nga cùng với các nhóm lưu vong Nga khác đến từ Tây Âu. Với tư cách
chủ tịch đại hội, Lenin bắt đầu với một thái độ ôn hoà và vô tư, nhưng dần dần khi
phát hiện các cuộc thảo luận có chiều hướng về một xã hội chủ nghĩa hoà bình chứ
không phải về cuộc cách mạng quân đội đã làm Lenin hoảng sợ lo lắng. Lenin ngay
lập tức tập trung lại các bạn bè cộng sự thân tín xung quanh, cắt riêng các chủ
đề thảo luận mở của hội nghị cho các đối tượng là thành viên của đảng - những nhà
cách mạng hạt nhân hoặc mở rộng cho tất cả những ai có thái độ đồng cảm với phong
trào.

Trong cuộc tranh luận này, Lenin tạm thời đã tập hợp được phần lớn hội nghị và từ
đó sử dụng nó làm cơ sở để gọi những người ủng hộ mình là "`Bolsheviks`" (từ này
trong tiếng Nga có nghĩa là "`đa số - majority`"). Trong khi những người phản đối
lại được gọi là "`Mensheviks`" (tiếng Nga có nghĩa là "`thiểu số - minority`").
Giá trị tuyên truyền của một cái tên Đảng với ý nghĩa là "`đa số`" đã nhanh
chóng được công nhận. Đó là một sự minh hoạ khác cho thấy quyết tâm tuyệt
đối của Lenin khai thác mọi tình huống làm công cụ để tiến xa hơn trong chiến
lược chính trị toàn cục.

Tuy nhiên, tại đại hội cụ thể như thể này chiến thắng của Lenin chỉ tồn tại trong
thời gian ngắn. Một số nhóm đã hợp sức để chống lại Lenin và sau này Lenin cũng
đã nhận ra chính mình đang đại diện cho phần lớn quan điểm của nhóm "`thiểu số`"
trong mọi các vấn đề. Nhưng Lenin vẫn tiếp tục gọi những người theo mình là
"`Bolsheviks`" và bất kì ai phản đối chống lại đều được gọi là "`Mensheviks`".
