=== Stalin nhúng tay vào hoạt động phạm tội

Mùa hè năm 1907, Stalin tổ chức cuộc họp bí mật với Lenin tại Berlin, sau đó Stalin
quay về lại Tiflis tiến hành vụ cướp đầy bạo lực. Đây không phải đơn
thuần là một vụ trộm tiền theo kiểu Robin Hood lấy của người giàu chia cho người
nghèo, mà đó lại là hoạt động của một nhóm gangster xã hội đen coi thường mạng
sống của tất cả đàn ông, phụ nữ trẻ nhỏ sinh sống trong thị trấn nơi quê hương
của Stalin.

Một quả bom với sức công phá cực mạnh đã được ném ra trước một đoàn xe chở tiền
đi từ bưu điện tới chi nhánh Tiflis của Ngân hàng Nhà nước. Quả bom đã tiêu diệt
những con ngựa kéo xe, giết chết nhiều người vô tội xung quanh, và làm bị thương
hơn năm mươi trẻ em và người lớn. Trong cơn cuồng loạn theo sau, những túi tiền
chứa 341.000 rúp (khoảng 170.000 đô la) đã bị những kẻ ném bom cướp khỏi xe và
vội vã mang đi.

Tội ác phản ánh sự coi thường hoàn toàn tính mạng con người đến nỗi các nhà
chức trách trong và ngoài nước Nga cố gắng truy tìm tất cả các khả năng có thể
phát hiện đầu mối để xác định danh tính những kẻ phạm tội.  Cuối cùng thì số tiền
cũng được tìm thấy dưới sự sở hữu của  Maxim Litvinov - một cộng sự thân cận của
Stalin (người mà sau này được Stalin gửi qua Mỹ vào năm 1933 nhằm tìm kiếm sự
công nhận của Mỹ cho Liên Bang Sô Viết).
Litvinov và một người bạn đồng hành đã bị chính quyền Pháp bắt giữ tại Paris khi
họ cố gắng đổi đồng rúp thành đồng franc trước khi gửi tiền cho Lenin.
Chi tiết về tội ác cuối cùng đã được các nhà chức trách làm sáng tỏ, và tên của
các thủ phạm ban đầu đã được tiết lộ. Tuy nhiên, Stalin đã thành công trong việc
duy trì ở mức độ lớn trong vài năm nữa và tiếp tục các hoạt động cách mạng của mình.
