=== Cuộc đời thời kì đầu của Nikolai (VI) Lenin

Marx khó có thể đoán được rằng nhà độc tài Cộng sản đầu tiên lại là con người như
Lenin, sinh ra vào ngày 22 tháng 4 năm 1870 tại Simbirsk bên bờ sông Volga.
Cha của Lenin là một Ủy viên Hội đồng Nhà nước với tước hiệu thừa hưởng dòng dõi
quý tộc trong khi mẹ là người Đức theo đạo Tin lành dòng Luther.
Lenin có mái tóc đỏ, xương gò má cao và đôi mắt xếch của tổ tiên Tartar từ Astrakhan.

Tên khai sinh của Lenin là Vladimir Ilich Ulyanov, còn tên "`Nikolai Lenin`" là
bí danh dùng để hoạt động cách mạng và đã trở nên nổi tiếng sau này. Khi còn bé
Lenin được dạy dỗ rất nghiêm ngặt từ người cha, một con người nhân văn lý tưỏng,
tự mình làm việc cho đến kiệt sức để thành lập 450 trường phổ thông trong khoảng
thời gian 17 năm. Người cha qua đời khi Lenin 15 tuổi, và ngay sau đó thảm kịch
thậm chí còn khủng khiếp hơn xảy ra với gia đình - người anh trai bị treo cổ.

Người anh trai này tên là Alexander, sắp bước sang tuổi 21, trước đó một thời gian
đã mất niềm tin vào tôn giáo của mình và bị ấn tưởng mạnh bởi triết học của chủ
nghĩa duy vật. Anh ta cũng cảm thấy được sự cần thiết có một hành động quyết định
để cải cách xã hội tại Nga.

Khi còn học tại trường đại học St. Petersburg (bây giờ gọi là Leningrad), Alexander
đã đồng ý cùng với một số cộng sự chế tạo bom nhằm ám sát Nga Hoàng đệ tam. Quả
bom được đặt trong cuốn từ điển y khoa giả, chứa chất nổ và chất hoá học rất độc
(strychnine). Cảnh sát đã phát hiện ra âm mưu ám sát ngay trước khi nó được thực
hiện, và toàn bộ nhóm của Alexander bị bắt giữ. Phiên toà xét xử buộc tội sớm
được tiến hành, và vào tháng 5 năm 1887, các tờ báo tại St. Petersburg thông báo
anh trai của Lenin đã bị lên giá treo cổ. 
