=== Cuộc đời thời kì đầu của Nikolai (V.I.) Lenin

Marx khó có thể đoán được rằng nhà độc tài Cộng sản đầu tiên lại là con người như
Lenin, sinh ra vào ngày 22 tháng 4 năm 1870 tại Simbirsk bên bờ sông Volga.
Cha của Lenin là một Ủy viên Hội đồng Nhà nước với tước hiệu thừa hưởng dòng dõi
quý tộc trong khi mẹ là người Đức theo đạo Tin lành dòng Luther.
Lenin có mái tóc đỏ, xương gò má cao và đôi mắt xếch của tổ tiên Tartar đến từ
vùng Astrakhan.

Tên khai sinh của Lenin là Vladimir Ilich Ulyanov, còn tên "`Nikolai Lenin`" là
bí danh dùng để hoạt động cách mạng và đã trở nên nổi tiếng sau này. Khi còn bé
Lenin được dạy dỗ rất nghiêm ngặt từ người cha, một con người nhân văn lý tưỏng,
tự mình làm việc cho đến kiệt sức để thành lập 450 trường phổ thông trong khoảng
thời gian 17 năm. Người cha qua đời khi Lenin 15 tuổi, và ngay sau đó thảm kịch
thậm chí còn khủng khiếp hơn xảy ra với gia đình - người anh trai bị treo cổ.

Người anh trai này tên là Alexander, sắp bước sang tuổi 21, trước đó một thời gian
đã mất niềm tin vào tôn giáo của mình và bị ấn tưởng mạnh bởi triết học của chủ
nghĩa duy vật. Anh ta cũng cảm thấy được sự cần thiết có một hành động quyết định
để cải cách xã hội tại Nga.

Khi còn học tại trường đại học St. Petersburg (bây giờ gọi là Leningrad), Alexander
đã đồng ý cùng với một số cộng sự chế tạo bom nhằm ám sát Nga Hoàng đệ tam. Quả
bom được đặt trong cuốn từ điển y khoa giả, chứa chất nổ và chất hoá học rất độc
(strychnine) dùng làm đạn. Cảnh sát đã phát hiện ra âm mưu ám sát ngay trước khi
nó được thực hiện, và toàn bộ nhóm của Alexander bị bắt giữ. Phiên toà xét xử buộc
tội sớm được tiến hành, và vào tháng 5 năm 1887, các tờ báo tại St. Petersburg
thông báo anh trai của Lenin đã bị đưa lên giá treo cổ.

Khi mọi chuyện lắng xuống, Lenin lúc này bước sang tuổi 17 bắt đầu quay trở lại
tập trung nghiên cứu về Marx và những cây viết phong trào cách mạng khác.
Cũng giống như người anh trai, Lenin mất niềm tin vào tôn giáo của mình 2 hay 3
năm trước đó và trở nên đồng cảm với chủ nghĩa nghi ngờ theo diễn giải của
những người Marxist. Thêm vào đó cái chết của người anh trai càng làm tăng
thêm quyết tâm cho Lenin để trở thành nhà hoạt động cách mạng sớm nhất ngay khi
có thể.

Để tự trang bị sự nghiệp cho bản thân, Lenin tập trung học và nghiên cứu ngành
luật rất nghiêm túc. Với sự giúp đỡ của người mẹ, Lenin được phép tham gia kì
thi cuối cùng tại trường đại học St. Petersburg và đã trở thành người đúng đầu
trong số 124 sinh viên. Lenin sau đó cũng cố gắng hành nghề luật nhưng vì một
số lý do gần như toàn bộ những trường hợp tham gia của mình đều bị thất bại.
Lenin đã từ bỏ nghề luật và không bao giờ quay lại nữa.

Năm 1891-1892 nạn đói và dịch tả bùng phát tại Nga. Lenin sống trong vùng cùng với
nơi mà đại thi hào Nga - Tolstoy đang cố gắng duy trì tổ chức hàng trăm bếp súp,
phân phát hạt giống, ngựa cho những người nông dân nghèo khổ, bần cùng. Nhưng
Lenin thì không hề nhúng tay vào việc giúp đỡ gì từ giúp đỡ nấu súp hay tham gia
uỷ ban cứu trợ. Sau này Lenin còn bị cáo buộc chào đón nạn đói như một phương tiện
làm nổi bật sự đau khổ chịu đựng của người dân nhằm khơi dậy ý chí cách mạng của
họ sẵn sàng hành động. Và chẳng có gì nghi ngờ những năm tháng sau này các chương
trình hành động Marxist đã đóng đinh vào tư tưởng của Lenin trở thành người cách
mạng không khoan nhượng.

Thời gian ngắn sau đó Lenin chuyển đến cư trú hẳn tại St. Petersburg.
Lúc bấy giờ Lenin 23 tuổi và rất nóng lòng muốn bắt đầu công việc hoạt động cách
mạng nên ngay lập tức tham gia tổ chức gọi là
"`Liên Đoàn Đấu Tranh Gỉải Phóng cho tầng lớp Lao Động - Fighting Union for the Liberation of the Working Class`".
Tuy nhiên năm 1895, Lenin phát hiện mình có khối u trong ổ bụng và phải sang Thuỵ Sĩ để
điều trị đặc biệt tại nhà dưỡng bệnh. Trong thời gian ở Tây Âu, Lenin đã liên lạc
với https://en.wikipedia.org/wiki/Georgi_Plekhanov[George Plekhanov] - lãnh đạo
của những người Nga Marxist sống lưu vong.

Lenin dành nhiều thời gian với Plekhanov và cảm thấy hãnh diện khi một người mới
đến như mình được người có vai trò quan trọng trong cộng đồng lưu vong chia sẻ
kế hoạch dùng bạo lực cách mạng lật đổ Nga Hoàng. Plekhanov khá ấn tượng về Lenin,
ông ta cảm nhận được nhiệt huyết của Lenin căm ghét tất cả những thứ gì nhuốm màu
bởi chế độ Nga Hoàng. Plekhanov quyết định Lenin nên trở về Nga, tập hợp những
người Marxist và tổ chức đảng chính trị Cộng sản quốc gia theo khuôn mẫu của đảng
Dân chủ Xã hội rất thành công ở Đức. Lenin cũng được yêu cầu bắt đầu xuất bản một
ấn phẩm định kỳ mang tính cách mạng.

Lenin chấp nhận nhiệm vụ được giao này như một sứ mệnh anh hùng mà số phận đã an
bài cho mình. Ngay khi trở về Nga, Lenin tổ chức biểu tình, đào tạo tuyển dụng,
thiết lập chiến lược chính trị và viết nhiều bài báo kêu gọi. Nhưng giữa lúc chiến
dịch đang nở rộ, một viên cảnh sát điệp vụ đã phản bội lại nhóm, Lenin bị kết án
lao động khổ sai lưu vong tại Siberia. Lenin chấp nhận việc gián đoạn này trong sự
nghiệp hoạt động cách mạng của mình với sự cam chịu cay đắng.

Ngay sau khi đến Siberia, Lenin đã kết thân với một cô gái cùng chung lý tưởng
Marxist tên là https://en.wikipedia.org/wiki/Nadezhda_Krupskaya[Nadezhda Krupskaya],
người mà Lenin đã gặp vào năm 1894. Cô được phép đến theo yêu cầu của Lenin nhưng
với điều kiện họ phải cùng nhau hợp pháp hoá mối quan hệ bằng một lễ thành hôn.
Việc này đã vi phạm nguyên tắc cơ bản của chủ nghĩa Marxist rao giảng "`bãi bỏ gia đình`",
nhưng họ đã tự cho phép để có thể chung sống được với nhau. Và bây giờ thì Lenin
đã có người bạn đồng hành tận tuỵ cống hiến cho cách mạng như chính con người của
mình. Họ không có con cái, những người cộng sự gần gũi với Lenin nói rằng họ chủ
ý lên kế hoạch để không có con cái, họ cảm thấy rằng sứ mệnh của họ không cho phép
bị vướng bận bởi những vấn đề cá nhân.

Lenin dành nhiều thời gian ở Siberia để nghiên cứu, viết hàng đống bức thư bằng
loại mực bí mật, cô đọng lại chương trình hành động cho một Đảng dân chủ xã hội
mới tại Nga và hoành thành cuốn sách của mình - _Chủ nghĩa Tư bản tại Nga - Capitalism in Russia_.

Khi được phóng thích năm 1900, Lenin trở thành một nhà cách mạng trưởng thành hơn,
cảnh giác hơn, đầy tính toán và mưu mô. Lenin ngay lập tức di chuyển đến Munich
nước Đức và bắt đầu in tạp chí "`Tia Sáng - The Spark`" để tuồn nhập lậu vào Nga.
Cuộc sống lưu vong 17 năm cùng với vợ tại Tây Âu của Lenin bắt đầu từ đây, họ chỉ
trở về thăm lại Nga trong một vài dịp rất hiếm hoi. Họ sống khiêm tốn, di chuyển
kín đáo và đợi chờ tiếng gọi của lịch sử giao phó vai trò giải phóng cách mạng.
