=== Chủ nghĩa Marxist đến nước Nga

Năm 1885, Andrew D. White công dân Mỹ trở về sau một nhiệm kì tại đại
sứ quán Hoa Kỳ ở St. Petersburg đã mô tả về tình trạng nước Nga lúc đó như sau:
Toàn bộ hệ thống chính phủ thuộc loại dã man tàn bạo nhất trên thế giới.
Không tồn tại một chế độ nào tương tự như vậy trên trái đất này, một xã hội
xuống cấp, một dân tộc bị nghiền nát, một hệ thống công quyền vô đạo đức như vậy.

Khi Andrew D. White đưa ra bản báo cáo này dân số nước Nga cỡ khoảng hơn 70 triệu
người, trong số đó 46 triệu sống trong tình trạng như bị tù giam giống như người
ở đợ.

Điều này nhắc lại thời kì Marx và Engels đã khơi gợi sự phẫn nộ của tầng lớp lao
động tại Anh quốc khi chứng kiến tình trạng tồi tệ của họ, nhưng tình trạng của
công nhân lao động tại Anh còn tốt hơn rất nhiều, vượt xa so với những người nông
dân nghèo khổ tại Nga đang phải chịu đựng.
Tầng lớp bần cố nông tại Nga không chỉ bị chết đói, bị bóc lột, bần cùng hoá
mà họ còn là nạn nhân, đối tượng của sự đàn áp hà khắc của hệ thống chính trị
phong kiến bàn tay sắt. Luôn luôn phải lo sợ mật vụ chìm, đe doạ bị bắt giữ và
bị phạt tù đày tại trại lao động khổ sai Siberia, cùng với sự hung bạo của lực
lượng quân đội Sa Hoàng trút lên những người nông dân khổ sở.

Nông dân Nga dường như không được hưởng bất cứ quyền miễn trừ thiêng liêng nào,
kể cả quyền con người, tài sản hay con cái của anh ta, và đôi khi cả vợ anh ta nữa.
Tất cả mọi người phải chịu đựng những thứ bẩn thỉu hèn mọn của lũ công quyền tham
lam dưới chế độ Nga Hoàng đầy tham nhũng và quan liêu.

Trong giai đoạn từ 1861 đến 1866, Nga Hoàng Alexander II đã cố gắng loại bỏ chế độ
nông nô, phê chuẩn một số cải cách giải phóng người nông dân. Tuy nhiên thực tế
thì cuộc sống nghèo khó của nông dân vẫn tiếp tục bấp bênh, khắc nghiệt và đói khổ,
tạo điều kiện nuôi dưỡng cho hoàn cảnh dẫn tới cuộc cách mạng là không thể tránh
khỏi.

Chủ nghĩa Marxist đến nước Nga vào năm 1868 khi bản dịch _Tư bản - Capitals_
của Bakunin thoát khỏi sự kiểm duyệt của Nga Hoàng và được truyền tay giữa những
người giải phóng cách mạng như những miếng ăn tinh thần của Chúa mang đến. Đối
với nước Nga, đó là sự châm ngòi cho ngọn lửa đỏ rực cháy trong tuyên ngôn Cộng
sản: _Hãy làm cho giai cấp thống trị run sợ trước cách mạng Cộng sản. Người vô sản không có gì để mất ngoài xiềng xích...Tất cả công nhân lao động trên toàn thế giới, hãy đoàn kết lại!_

Phong trào cách mạng Nga đã sớm bắt đầu hình thành và đến năm 1880 chủ nghĩa
Marxist mạnh lên, được thiết lập rõ ràng đi vào hoạt động. Vụ tấn công bạo lực đáng kể
đầu tiên xảy ra vào năm 1881 giết chết Nga Hoàng Alexander II sau khi cỗ xe Hoàng
gia bị ném bom, thực hiện bởi
link:++https://en.wikipedia.org/wiki/Ignacy_Hryniewiecki++[Ignatius Grinevitsky],
một thành viên của nhóm giải phóng _Nguyện ước nhân loại - The People's Will_.

Vụ ám sát Nga Hoàng thành công làm cho nhiều người Marxist cảm thấy thời khắc
cuộc cách mạng thoát bỏ xiềng xích đang đến rất gần. Ở London, Marx già nua bắt
đầu nhận được nhiều yêu cầu từ môn đệ của mình tại nước Nga.
Họ muốn biết liệu có thể có một cuộc cách mạng ở Nga hay không, mặc dù nền kinh tế
Nga chưa bao giờ vượt qua sự phát triển tư bản, điều mà Marx luôn khẳng định đó
là điều kiện tiên quyết. Marx đã nghiên cứu vấn đề này hết sức cẩn trọng, cuối
cùng thì Marx cũng đưa ra ý kiến của mình: _"Đây là cơ hội hiếm hoi của nước Nga và là cơ hội thích hợp nhất chưa từng có tại bất kì quốc gia nào để có thể bỏ qua giai đoạn phát trển tư bản"_.
Nói một cách khác, Marx đề nghị về một khả năng diễn ra cuộc cách mạng sớm tại Nga.

Điều này đã hoàn toàn trở thành bước ngoặt trong lý thuyết của Marx. Marx cũng
đã thừa nhận một trong những tiên đoán sai lầm trước đây nói rằng cuộc cách mạng
sẽ đến trước tiên tại những quốc gia tư bản phát triển mạnh như Đức và Anh. 
