=== Phong trào cách mạng nổi lên tại Nga

Các sự kiện miêu tả trong chương này là những thực tế gần gũi trong tâm thức của
tất cả những người Marxist nhà nòi. Người Cộng sản thường tranh luận dựa
trên diễn giải của những sự kiện này, do đó chúng ta sẽ tìm thấy một số nền tảng
lịch sử hữu ích ở đây.

Chương này cũng đề cấp về tiểu sử của một số nhà lãnh đạo Cộng sản cao cấp: Nikolai
(V.I.) Lenin, Leon Trotsky và Joseph Stalin.

Những câu hỏi dưới đây sẽ giúp tìm ra câu trả lời mà chương này mong muốn đem đến
cho độc giả:

****

. Ai khởi xướng chủ nghĩa Marxist ở Nga vào năm 1868? Tại sao Marx lại coi người
này là "`kẻ thù`" của ông ta? Sau khi ám sát Alexander II thì Marx đã nói gì về
khả năng về một cuộc Cách Mạng Cộng Sản tại Nga?

. Nikolai Lenin được xuất thân trong môi trường như thế nào? Tại sao người anh trai
lại bị treo cổ?

. Ai tổ chức phong trào Bolsheviks? Cái tên Bolsheviks có ý nghĩa là gì? Họ gọi
kẻ thù của họ là gì? Đây có phải chính xác là những gì được thiết kế theo kế
hoạch hay đó lại là vấn đề của chiến lược?

. Lai lịch của Leon Trotsky như thế nào? Tại sao ông ta lại có cái tên như vậy?
Làm thế nào ông ta trốn thoát khỏi Siberia? Tại sao ông ta chống lại Lenin vào
năm 1903?

. Phong trào cách mạng Nga năm 1905 được dẫn dắt bởi một số nhà cách mạng hay đó
là cuộc nổi dậy của tất cả người dân? Tại sao Lenin và Bolsheviks chống lại
"`Tuyên ngôn Tháng 10`" hứa hẹn người dân đại diện cho chính quyền?

. Joseph Stalin xuất thân trong kiểu gia đình gì? Tại sao ông ta bị đuổi khỏi
trường dòng, nơi ông ta được học để trở thành linh mục? Những hành động tội phạm
gì của Joseph Stalin suốt năm 1907 bộc lộ bản chất con người của ông ta? Những
hoạt động của Stalin như: tổ chức công đoàn, tuyên truyền viên, lãnh đạo phong trào
cách mạng được mở rộng như thế nào trong giai đoạn này? Mỗi quan hệ với Lenin là
gì?

. Điều gì đã mang nước Nga tới bờ vực của một cuộc tổng nổi dậy khác suốt thế
chiến thứ nhất? Thái độ của Nga Hoàng suốt cuộc khủng hoảng này là gì?

****
