=== Lai lịch Joseph Stalin

Joseph Stalin tên thật là Djugashvili, sinh ngày 21 tháng 12 năm 1879 tại một
thị trấn nhỏ thuộc Gori gần biên giới Thổ Nhĩ Kì. Ngày nay ngôi nhà gỗ nhỏ bé khiêm
nhường che chở cho Stalin những ngày đầu đời  đã trở thành di sản quốc gia, được
bao quanh bởi chiếc mái vòm bằng đá cẩm thạch.

Cha của Stalin là thợ làm giày, chết vì nghiện rượu khi Stalin mới lên 7 tuổi.
Mẹ Stalin phải tự mình vất vả giặt giũ, dọn dẹp, khâu vá và nướng bánh kiếm tiền
cho Stalin đi học. Mong ước của mẹ muốn Stalin trở thành linh mục nên Stalin được
gửi vào chủng viện thần học tại Tiflis gần đó.
Khi tìm hiểu về con đường của mình, Stalin phát hiện ra rằng bên trong chủng viện
được tổ chức với những xã hội bí mật. Nhiều người trong số họ đang thúc đẩy các
tác phẩm vô thần của Feuerbach và Bauer và các tác phẩm cách mạng của Marx và Engels.
Trước đó, Stalin đã tự thuyết phục bản thân rằng mình có sở thích cách mạng hơn
là tôn giáo và do đó, Stalin trở nên tích cực mạnh mẽ trong các tổ chức bí mật tồn
tại trong các nhóm sinh viên của chủng viện.
Stalin tiếp tục các hoạt động này trong gần ba năm, nhưng cuối cùng đã bị lộ vào
tháng 5 năm 1899, đồng thời bị trục xuất khỏi chủng viện với lí do
"`thiếu niềm tin vào tôn giáo`".

Khi đã gia nhập thế giới bên ngoài, Stalin dành toàn bộ thời gian của mình hoạt động
như một nhà cách mạng Marxist chuyên nghiệp. Stalin ta tổ chức các cuộc đình công,
tiến hành bất hợp pháp các lễ hội quốc tế lao động tháng 5 (May Day), và cuối cùng
trốn sang Batumi, nơi Stalin trở thành người thúc đẩy lao động chính cho đảng Dân
chủ Xã hội. Cuối cùng Stalin bị bắt và sau khi ở lại tù đến năm 1903, Stalin bị
kết án ba năm lưu đày ở Siberia.
Khi vẫn còn ở Siberia Stalin đã nghe về sự chia rẽ giữa những người Bolshevik và
Menshevik. Stalin gần như theo bản năng cảm thấy mình là một người Bolshevik cốt
lõi. Sau khi trốn thoát thành công khỏi Siberia vào năm sau đó, Stalin trở lại Tiflis
trở thành thủ lĩnh của những người Bolsheviks vùng Transcaucasian.
Trong cuộc cách mạng năm 1905, Stalin đã lãnh đạo cuộc cách mạng phá thai ở tỉnh
thuộc Georgia, quê hương của mình và ngay lập tức sau đó khởi hành đến Phần Lan
để tham dự Hội nghị Bolshevik, đồng thời liên lạc với Lenin.

Từ đó trở đi, Stalin giữ chức trợ lý cố vấn cho Lenin, người mà Stalin rất ngưỡng
mộ. Cũng không cần mất nhiều thời gian, lòng nhiệt thành với chủ nghĩa Cộng sản
của Stalin bắt đầu được biểu hiện hết sức mạnh mẽ.
