=== Stalin người tổ chức Công Đoàn, cây bút và lãnh đạo Bolshevik 

Thời gian từ năm 1907 đến 1913 là những năm tháng vất vả, khó khăn nhưng cần thiết
cho sự nghiệp chính trị của Stalin. Không ai có thể buộc tội Stalin đơn thuần
chỉ là loại "`trí thức Cộng sản`" như thỉnh thoảng họ vẫn mô tả Lenin. Stalin đã
học mọi thủ đoạn tuyên truyền, tạo áp lực chính trị, truyền thông đại chúng, các
kỹ thuật biểu tình và đình công lao động. Một số kinh nghiệm quan trọng nhất của
Stalin được minh chứng rất rõ ràng diễn ra trong khu công nghiệp năng động nhất
tại Baku - thủ đô Cộng hoà Azerbaijan. Stalin được phân công tổ chức hàng nghìn
công nhân lao động tại các giếng dầu và nhà máy lọc dầu. Để làm được điều này,
Stalin đã thành lập ba hệ thống gồm tổ chức hợp pháp, bán hợp pháp và hoàn toàn
bất hợp pháp. Stalin áp đặt sự lãnh đạo tuyệt đối của mình lên toàn bộ công nhân
trong khu trung tâm công nghiệp lớn này đến mức Stalin có thể tổ chức một liên
minh công nghiệp hùng mạnh (hội đồng công nhân) thống trị từ trên xuống dưới bởi
các cộng sự Bolsheviks trung thành.

Stalin chưa bao giờ là nhà diễn thuyết hiệu quả bởi vì chất giọng Georgian của
mình, nhưng từ năm 1907 đến 1913 Stalin đã trở thành cây viết cách mạng tài năng.
Trong một thời gian ngắn, Stalin làm biên tập cho một tờ báo Xã hội chủ nghĩa
tại Tiflis có tên _Dio_ (Thời gian - Time), Stalin đã khiến ngay cả những người
Bolshevik phải ngạc nhiên khi tấn công người Menshevik rất cay nghiệt trên tờ báo.
Năm 1910 Stalin chuyển đến St. Petersburg (bây giờ gọi là Leningrad) và viết cho
tờ Zvezda (Ngôi Sao) của Đảng Dân Chủ Xã Hội (Social Democrat), sau đó là tờ
Pravda (Sự Thật). Chính trong những ấn phẩm định kỳ này, cái tên Joseph Djugashvili lần
đầu tiên được biết đến với bút danh "`Người đàn ông thép - Man of Steel`" hay _Stalin_.

Năm 1912, Stalin nhận được sự công nhận đặc biệt khi Lenin ly khai hoàn toàn khỏi
Đảng Dân chủ Xã hội và thành lập Đảng Bolshevik độc lập. Trong tổ chức mới,
Lenin bổ nhiệm Stalin vào Ban chấp hành trung ương.

Tuy nhiên, ngay năm sau đó sự nghiệp của Stalin đã bị gián đoạn khi bị bắt và bị
đày đến Siberia. Đối với Stalin thì cũng không có gì là lạ vì từ năm 1903 bản thân
đã bị bắt đến tám lần, bị lưu đày bảy lần và trốn thoát sáu lần.
Nhưng trong vụ bắt giữ mới nhất này không có sự trốn thoát nào cả, Stalin được gửi
đến một trong những vùng xa xôi nhất của Siberia.

Chiến tranh thế giới thứ nhất đã nổ ra khiến cho Stalin không còn mong muốn đặc
biệt nào nhằm trốn thoát khỏi Siberia. Stalin nói với bạn bè muốn tận hưởng
"`kỳ nghỉ ngơi và thư giãn`" tại Siberia bởi vì nếu trốn thoát thì sẽ có khả năng
rất cao bị bắt phải gia nhập quân ngũ, việc này Stalin không hề muốn chút nào.
