=== Lai lịch của Leon Trotsky

Một trong những người nhiệt tình phản đối chống lại Lenin là cậu thanh niên trẻ
mới 23 tuổi tên là Leon Trotsky. Một ngày nào đó trong tương lai Lenin và Trotsky
sẽ cùng chiến tuyến, nhưng tại đại hội năm 1903 họ đã đứng về hai phía khác nhau.
Chúng ta sẽ dừng tường thuật một chút để tìm hiểu tóm tắt về cuộc đời của Leon
Trotsky.

Xét về nhiều khía cạnh, lai lịch của Lenin và Trotsky có rất nhiều điểm tương đồng.
Cùng được sinh ra trong những gia đình khá giả, được giáo dục tốt,
bị mất niềm tin vào tôn giáo, tham gia hoạt động cách mạng và cùng bị kết án khổ
sai tại Siberia.

Tên khai sinh của Leon Trotsky là Lev Bronstein có cha là một nông dân giàu có
(hay còn gọi là Kulak). Cha của Trotsky là nạn nhân của chiến dịch bài Do Thái
của Nga Hoàng, phải chạy trốn khỏi cuộc sống thành thị chuyển đến sống tại huyện
nhỏ làm nông nghiệp gần Biển Đen (Black Sea), ở đó người ta không kì thị tôn giáo
như các thành phố lớn thời Nga Hoàng lúc đó. Tuy nhiên sau này khi các thành viên
của gia đình ngày càng đông lên, họ dần dần thôi không đi lễ tại nhà thờ Do Thái
địa phương cũng như không thực hành giới luật https://en.wikipedia.org/wiki/Sabbath[Sabbath]
của người Do Thái nữa. Cuối cùng thì người cha của Trotsky đã công khai thừa nhận
chiều hướng tôn thờ chủ nghĩa vô thần.

Khi Trotsky rời khỏi trường học, cậu thanh niên đã mang theo mình sự đồng cảm với
chủ nghĩa vật chất có được từ người cha và thái độ này sớm bắt đầu thăng hoa nảy
nở. Trong quá trình hoàn thành chương trình học tập ở trường, Trotsky không chỉ
cổ vũ, truyền bá cho chủ nghĩa nghi ngờ của một người tự thừa nhận là duy vật mà
còn luôn luôn thể hiện mong muốn mạnh mẽ trở thành nhà chính trị cách mạng. Cha
của Trotsky hầu như không hài lòng về những chiều hướng tư tưởng này nhưng cũng
chẳng có gì có thể khuyên can cậu con trai. Căng thẳng giữa hai người phun trào mỗi
lần Trotsky trở về nhà sau kì nghỉ hè và vài năm sau đó cậu con trai trở nên hoàn
toàn xa lánh với gia đình của mình.

Trong hoàn cảnh đó không khó để chủ nghĩa Marxist có được một vị trí trong tâm
trí của người thanh niên trẻ tuổi mỗi lần có cơ hội được tiếp cận. Quá trình
"`cải đạo`" này của Trotsky được tạo điều kiện thuận lợi hơn khi được tiếp thu chủ
nghĩa Marxist từ https://en.wikipedia.org/wiki/Aleksandra_Sokolovskaya[Alexandra Lvovna]
một người phụ nữ trẻ tuổi, hấp dẫn, lớn hơn 6 tuổi mà sau này Trotsky đã lấy làm vợ.

Trotsky lúc đó mới chỉ 19 tuổi và Alexandra quyết định giúp đỡ tổ chức Liên Đoàn
Công Nhân miền nam Nga. Trotsky được phân công làm nhiệm vụ in ấn những tờ báo bất
hợp pháp và việc này dẫn đến hậu quả là Trotsky đã bị bắt giữ biệt giam trong
suốt 3 tháng, luôn chuyển khắp các nhà tù; và cuối cùng bị đày tới Siberia nơi sau
này Alexandra cũng bị gửi đến. Họ cùng bị kết án 4 năm tù khổ sai ở vùng giá lạnh
cằn cỗi nơi có rất ít người định cư sinh sống.
Hai đứa trẻ đã ra đời trong khoảng thời gian lưu đày này.

Trotsky trốn thoát vào năm 1902 bằng cách tự vùi mình vào đống rơm của những người
nông dân, chạy ra đến đường ray xe lửa và dùng giấy tờ giả tự xưng là "`Trotsky`" -
đây là tên của cai tù quản lý trực tiếp, và cái tên này được bắt đầu sử dụng từ đó.
Với sự giúp đỡ của một số người đồng chí Marxist, Trotsky đã đến được London, tham gia
hội nghị Xã hội - Dân Chủ (được trình bày ở phần trước). Một thời gian sau Trotsky
gặp lại vợ và những đứa con của mình.

Cuộc gặp gỡ lần đầu tiên với Lenin diễn ra suôn sẻ. Lenin mô tả Trotsky là một
nhà cách mạng "`ít khả năng`", nhưng Trotsky đã đáp lại bằng cách đề xuất Lenin
làm chủ tịch của hội nghị. Tuy nhiên, trong suốt quá trình diễn ra hội nghị cũng
đã đủ để Trotsky nhận ra những thứ máu lạnh, sắc như dao cạo trong đầu của Lenin,
việc này khiến Trotsky rất e ngại. Trotsky cũng rất sốc khi Lenin phớt lờ, gạt bỏ
 những ý kiến trái chiều đến từ những thành viên lâu năm và rất được kính trọng
 trong Đảng khi họ phản đối quan điểm của Lenin. 
