=== Sức hấp dẫn của chủ nghĩa Cộng sản

Làm thế nào một nhà khoa học lớn hay một người có giáo dục tốt lại có thể rơi
vào chủ nghĩa Cộng Sản?. Trong suốt 20 năm câu hỏi này được vang lên khắp nơi
mỗi lần tiếp cận với tình báo Đỏ. Rất thú vị khi phát hiện ra cái cách Cộng sản phản
ứng lại những người có giáo dục bởi vì nó chứa đựng âm mưu "triết học của
tự nhiên". Triết học chủ nghĩa cộng sản dường như giải thích về nguồn gốc và sự
phát triển của tất cả sự vật tồn tại: cuộc sống, hành tinh, giải ngân hà, tiến
hoá, và thậm trí cả trí tuệ của loài người. Với những ai chưa từng đào sâu nghiên
cứu triết học thì những khái niệm này đôi lúc thuyết phục, gây cảm hứng. Do vậy
chương này sẽ giải quyết những vấn đề đó.

Có lẽ tài liệu này hơi khó đó đọc, tuy vậy lý thuyết cộng sản cũng khá dễ tiêu hoá
trong tóm tắt cô đọng này nếu như các bạn sinh viên dành vài tháng đào sâu hơn
những bài luận, dữ liệu kỹ thuật trong các ấn phẩm của chủ nghĩa Cộng sản.
Các bạn nên tiếp tục nghiên cứu chủ nghĩa Marxist cho tới khi có thể trả lời được
những câu hỏi này:

****

. "Luật đối ngẫu - law of opposites", "Luật phủ nhận - law of negation"
của chủ nghĩa cộng sản là gì? Diễn giải "luật chuyển hoá - law of transformation".

. Các nhà triết học cộng sản giải thích thế nào về nguồn gốc sự sống? Vũ trụ này
có mục đích không, có "nhà thiết kế" không?

. Khái niệm "tất cả vạn vật là kết quả tích luỹ ngẫu nhiên" của Cộng sản nghĩa là gì?

. Chủ nghĩa cộng sản có Chúa không? Feuerbach nói Chúa của loài người thực sự ý
là như thế nào? Ai đã viết rằng Marx nói phải tái tạo lại thế giới? Marx và Engels
biện hộ cho việc sử dụng bạo lực như thế nào?

. Nguỵ biện cơ bản của quy luật đối ngẫu Cộng sản là gì? Nguỵ biện vốn dĩ của
quy luật phủ định là gì? Điểm yếu của quy luật chuyển hoá?

****
