=== Đặc điểm của chủ nghĩa Cộng sản

Ảnh hưởng của Marx và Engels vẫn tiếp tục lan truyền trên trái đấy, không chỉ
đơn giản là vì họ chống lại rất nhiều thứ mà còn bởi vì nó đại diện cho một cái
gì đó. Trong một từ, họ hứa hẹn rằng đó là để thoả mãn hai nhu cầu lớn nhất cho nhân
loại: cần thiết cho hoà bình toàn thế giới và cần cần thiết cho một sự thịnh vượng
chung.

Thực tế rất rõ ràng chủ nghĩa Cộng sản đã đưa ra đề nghị hấp dẫn thiên niên kỷ
cho tất cả những người mất phương hướng, bất mãn, không hạnh phúc trong xã hội.
Hơn thế nữa, đề nghị này còn đảm bảo một phiên điều trần có mặt không chỉ là tầng lớp
lao động bị trị mà còn có cả quý tộc thượng lưu, giàu có, và các nhà kinh tế học
chính trị học.

Những con người này khi nghe được Marx cùng Engels thuyết giảng làm thế nào để
đạt được hoà bình, thịnh vượng chung cho nhân loại, họ bắt đầu chia rẽ thành hai
phe riêng biệt, ủng hộ hoặc chống lại Cộng sản. Một phe cho rằng chủ nghĩa Cộng
sản là thử nghiệm đáng giá thay vì đó là một trận tắm máu kinh hoàng mà nó đã
đem tới cho nhân loại (nếu nó đúng là chiếc cổng dẫn tới hoà bình lâu dài thì thêm
một cuộc chiến tranh nữa thì thế nào?).
Phe còn lại nhấn mạnh rằng chủ nghĩa Cộng sản đã chối bỏ hoàn toàn, huỷ hoại, làm
mất đi các giá trị nhân bản của loài người đạt được sau hàng nghìn năm lịch sử
đấu tranh.

Vậy thì đặc điểm của Cộng sản là cái gì?

Trong chương này chúng ta cố gắng tối giản chủ nghĩa cộng sản xuống thành những
công thức đơn giản. Các bạn sinh viên sẽ thấy rằng Marx và Engels không chỉ giải
quyết, xử lý đối với bạo lực cách mạng và nền kinh tế Cộng sản mà còn có rất nhiều
các vấn đề khác. Thực tế họ đã phát triển khung các ý tưởng được thiết kế để giải
thích cho tất cả sự tồn tại của vạn vật. Triết học này đã là niềm kiêu hãnh và
yêu thích của những trí thức Cộng sản hiện đại, do đó đáng để được nghiên cứu
phân tích kỹ lưỡng.
