=== Nguồn gốc sự sống - nhận thức và ý thức

Trên nguyên tắc cơ bản này, các nhà triết học Cộng sản đã khẳng định rằng các hiện
tượng trong sự sống là sản phẩm của những bước nhảy vọt. Engels phát biểu cấu
trúc hoá học phức tạp của vật chất tiến hoá cho tới khi chất
link:++https://en.wikipedia.org/wiki/Albumin++[albumin] được tạo thành, và sự
sống cũng bắt đầu hình thành từ đó.
Thực tế Engels nhấn mạnh rằng, không thể có vật chất thiếu vận động, cũng không
thể có sự sống mà thiếu albumin. Đó là tính chất vốn có của albumin - hình thái
cao hơn của vận động tự nhiên. footnote:[Engels, Friedrich, Anti-Duhring, pp. 78, 85.]

Engels cũng đề xuất rằng sự sống bị ràng buộc để tăng tính phức tạp ngay
khi nó được hình thành từ chất albumin. Chủ nghĩa duy vật biện chứng là một triết
học tiến hoá. Tuy vậy những người công sản lại không tin rằng hình thái mới của tự nhiên
là kết quả của thay đổi dần dần mà là sự gia tăng cấp số nhân về lượng tạo
đà cho "bước nhảy vọt - leap" trong tự nhiên, tạo ra sự thay đổi hoặc giống loài
mới.

Cộng sản tin rằng sự ngẫu nhiên xảy ra với một trong những bước nhảy vọt thì
hiện tượng nhận thức xuất hiện. Các sinh vật trở nên nhận biết được lực xung quanh
tác động lên chúng. Sau đó ở một hình thái khác, cấp độ cao hơn của sự
sống sẽ xuất hiện khả năng biểu hiện ra để tương tác, làm việc với những tác động này
(sắp xếp chúng trong sự kết hợp mới), và lúc đó ý thức xuất hiện giống như sự
thông minh, sự tự nhận biết, tự quyết định chất lượng trong vật chất. Tuy nhiên
vật chất là quan trọng nhất, còn ý thức là thứ yếu. Ở đâu có không có vật chất
ở đó sẽ không có ý thức. Do vậy không có khả năng tồn tại của linh hồn, sự bất tử,
và Chúa.

Triết học Cộng sản trở nên hoàn thiện với quy luật chuyển hoá được nêu ra và
những nhà duy vật biện chứng cảm thấy họ đã đóng góp trí tuệ to lớn cho nhân loại
khám phá hiểu biết vũ trụ này:

. Vật chất là sự đồng nhất đối ngẫu tạo ra mâu thuẫn làm cho nó tự vận động, tự
cung cấp năng lượng, do đó vật chất không cần năng lượng bên ngoài cho biểu hiện
vận động của nó.

. Thông qua hình mẫu liên tục phủ định hoặc chết đi, tự nhiên có xu hướng tự nhân
lên và lấp đầy vũ trụ với sự phát triến có trật tự, hoặc gia tăng mà không
đòi hỏi bất kỳ trí thông mình hướng dẫn nào.

. Thông qua quy luật chuyển hoá, vật chất có khả năng tạo ra hình thái mới mà không
cần đến bất kì quyền lực sáng tạo hay chỉ dẫn nào ngoài chính bản thân nó.

Với sự phát hiện ra những quy luật này, Engels đã khoe khoang: "Di sản cuối
cùng của Đấng Sáng Tạo bên ngoài thế giới đã bị xoá sạch."
footnote:[ Engels, Friedrich, Anti-Duhring, p. 18.]

Tóm tắt một cách ngắn gọn lại có thể thấy rằng những trí thức cộng sản tin mọi
vật tồn tại là kết quả của sự vận động không ngừng nghỉ giữa các lực trong tự
nhiên. Tất cả là sản phẩm của tích luỹ ngẫu nhiên. Không có thiết kế, không có
luật lệ, không có Chúa, chỉ có vật chất và lực trong tự nhiên.

Đối với một người bình thường các nhà triết học Cộng sản dạy rằng anh ta chỉ là
một động vật trưởng thành - một sự ngẫu nhiên của tự nhiên giống như các hình thái
khác của sự sống. Tuy nhiên thì anh ta được tin rằng mình có may mắn ngẫu nhiên đủ
tốt để sở hữu trí thông minh tối thượng trong sự tồn tại của mình. Điều này có nghĩa
rằng anh ta là Chúa thật sự của vũ trụ này. Đây chính xác là những gì Ludwig Feuerbach
đã nói: _"Bước ngoặt của lịch sử sẽ là khoảnh khắc khi con người trở nên nhận thức
được rằng Chúa của con người là chính con người anh ta mà thôi."_

Những việc này lý giải cho hầu hết lòng đam mê sốt sắng của những nhà lãnh
đạo Cộng sản mong muốn tiêu diệt, phá huỷ toàn bộ tất cả các hình thái của tôn giáo
và tôn sùng Chúa. Nikolai Lenin tuyên bố: _"Chúng ta phải chiến đấu với tôn giáo
- đây là điều cơ bản của chủ nghĩa duy vật và kết quả của chủ nghĩa Marxist"_.
Khi Karl Marx được hỏi mục đích trong cuộc đời mình là gì, ông ta đã trả lời: _"
để phế truất Chúa và tiêu diệt chủ nghĩa Tư bản"_.
Thật thú vị khi quan sát thấy rằng khi chối bỏ Chúa, kinh thánh, đạo đức, sự bất tử,
sự phán xét của Chúa, chối bỏ sự tồn tại của linh hồn và sự thánh thiện linh thiêng
của con người, những nhà duy vật biện chứng đã chuyển sự tôn sùng sang chính bản
thân họ. Họ cho rằng con người là hình ảnh thu nhỏ của sự hoàn hảo
giữa những thành tựu của thiên nhiên và do đó là trung tâm của vũ trụ.

Nếu con người được cho là có sẵn trí tuệ tối thượng, thì tái tạo
lại thế giới là bổn phận của họ. Một cách tự nhiên, Marx tin rằng trách nhiệm
không thể tránh khỏi này là của các nhà lãnh đạo Cộng sản, vì họ những người duy
nhất hiểu biết thật sự về khoa học xã hội và tiến bộ kinh tế.
Marx và Engels chấp nhận thực tế để tái tạo lại thế giới thì phải tàn bạo, không
khoan nhượng, tiêu diệt tất cả những ai ngăn cản con đường này. Họ nói việc này
là cần thiết để cho phép sự lãnh đạo Cộng sản chỉ trong một lần sẽ quét sạch tội
lỗi xã hội và kinh tế của loài người không hoàn hảo, sau đó sẽ giới thiệu một mô
hình xã hội hoàn hảo mới, hài hòa, cho phép loài người sống một cách khoa học,
an toàn, hạnh phúc.

Tuy nhiên trước khi tiến hành tấn công táo bạo trực diện vào những mục tiêu xác
định kia, những người sáng lập chủ nghĩa Cộng sản nhận ra rằng có lẽ họ cần phát
triển toàn bộ cách tiếp cận mới về các vấn đề đạo đức, nguyên tắc chuẩn mực áp
dụng cho những tín đồ của họ.
Lenin tóm tắt: _"Chúng ta nói rằng, đạo đức của chúng ta là những gì phục vụ
lợi ích cho đấu tranh giai cấp của những người vô sản"_.
footnote:[Lenin, V. I., Religion, p. 47]

Nói một cách khác, đạo đức tốt là bất kể những gì có xu hướng đem lại cải tiến,
làm tốt hơn khái niệm duy vật cộng sản, còn không thì là đạo đức xấu.
Quan điểm này về đạo đức rất rõ ý đồ muốn chấm dứt biện minh rằng không sai khi
nói dối, lừa đảo, vi phạm lời tuyên thệ hoặc thậm chí huỷ hoại nhân loại nếu đó
là lí dó đúng. Quy chuẩn không có đạo đức này lý giải cho những hành vi, cư xử
vô luân lý của một bộ phận những người Cộng sản, điều mà người ngoài thường
không thể hiểu nổi.
