=== Phê bình triết học tự nhiên Cộng sản

Từ kinh nghiệm quan sát thực tế, những người mới bị chuyển hoá thành cộng sản
thường có cảm giác rằng mình là người toàn trí, biết hết mọi thứ hơn với những
người chưa chuyển hoá. Anh ta cảm thấy cuối cùng thì vũ trụ cũng đặt trước mặt
mình đơn giản và dễ hiểu. Nếu anh ta chưa từng bao giờ đánh vật với những vấn đề
triết học thì rất có khả năng bị choáng ngợp bởi khả năng gây cảm hứng khi biết
rằng con người cuối cùng cũng đã giải quyết được những vấn đề cơ bản nhất để hiểu
rõ vũ trụ thông qua _chủ nghĩa duy vật biện chứng_.
Ở trạng thái này của ý thức, các bạn sinh viên thường đánh mất thái độ yêu cầu phản biện.
Các bạn sẽ tiếp nhận những thứ rao giảng này rất mạnh mẽ bởi vì các bạn chắc chắn
hoàn toàn rằng cuối cùng đã khám phá ra _chân lý_ tồn tại dưới hình thái căn bản
của nó.

Có rất nhiều thứ cảnh báo, ngay lập tức nhận ra sự nguỵ biện trong triết học Cộng
sản. Lấy ví dụ về quy luật đối ngẫu. Quy luật này tuyên bố tất cả vật chất là sự
đồng nhất đối ngẫu, năng lượng được phát ra dưới biểu hiện bên ngoài đối ngẫu được gây
ra bởi các thành phần đối nghịch mâu thuẫn. Điều này được cho là lý giải nguồn
gốc của vận động. Nhưng cần chú ý ở đây: hai thành phần đối nghịch mâu thuẫn sẽ
không bao giờ cùng nhau đi đến một nơi xác định, trừ khi _chúng tự thân đã có năng
lượng_. Các lực đối nghịch nhau trong tự nhiên được phát hiện có năng lượng
độc lâp với nhau. Việc hợp nhất chúng lại chỉ đơn thuần là việc kết hợp năng
lượng hoặc vận động đã tồn tại sẵn từ trước. Do đó các học giả triết học đã chỉ
ra rằng #quy luật đối ngẫu của Cộng sản không giải thích nguồn gốc của vận động, và quy luật này chỉ mang tính phỏng đoán#
footnote:[For an extended discussion of this problem see The Philosophy of Communism, by Dr. Charles McFadden, pp. 177-184.]

Một học giả đã hài hước rằng: _"Hai thành phần bất động không thể sản sinh ra mâu
thuẫn và tạo ra vận động giết chết hàng nghìn người tư sản và cả triệu mạng người khác
như Cộng sản đã tạo ra trong cuộc chiến tranh giai cấp."_

Nhắc lại một chút về quy luật thứ hai của triết học Cộng sản - quy luật phủ định.
Quy luật này phát biểu rằng các lực đối nghịch mâu thuẫn trong một thực thể có
chiều hướng tự phủ định, nhưng thông qua quá trình chết đi, lực vận động được
giải phóng ra, thậm chí mở rộng phát triển hơn. Trường hợp hạt cây lúa mạch tự
nảy mầm và tự phủ định tạo ra cây lúa mạch, sau đó cây lúa mạch tự phủ định tạo
ra một số lượng hạt mới. Đây chính là lý giải cho việc gia tăng số lượng trong
tự nhiên.

Nhưng tiến sĩ Mc.Fadden đã chỉ ra trong cuốn sách "`Triết học chủ nghĩa Cộng sản
- The Philosophy of Communism`": #quy luật phủ định không giải thích gì cả#,
chỉ đơn thuần mô tả hiện tượng tự nhiên. Sự thực kế hoạch của tự nhiện là tự tái
tạo chính nó với số lượng ngày càng mở rộng, nhưng sự chết đi (sự phủ định) của
thế hệ trước không nhất thiết liên quan gì đến năng lực tự tái tạo chính nó.
Việc lớn lên hay chết đi vẫn tiếp diễn cho dù có tự tái tạo hay không, và một số
thì tự tái tạo lặp đi lặp lại trước khi bất kì sự phủ định nào xảy ra.

Vấn đề trong quy luật thứ nhất và thứ hai để lại cho các nhà triết học Cộng sản
một vị trí tranh cãi rất rõ ràng: không chỉ sự vận động và sự sống là _tự vận động_,
_tự tạo ra một cách tự phát_, mà sự phát triển của hạt lúa mạch thành cây, cây
tái tạo ra rất nhiều hạt lúa mạch mới khác, lại chính là kết quả của
sự _tích luỹ ngẫu nhiên_. Engels thất vọng với khả năng bị mắc kẹt trong tình
thế này và đồng ý rằng có "luật lệ, trật tự, nhân quả và những thứ tất yếu trong
tự nhiên". footnote:[Quoted by V. I. Lenin in Materialism and Empiro-Criticism, p. 125.]
Tuy nhiên Engels không thừa nhận về khả năng tồn tại của một thiết kế thông minh,
siêu việt trong tự nhiên, nhưng lại nói rằng hạt lúa mạch tạo ra cây, cây tạo ra
nhiều hạt lúa mạch hơn là do _tự nhiên yêu cầu nó như vậy_.
footnote:[Engels, Friedrich, Anti-Duhring, p. 79]
Vậy thì tại sao nó lại được yêu cầu như vậy? Các bạn sinh viên sẽ gặp chút khó
khăn để phát hiện ra rằng Engels đang tranh luận một cách mù quáng, không phải do
vấn đề bị che đậy bởi những thuật ngữ triết học, mà đó là những lực chưa được biết đến
của vận động cơ học trong tự nhiên có khả năng tự xắp sếp chúng để biến đổi những
thứ lộn xộn, phức tạp thành những thứ đã được _quyết định trước, thiết kế từ trước đó_.
Vậy có tồn tại những hạt lúa mạch có thể yêu cầu, đòi hỏi sự phủ định chính nó và tạo ra cây
hay không? Các nhà _duy vật biện chứng_ giải thích thế nào khi những hạt lúa mạch
nảy mầm kia chỉ tạo ra một loại cây lúa mạch mà không phải là loại cây nào khác?

Nhà chức trách đã chỉ ra rằng Engels phát triển một hình mẫu tư duy dẫn đến những kết
luận mà thậm chí ngay bản thân Engels nhận ra là không thể chứng thực trong tự nhiên
được. Engels đã lẩn trốn đằng sau sự khái quát mơ hồ, gây cho những sinh viên
cảm thấy mập mờ khó hiểu, không thể tiếp cận.

Quy luật thứ ba, luật chuyển hoá, cũng chỉ mô tả hiện tượng tự nhiên, nhưng
thất bại khi giải thích nó. Nó xác nhận rằng, trong tự nhiên chúng ta đã phát hiện
ra rất nhiều loài khác nhau có những phẩm chất, tính chất và đặc điểm khác nhau.
Nhưng trong khi đó, các "`bước nhảy vọt`" có thể được tạo ra với một số xác định chất vô
cơ thông qua quá trình tích luỹ về lượng (giống như chất paraffin carbon) thì lại
không giải thích được phẩm chất mới, tính chất mới, hay đặc điểm mới được tạo ra
như thế nào. Hơn thế nữa, cũng chính nguyên lý này được dùng để giải thích sự
sống tự động được sinh ra từ chất albumin, các nhà triết học cộng sản đang thách
thức tất cả những thí nghiệm khoa học. Thực tế trong tự nhiên đã biểu hiện ra tất
cả: sự sống đem lại sự sống, không thể tạo ra sự sống bằng cách nhân tạo, hay tự
phát sinh phòng thí nghiệm hoặc tự phát sinh trong tự nhiên.

Những điểm yếu trong triết học Cộng sản này cuối cùng đã thuyết phục
link:++https://en.wikipedia.org/wiki/Whittaker_Chambers++[Whittaker Chambers]
(cựu điệp vụ Mỹ làm việc cho Cộng sản) thừa nhận mình đã bị lừa
dối. Những thuật ngữ nặng nề của biện chứng Cộng sản không cản trở anh ta trở nên
bị thuyết phục rằng những _lực lượng vật chất_ chưa được biến đến không thể tạo ra được
những thứ có độ phức tạp rất cao mà có thể tìm thấy xung quanh chúng ta.

Vấn đề thường được đặt ra: "`Hiện tượng tự xảy ra trong tự nhiên như việc hình thành
cơ quan, bộ phận có độ phức tạp giống như con mắt với hàng nghìn chi tiết cực nhỏ,
cần thiết cho viêc xử lý hình ảnh được kết hợp một cách chính xác tuyệt đối, về
mặt toán học là gần như không thể tính toán được.
Nhưng con mắt chỉ là một trong số các bộ phận phức tạp của cơ thể người. Xác suất
tự nhiên để tạo ra một cách chính xác những tổ chức vật chất tìm thấy trong các
bộ phận nội tạng hay trong các tuyến là giống nhau.
Chưa hết, trong cơ thể người, những đơn vị chức năng của các cơ quan và các tuyến
này được tổ chức hoạt động hoàn hảo. Và con người chỉ là một trong vô số loài của
tự nhiên, mỗi loài đều sở hữu những tổ chức kì diệu tương tự.`"

Những suy nghĩ này đã thức tỉnh Whittaker Chambers nhận ra thực tế xung quanh
phức tạp và uyên thâm hơn rất nhiều những lý giải của Cộng sản về
"`vận động và vật chất`" và Chambers đã rút mình ra khỏi triết học Cộng sản.

Chiến lược tuyệt vời của Cộng sản được những người sáng lập thực hiện đó là họ
không bao giờ dừng lại cái gọi là "`giả thuyết vô hại`" của chủ nghĩa duy vật biện
chứng. Những nguyên tắc được họ xây dựng dần dần thấm vào mỗi khía cạnh đời sống
của con người hàng ngày. Họ cổ suý, ủng hộ một cách tiếp cận mới về lịch sử, kinh
tế, chính trị, nguyên tắc đạo lý, kế hoạch xã hội và thậm chí cả khoa học.
Trong tuyên ngôn cộng sản, Marx và Engels đã thừa nhận phê bình chủ nghĩa Cộng sản,
có thể viết ngắn gọn:
_"bãi bỏ chân lý bất diệt, bãi bỏ toàn bộ tôn giáo và đạo đức thay vì dùng những
 giá trị này làm nền tảng cơ bản mới, do đó hành động đi ngược lại tất cả kinh
 nghiệm lịch sử."_
footnote:[Marx and Engels, Communist Manifesto, Authorized English Translation, p. 40]

Hơn một phần ba dân số trên trái đất này là đối tượng cho "`kế hoạch hành động`"
đáng sợ mà những người sáng lập Cộng sản tin rằng cần phải bắt buộc thực thi đối
với toàn bộ nhân loại vì lợi ích tối thượng của họ.
Chúng ta sẽ cố gắng khám phá chủ nghĩa Cộng sản đề xuất giải quyết các vấn đề
thế giới như thế nào.
