=== Triết học tự nhiên Cộng sản

Để bắt đầu, ý tưởng cơ bản của Cộng sản đó là mọi vật tồn tại có thể được
giải thích bằng một thứ: _"vật chất - matter"_. Vật chất giải thích tất cả
cho những khái niệm như: nguyên tử, hệ mặt trời, thực vật, động vật, tâm lý ý
thức, trí thông minh loài người và những khía cạnh khác của sự sống.
Triết học cộng sản duy trì quan điểm nếu như khoa học có khả năng nhận biết những
gì cần biết về vật chất, thì chúng ta sẽ biết tất cả những gì cần biết về mọi
thứ. footnote:[Engels, Friedrich, Ludwig Feuerbach, International Publishers, New York, 1934, p. 31.]

Chủ nghĩa cộng sản do đó đã giao phó cho khoa học một nhiệm vụ vĩ đại biến con người
trở nên toàn trí - biết tất cả sự thật - nhưng lại bị giới hạn điều tra khám phá
cho một thực tại: _vật chất_. Vật chất được chấp nhận hoàn toàn như sự khởi đầu
và kết thúc của tất cả thực tại.

Triết học cộng sản sau đó đặt ra ba câu hỏi để trả lời:

. Nguồn gốc của năng lượng hay vận động trong tự nhiên là gì?

. Cái gì gây ra sự gia tăng số lượng của dải ngân hà, hệ mặt trời, hành tinh,
động vật và tất cả vương quốc trong tự nhiên?

. Nguồn gốc của cuộc sống, các giống loài, tâm trí và ý thức con người là gì?

Marx và Engels đã trả lời ba câu hỏi trên dựa vào ba quy luật đã phát biểu trước
đó:

*Quy luật đối ngẫu:*

Marx cùng Engels bắt đầu với quan sát tất cả sự vật tồn tại
như là sự kết hợp hoặc đồng nhất đối ngẫu - unity of opposites.
footnote:[Conze, E., Dialectical Materialism, London, N.C.L.C Society, 1936, p. 35.]
Dòng điện được đặc trưng bởi điện tích dương và âm. Hạt nhân nguyên tử bao gồm
hạt proton và electron được hợp nhất nhưng có lực đối nghịch.
Trong mỗi cơ thể sống đều có tính chất của sức hấp dẫn và sự phản kháng lại.
Thậm chí trong nội tâm bản chất con người cũng có thể tìm thấy những tính chất
đồng nhất đối ngẫu: sự ích kỷ và lòng vị tha, dũng cảm và hèn nhát, thái độ xã
hội tích cực và tiêu cực, khiêm tốn và kiêu ngạo, nam tính và nữ tính.
Cộng sản kết luận rằng tất cả vạn vật tồn tại "`chứa đựng hai phần hoặc hai khía
cạnh không tương thích, loại trừ lẫn nhau, nhưng không kém phần thiết yếu và không
thể thiếu.`"
footnote:[Conze, E., Dialectical Materialism, pp. 51-52; See also Engels, Friedrich, Socialism: Utopian and Scientific, pp. 47- 48.]

Bây giờ thì khái niệm của Cộng sản đi đến: sự đồng nhất đối ngẫu làm
cho mọi thực thể tự vận động, cung cấp động lực liên tục cho vận động và thay đổi.
Ý tưởng này được mượn từ link:++https://en.wikipedia.org/wiki/Georg_Wilhelm_Friedrich_Hegel++[Georg Wilhelm Hegel]
(1770-1831) với câu nói: "`Mâu thuẫn trong tự nhiên là nguồn gốc của tất cả vận
động và sự sống`".footnote:[Quoted by V. Adoratsky, Dialectical Materialism, pp. 26-27]

Từ khái niệm trên sẽ giới thiệu tiếp cho chúng ta những quan sát cơ bản đầu tiên về
biện chứng Cộng sản - Communist dialectics.
Nó đại diện cho ý tưởng _"mâu thuẫn - conflict"_ trong tự nhiên. Những sinh viên
mới nghiên cứu triết học Cộng sản có thể hiểu tốt hơn ý nghĩa của "phép biện chứng" nếu
mỗi khi nó được thay thế bởi từ "mâu thuẫn" ở đâu đó.

Đến đây hy vọng các bạn đã hiểu rằng theo triết học Cộng sản: mỗi sự vật tồn tại
trong vũ trụ này đều ở trạng thái vận động - kết quả của lực đối nghịch với nhau,
đấu tranh bên trong.

*Quy luật phủ định:*

Sau khi giải thích về nguồn gốc của sự vận động và năng lượng
trong vũ trụ, các học giả Cộng sản tiếp tục giải thích chiều hướng liên tục gia
tăng số lượng của vạn vật trong tự nhiên. Họ khẳng định mỗi thực thể có chiều hướng
tự phủ định bản thân để tái tạo với số lượng lớn hơn.
Engels nêu ra trường hợp hạt cây lúa mạch (trong trạng thái tự nhiên của nó)
tự nảy mầm, và chết đi (tự phủ định) tạo thành cây. Cây tự lớn lên, trưởng thành
và tự phủ định bản thân sau khi cho ra rất nhiều hạt. Do vậy, tất cả tự nhiên mở
rộng không ngừng thông qua quá trình chết đi.
Các thành phần của đối ngẫu tạo ra mâu thuẫn trong mỗi sự vật và đem lại vận động
thì cũng có chiều hướng tự phủ định chính nó. Ngoài quá trình vận động thay đổi
liên tục của sự chết đi, năng lượng được giải phóng dùng để mở rộng và tái tạo lại
thực thể cùng loài với số lượng lớn hơn.
footnote:[Engels Friedrich Anti-Duhring, p. 138]

Giải thích xong về sự gia tăng số lượng trong vũ trụ, các nhà triết học Cộng sản
tiếp tục bắt đầu giải thích về sự khác nhau của tạo hoá tự nhiên.

*Quy luật chuyển hoá:*

Quy luật này phát biểu rằng nếu như sự phát triển liên tục
về lượng của một lớp cá biệt nào đó sẽ dẫn đến "`bước nhảy vọt - leap`" trong tự
nhiên, hình thành nên hình thái hoàn toàn mới hoặc thực thể mới được sinh ra.
footnote:[Engels, Friedrich, Anti-Duhring, p. 145]
Hãy xem ví dụ sau, trường hợp của chất
link:++https://en.wikipedia.org/wiki/Alkane++[paraffin hydrocarbon]:

"`Đây là chất hoá học hữu cơ chỉ bao gồm carbon và hydro, có công thức tổng quát
C~n~H~2n+2~. Chúng ta lấy _methane_ CH~4~ làm khởi điểm bắt đầu minh chứng cho luận điểm.
Nếu như chúng ta thêm vào _methane_ 1 nguyên tử carbon và 2 nguyên tử hydro
thì ta sẽ thu được chất hoàn toàn mới gọi là _ethane_ C~2~H~6~. Tương tự nếu ta thêm
1 nguyên tử carbon và 2 nguyên tử hydro khác vào _ethane_, ta sẽ thu được chất
cũng hoàn toàn mới là _propane_ C~3~H~8~. Thêm tiếp cùng số lượng carbon và hydro
như trên ta thu được chất thứ tư _brutane_ C~4~H~10~. Và lại tiếp tục thêm tiếp ta
có được chất hoá học thứ năm _pentane_ C~5~H~12~.`"
footnote:[McFadden, Charles J., The Philosophy of Communism, p. 50; see also C. Porter, The Carbon Compounds, p. 10.]

Các nhà triết học Marxist ngay lập tức kết luận rằng có một manh mối cho cái gọi
là "`Năng lực Sáng Tạo - Creative Power`" của tự nhiên. Vật chất không chỉ tự vận động
và có khuynh hướng tự gia tăng số lượng, mà còn thông qua tích luỹ về lượng, nó
có khả năng tự "nhảy vọt" hình thành nên trạng thái mới và cấp độ mới của
thực tại.

Marx và Engels cảm thấy rằng họ đã không chỉ tìm ra lời giải thích cho "`nguồn gốc
các loài`", mà còn phát hiện ra giải thích gây phấn khích, bất ngờ cho bí mật vĩ đại:
Sự sống là gì?
