=== Phê bình cách giải quyết của Cộng sản

Sinh viên nghành lịch sử và kinh tế ngày nay sẽ cảm thấy khó khăn đôi chút khi tìm
hiểu về lý thuyết Cộng sản, không rõ lý thuyết này xuất phát từ những khía cạnh
thực tế cơ bản nhất nào.

Những môn đồ của Marx ngước nhìn lý thuyết chủ nghĩa Cộng sản giống như một quá
trình phân tích thâm nhập lịch sử mà loài người đã từng làm, còn những học giả
thì nhìn toàn bộ khung cảnh Cộng sản không hơn không kém như một sản phẩm sinh
ra trong thời kì Marx và Engels sống.
Các bản thảo của hai con người này rõ ràng phản ánh những cố gắng nghiên cứu để
hoà giải năm ảnh hưởng lớn nhất trong thế hệ của mình và họ đã cố gắng gộp chúng
lại thành một hình mẫu tư duy thống nhất. Dưới đây là những ảnh hưởng đã đánh
dấu nhận thức của Marx và Enges:

****

Thứ nhất:: _Sự thay đổi, biến động kinh tế dữ dội và đột ngột trong thời
kì của họ_. Điều này được tin rằng đã làm Marx và Engels quá nhạy cảm đặt vị trí
kinh tế trong bối cảnh lịch sử.

Thứ hai:: _Sự lan rộng, phổ biến của triết gia người Đức, Georg Wilhelm Hegel_.
Lý thuyết "`biện chứng`" của ông ta được Marx và Engels chấp nhận với một
chút thay đổi nhỏ để giải thích tất cả hiện tượng của tự nhiên, đấu tranh giai
cấp và chiến thắng chắc chắc xảy ra của xã hội vô sản tương lai.

Thứ ba:: _Chủ nghĩa hoài nghi bài tôn giáo của chủ nghĩa Duy vật thế kỉ 19._
Họ cố gắng giải thích tất cả vạn vật tồn tại dưới một yếu tố duy nhất: _vật chất_.
Họ phủ nhận một thiết kế siêu việt trong vũ trụ, sự tồn tại của Chúa, các vị thần
của tôn giáo, và các luân lý đạo đức răn dạy của Do Thái - Thiên Chúa giáo.

Thứ tư:: _Ý tưởng kinh tế xã hội của những người Cộng sản lý tưởng (Utopian Communism)._
Marx và Engels quyết định họ muốn có một xã hội cộng đồng, những nó phải là xã
hội được kiểm soát; do đó họ loại bỏ nguyên tắc anh em của những nhà cải cách lý
tưởng (Utopian) và tuyên bố chủ nghĩa Cộng sản chỉ có thể được thiết lập dưới
quyền lực độc tài.

Thứ năm:: _Tinh thần cách mạng của những kẻ vô chính phủ (Anarchists)_.
Marx và Engels hứa hẹn hai thứ hấp dẫn những kẻ vô chính phủ: sử dụng bạo lực
cách mạng để lật đổ quyền lực hiện thời, và cuối cùng tạo ra xã hội không giai
cấp, không nhà nước.

****

Sinh viên nghiên cứu chủ nghĩa Cộng sản sẽ tìm thấy năm ảnh hường này được thiết
kế trong một khối kết tụ rất rộng lớn, nó dường như được tạo ra để cho tất cả mọi
người.
