=== Phê bình Độc tài Vô sản

*Nguỵ biện 17*

Độc quyền về chính trị và quyền lực kinh tế được đưa ra với tham vọng mang lại
rất nhiều điều tốt đẹp cho nhân loại, nhưng trên kinh nghiệm thực tế những gì
diễn ra chỉ là ảo tưởng. Lấy ví dụ chế độ Độc tài vô sản hy vọng mang lại giàu
có cho dân chúng sau khi bãi bỏ tư hữu, dồn tất cả phương thức sản xuất vào chính
phủ. Tại sao họ muốn làm như vậy? Họ nói là để chống lại việc tài sản, của
cải rơi vào tay sở hữu tư bản. Nhưng cái gì xảy ra khi Cộng sản đã cố gắng thực
hiện tại Nga? Nó đã tiêu diệt bộ phận giàu có ít ỏi này, kéo ngược nền kinh tế
trở lại hướng đi của chế độ Phong kiến - hệ thống kinh tế bị chi phối bởi một số
cá nhân có đặc quyền, ban phát cho người dân nhu những cầu thiết yếu đời sống bằng
những quyết định tuỳ tiện bừa bãi, bắt người dân phải sống theo cách chúng muốn.

Hai con người điên rồ đã không phân biệt được sự khác nhau giữa _quyền sở hữu_
tài sản cá nhân và sự _lạm dụng_ tài sản cá nhân. Họ muốn thoát khỏi sự lạm dụng
bằng cách phá huỷ quyền sở hữu. Vấn đề của nhân loại không nằm ở chỗ quyền
sở hữu tài sản riêng, mà phải làm sao để mang đến công bằng các quyền về tài sản
cho dân chúng. Cộng sản đã không giải quyết được vấn đề vì thực tế đơn giản là họ
đưa tất cả tài sản trở lại sự giám sát của những kẻ làm thuê dưới chế độ độc
tài, vận hành hệ thống theo chiều hướng độc quyền tài sản chứ không rộng rãi phân
phối, đem hưởng thụ đến cho người dân.

*Nguỵ biện 18*

Mục đích của Độc tài Vô sản đối với người công nhân lao động là bù đắp lại thành quả
cho họ hơn là những gì họ nhận được từ tiền lương cơ bản. Với việc bãi bỏ tiền lương
thay bằng cơ chế chứng nhận lao động (labor certificate), những người lãnh đạo
Cộng sản đã từ bỏ phương thức trao đổi hiện hành cơ bản. Sau khi cách mạng Cộng
sản diễn ra tại Nga, mọi người đã nhận thấy rõ ý tưỏng kia đã kéo quốc gia này
trở lại hình thức trao đổi thời kì nguyên thuỷ, không cần dùng đến tiền.
Ý tưởng này thậm chí biến thành thảm hoạ, và nó đã bị bãi bỏ sau vài tháng thử
nghiệm. Cộng sản đã học được bài học quan trọng, vấn đế công bằng tiền lương không
thể giải quyết bằng cách bãi bỏ nó.

*Nguỵ biện 19*

Chế độ độc tài vô sản mang tham vọng cho phép mình tạo ra lực lượng quân đội
"`quốc phòng`" hùng mạnh với mục tiêu "`giải phóng`" những người vô sản ở tất
cả các quốc gia cho tới khi chế độ Độc tài bao trùm toàn bộ thế giới.

Nỗ lực che giấu này mục đích làm mờ đi tham vọng đế quốc của các nhà lãnh đạo Cộng
sản thèm khát chinh phục thế giới. Quân đội của họ luôn được mô tả là để "`phòng thủ`"
và nạn nhân của việc tấn công là cần được "`giải phóng`".
Lịch sử thế giới gần đây đã đưa ra bình luận bi thảm về vai trò giải phóng Cộng sản.

*Nguỵ biện 20*

Chế độ độc tài của giai cấp vô sản được chờ đợi sẽ cho các nhà lãnh đạo Cộng sản
có thêm thời gian chứng minh cho quần chúng thấy hiệu quả trong kế hoạch của họ,
đảm bảo sự thống nhất ủng hộ cho "`chế độ cộng sản toàn trị`" sớm được thực hiện.
Nhưng cộng sản độc tài ở Nga lại không có quyền lực để thuyết phục việc này.
Thực tế thì bạo lực, giận dữ trút lên đầu tầng lớp lao động, vô sản cũng giống hệt
như bạo lực được cho phép sử dụng chống lại giai cấp tư sản. Do vậy quần chúng
lúc đó suy giảm nhuệ khí và khá miễn cưỡng, sợ hãi hơn là "`đồng lòng ủng hộ`"
cho sự nghiệp Cộng sản.
