=== Phê bình giải thích xã hội của Cộng sản

*Nguỵ biện 3*

Đầu tiên Marx và Engels nói hình thái của xã hội được quyết định bởi các điều
kiện kinh tế, động cơ của tầng lớp thống trị trong từng giai đoạn cụ thể. Như
Marx viết: "`Con người có được tự do lựa chọn cho mình hình thái này hay hình
thái kia của xã hội hay không? Chắc chắn là không. Giả sử tại một giai đoạn phát
triển cụ thể lực lượng sản xuất của con người, chúng ta sẽ nhận được một hình
thái cụ thể của thương mại và tiêu dùng. Tại một giai đoạn phát triển
cụ thể của sản xuất, thương mại và tiêu dùng, chúng ta sẽ có một cấu trúc xã hội
tương ứng, một tổ chức gia đình tương ứng, một trật tự hay không giai cấp tương
ứng, nói một cách khác đó là một xã hội dân sự tương ứng. Giả định trong một xã
hội dân sự cụ thể, chúng nhận được những điều kiện chính trị cụ thể, nhưng đó chỉ
là biểu hiện chính thức của xã hội dân sự mà thôi.`"
footnote:[Karl Marx, Poverty of Philosophy, pp. 152-153]

Không thể tưởng tượng nổi làm sao Marx và Engels lại có thể cho phép những ao ước
thèm muốn này che đậy đi một thực tế của lịch sử, họ tự thuyết phục bản thân khi
cho rằng nếu một loại hình thức sản xuất xác định tồn tại thì cũng phải tồn tại
một kiểu xã hội xác định tương ứng. Từ thời kì cổ đại phương thức sản xuất vẫn
giữ nguyên hàng thế kỉ trong khi xã hội chạy suốt chiều dài lịch sử gần như liên
tục thay đổi. Các nhà sử học và kinh tế học đã chỉ ra lịch sử không minh chứng bất
kì điều gì thực tế cho thấy sự liên quan trực tiếp giữa phương thức sản xuất và hình
thái của xã hội chấp nhận nó. Chúng ta sẽ thấy tại sao ở phần tiếp theo.
