=== Phê bình Cộng sản toàn trị không giai cấp không nhà nước

*Nguỵ biện 21*

Giấc mơ Cộng sản về "`một thế giới`" vĩ đại tạo dựng dựa trên niềm tin rằng dưới chế
độ bạo lực, cưỡng chế của Độc tài vô sản sẽ cho phép thiết lập một xã hội sản sinh
ra trật tự mới, những con người có thói quen tuân theo cái mà Lenin gọi là:
"`những thứ luật lệ chung cơ bản trong cuộc sống xã hội thường ngày`".

Nguỵ biện của hy vọng này nằm ở chỗ chủ nghĩa Cộng sản đã cố tình diễn giải sai,
làm biến thái ý nghĩa nguồn gốc của hành vi cư xử con người. Dựa trên căn bản của
chủ nghĩa Duy vật biện chứng, nó cho rằng nếu như bạn thay đổi sự vật _bên ngoài_
con người, thì tự động bắt buộc có sự thay đổi _bên trong_ con người ấy. Không có
gì phải tranh cãi tồn tại quan hệ qua lại giữa môi trường bên trong và bên ngoài
tô điểm nên tính cách của con người, nhưng môi trường chỉ _tạo điều kiện_ chứ nó
không thay đổi _bản chất tự nhiên của anh ta_. Lấy ví dụ, đàn ông thường luôn
thích ăn uống, vui vẻ, tụ tập tán chuyện, họ sẽ luôn tận hưởng niềm vui được sở
hữu mọi thứ; họ sẽ luôn có khát vọng thể hiện bản thân hay chủ động quyết định
vấn đề, tham vọng cải thiện hoàn cảnh cá nhân và động lực vươn lên trên người khác.
Những phẩm chất này có sẵn trong mọi thế hệ và không thể bỏ qua hay luật pháp hoá.

Do đó bất kì hành vi cưỡng chế hay bạo lực nào sẽ không bao giờ phát triển thành
thói quen bền vững tuân theo cái gọi là
"`luật lệ chung cơ bản trong cuộc sống xã hội thường ngày`" nếu như cuộc sống xã
hội hàng ngày vi phạm bản chất tự nhiên của con người. Cho dù con người có bị đàn
áp như thế nào, thì với bản chất tự nhiên anh ta sẽ vẫn luôn ấp ủ nhiệt thành bản năng
được tự do bộc lộ khát vọng, mong muốn - những thứ được kế thừa trong anh ta chứ
không phải thứ anh ta có được bằng chiếm đoạt. Đó là lý do tại sao khát vọng đam
mê không thể bị phớt lờ, không thể bị huỷ diệt mặc dù bị đàn áp tàn bạo dưới
chế độ quân đội Độc tài vô sản. Chắc chắn họ sẽ đứng dậy khẳng định mình bất kì
lúc nào một khi cái chế độ kia có dấu hiệu suy yếu.

Sáu mươi thế kỉ lịch sử trải qua đã minh chứng một điều rõ ràng xã hội thành công
chỉ khi nó hài hoà và thuận theo bản năng tự nhiên của con người. Trên thực tế
chủ nghĩa Cộng sản lại cố gắng xoá bỏ đi những bản chất tự nhiên của con người,
những điều cơ bản nhất như nguồn gốc của sự hài lòng, hay sức mạnh của hạnh phúc
dẫn đến tiến bộ cho toàn thể xã hội.

*Nguỵ biện 22*

Marx và Engels quá lo lắng tập trung vào việc hạ thấp chủ nghĩa tư bản, dành phần
lớn thời gian vào những việc cụ thể đó mà chưa bao giờ vạch ra được hình mẫu hoàn
chỉnh của "`chế độ Cộng sản toàn trị`" thay thế cho chủ nghĩa tư bản; trong lúc
đó thì chúng ta lại có đủ thông tin phơi bày những yếu kém bẩm sinh từ một
trong những tiên đề: "`làm theo năng lực hưởng theo nhu cầu`".

Có lẽ nghe thì rất tuyệt vời đối với những người tàn tật, bởi vì xã hội sẵn sàng
bù đắp cho những người tàn tật khi họ mất đi khả năng tự chăm sóc bản thân.
Nhưng nếu áp dụng cho toàn bộ xã hội thì điều gì sẽ xảy ra? Gần đây có một giáo
viên hỏi các học sinh của anh ta xem họ nghĩ thế nào về khẩu hiệu này của Cộng
sản và các học sinh có vẻ như nghĩ rằng không có vấn đề gì. Giáo viên này đưa
ra một ví dụ nhỏ để xem nếu áp dụng phương châm Cộng sản này vào trường học thì
sẽ như thế nào. Anh ta nói:

"`Để vượt qua bài kiểm tra trong lớp, các bạn phải đạt ít nhât 75 điểm. Nếu ai đạt 95 điểm tôi sẽ lấy 20 điểm và cho các bạn chỉ được 55 điểm. Nếu bạn nào đạt 90 điểm tôi sẽ lấy đi 15 điểm và cho bạn chỉ có 60 điểm. Và như vậy thì tất cả mọi người sẽ đều vượt qua bài kiểm tra.`"

Ngay lập tức cơn bão phản đối từ những học sinh thông minh chăm chỉ, và chỉ những
học sinh lười nhác mới nghĩ rằng đó là ý tưởng hay. Cuối cùng thì giáo viên cũng
giải thích:

"`Về lâu dài tôi không nghĩ các bạn sẽ thích hệ thống giống thế này, và sau đây là những việc tất yếu sẽ xảy ra. Thứ nhất, những học sinh giỏi, những người có năng suất lao động cao luôn chiếm số ít trong chúng ta, họ sẽ mất đi động lực để làm việc. Tại sao họ lại phải phấn đấu đạt được điểm cao nhất để rồi bị lấy mất một phần đi, đem cho người khác bởi những người _có quyền_? Thứ hai, những học sinh kém hơn chiếm số đông tại các trường học sẽ yên vị tận hưởng mà không cần học hay làm việc. Việc này sẽ không dừng lại cho tới khi người có hiệu suất làm việc cao bị kéo xuống tới mức thấp giống như những người hiệu suất kém và lúc đó thì chẳng có gì đóng góp cho những kẻ ăn bám xung quanh. Tới lúc này, để tất cả cùng sống sót thì bắt buộc kẻ _cầm quyền_  không còn cách nào khác là phải tạo ra hệ thống cưỡng chế lao động, trừng phạt những kẻ làm việc hiệu suất thấp. Và họ tất nhiên sẽ phàn nàn khó chịu mà không hiểu chuyện gì đang xảy ra.`"
footnote:[Related by Thomas J. Shelly, instructor in Economics and History, Yonkers High School, Yonkers, New York]

Đối với chủ nghĩa Cộng sản, sự cần thiết của "`chính quyền`" đơn giản là quay
trở về chế độ Độc tài vô sản ép buộc tất cả công nhân phải làm ra nhiều hơn nhu
cầu cần thiết. Nhưng ngay cả khi dùng vũ lực ép buộc, Độc tài vô sản cũng vẫn
thất bại khi bắt ép công nhân lao động làm việc hết công suất trong khả năng của
họ. Như chỉ ra ở ví dụ trên, chủ nghĩa Cộng sản đã phá huỷ một cách có chủ đích
động lực làm việc bình thường nhất của con người, cụ thể ở bốn điểm sau:

. Tăng thu nhập khi tăng sản lượng
. Tăng thu nhập cho những người làm việc chăm chỉ, phát triển cải tiến sản phẩm
. Tăng thu nhập cho những người làm việc chăm chỉ mang đến cải tiến chất lượng dịch vụ.
. Quyền của người công nhân lao động được mua bán tài sản theo nhu cầu tiêu dùng
dựa trên tích lũy có được từ thu nhập (lợi nhuận) để cải thiện hoàn cảnh sống của
bản thân cũng như chính gia đình họ.

Các nhà lãnh đạo Cộng sản dường như đã hiểu lầm bài học phổ cập trong cuộc sống,
kẻ thù lớn nhất của con người chính là sự an phận lười biếng và lý do chính để
hành động chống lại sự an phận lười nhác không phải vũ lực ép buộc, mà phải
tạo ra cơ hội để tự cải tiến bản thân. Marx và Engels đều nhấn mạnh rằng
thái độ lười biếng là ích kỉ, là "`phản xã hội`", nhưng thực tế thô thiển lại cho
thấy những người công nhân gặp nhiều khó khăn mặc dù làm việc rất chăm chỉ để lấp
đầy cái bụng trống rỗng tham lam của "`xã hội`", trong khi đáng lẽ thành quả lao
động của họ phải phục vụ cho họ và gia đình trước tiên.

Những người Cộng sản nghĩ dùng vũ lực có thể quét sạch những thái độ "`phản xã hội`"
kia, nhưng trong suốt 35 năm dưới Độc tài ở Nga đã minh chứng sống động con người
sẽ không làm việc theo khả năng của họ trừ khi họ được đền bù xứng đáng theo năng lực.
Lãnh đạo Cộng sản biết vũ lực đã thất bại, dưới roi vọt của Độc tài công nhân lao
động hầu như không làm ra đủ để sống sót, do đó lãnh đạo Cộng sản nhấn mạnh chế
độ Độc tài phải tiếp tục vô thời hạn.
Trong thời gian dài công nhân không theo làm năng lực của họ và vì vậy chắc chắn
không thể nói gì về xã hội "`Cộng sản toàn trị`" lúc này, nơi mà con người sẽ được
hưởng thụ theo nhu cầu.

*Nguỵ biện 23*

Những sinh viên nghiên cứu lý thuyết Marx và Engels sớm nhận ra hai con người này
đã thất bại khi cân nhắc một số yếu tố thực tế cơ bản nhất trong cuộc sống.
Ví dụ, họ cho rằng mô hình xã hội không nhà nước quyền lực toàn dân (mass-rule và
thường sẽ biến thái thành quyền lực của đám vô lại: mob-rule) sẽ chính trực và
sáng suốt hơn mô hình chính phủ tổ chức tam quyền phân lập bao gồm cơ quan hành
pháp, tư pháp và lập pháp. Việc thiết lập nên xã hội kiểu này theo kì vọng của
Cộng sản toàn trị khác nào đi ngược lại kinh nghiệm của loài người đã từng trải
qua trong lịch sử nhân loại.

*Nguỵ biện 24*

Lý thuyết này cũng cho rằng dưới đàn áp cưỡng chế của Độc tài vô sản, bản năng
chiếm hữu, thâu tóm của con người sẽ bị mất đi hoặc bị bóp nghẹt hoàn toàn. Marx
và Engels khẳng định rõ ràng họ kỳ vọng chế độ Độc tài sẽ ép buộc con người phải
từ bỏ "`thói quen`" sở hữu tài sản hay nhu cầu ham muốn sở hữu.

Hãy thử tưởng tượng điều gì sẽ xảy ra khi một thế hệ mới sinh ra lớn lên trong
một xã hội không có nhà nước và thế hệ này chẳng có chút ý niệm nào về sự bức hại
không thương tiếc mà ông cha họ đã từng chịu đựng, bị ép buộc phải hình thành thói
quen vâng lời, tuân theo cái gọi là "`quy tắc, luật lệ chung cơ bản hàng ngày`"?
Giả sử một số lượng lớn con người của thế hệ mới này từ chối làm việc, hoặc từ chối
chia sẻ những công việc được chỉ định và họ bị kết tội "`không làm việc theo năng lực`"?
Hoặc những con người của thế mới đòi hỏi từ xã hội không giai cấp, không nhà nhà
nước nhiều hơn những gì họ được chia phần?

Cái gì sẽ xảy ra tiếp theo nếu như những con người mới này tổ chức lại, âm thầm
trang bị vũ khí, và bất ngờ nổi dậy chiếm lấy của cải mà cái xã hội không giai cấp
kia đã từ chối cho họ? Sẽ không cần phải thiết lập chế độ Độc tài vô sản một lần nữa
để đàn áp những con người mới này chứ? Có lẽ bản năng thâu tóm, chiếm hữu của con
người khó bị đàn áp hơn những gì mà Marx hay Engels nghĩ.
Trên thực tế với kiến thức của chúng ta thu được về hành vi của con người trải qua
hàng ngàn năm lịch sử thì liệu chủ nghĩa Cộng sản có khả năng sẽ vượt qua chế độ Độc
tài của giai cấp vô sản hay không?

*Nguỵ biện 25*

Chủ nghĩa Cộng sản toàn trị hứa hẹn rằng dưới chế độ xã hội không giai cấp, không
nhà nước, lượng hàng hoá sản xuất sẽ nhiều hơn những gì mà xã hội hiện tại đang
làm ra kể cả khi không có những thứ tạo ra động lực, khuyến khích làm việc như
tiền thưởng. Theo lý thuyết này thì mục đích sản xuất Cộng sản là sẽ đạt tới ngưỡng
bão hoà tuyệt đối, lúc đó tất cả mọi nhu cầu của con người sẽ được thoả mãn.
Hàng hoá cung cấp sẽ được chất đống, phân phối theo nhu cầu của từng cá thể. Các
dịch vụ đi kèm cũng sẵn sàng tại những trung tâm hàng hoá với chất lượng được
đảm bảo tốt nhất, người tiêu dùng sẽ không bận tâm về chuyện cạnh tranh dịch vụ
hay chất lượng. Và do đó chủ nghĩa Cộng sản hứa hẹn loại bỏ đi những thứ đang tồn
tại như thị trường, tiền tệ và giá cả.

Vậy điều gì xảy ra nếu như mục đích của bão hoà tuyệt đối không đạt được? Liệu
chế độ Độc tài vô sản sẽ phải hành động một lần nữa để đàn áp sự không hài lòng
này? Một ví dụ dễ hiểu cho vấn đề này đối với trường hợp sản xuất ô tô.
Cần sản xuất bao nhiêu ô tô để đạt được trạng thái bão hoà tuyệt đối thoả mãn nhu
cầu cho 2 tỷ con người trên trái đất? Dưới chế độ tư bản chủ nghĩa, mỗi gia đình
cảm thấy thoả mãn với một hoặc hai chiếc xe là đủ cho nhu cầu, phù hợp với điều
kiện chi trả kinh tế. Sẽ như thế nào nếu như yếu tố điều kiện chi trả kinh tế của
gia đình bị loại bỏ? Dưới chế độ Cộng sản toàn trị, một người công nhân tốt sẽ
được cho phép lấy tất cả những chiếc xe ô tô mà anh ta muốn. Và nếu như không lấy
được những gì mình muốn thì bản tính ích kỷ xấu xí sẽ ngay lập tức biểu hiện ra
ngoài. Những bài viết lặp lại nhiều lần của Cộng sản hứa hẹn với sự sản xuất no
đủ sẽ giúp loại bỏ đi lòng tham lam ích kỷ, nguyên nhân dẫn tới đấu tranh giai
cấp.

Và điều gì xảy ra khi những mẫu xe ô tô mới ra đời? Xã hội sẽ tự động loại bỏ tất
cả những chiếc xe mỗi lần mẫu mới được phát triển? Dưới chế độ Cộng sản toàn trị
thì ai là người muốn một chiếc xe cũ? Điều này có vẻ vô lý nhưng thực tế thì nó
lại là vấn đề phổ biến nhất, phát sinh liên quan đến tất cả các loại hình sản
xuất. Ai đó sẽ phải quyết định xem người nào sẽ phải giữ lại chiếc xe của họ thêm
một hay hai năm nữa, vì nếu không thì tất cả các gia đình chắc chắn sẽ đòi hỏi
một chiếc xe mới, thậm chí có thể yêu cầu vài chiếc mới.

Những vấn đề kiểu như thế này dưới hệ thống Cộng sản toàn trị rõ ràng là nhiều
vô số không thể liệt kê hết. Mọi hy vọng loại bỏ tiền tệ, thị trường và giá cả
dần chìm vào quên lãng. Một hệ thống toàn trị như vậy cũng đòi hỏi bộ máy chính
phủ rất cồng kềnh gấp nhiều lần so với cơ chế tự do doanh nghiệp của chủ nghĩa
tư bản. Và viễn cảnh sản xuất hàng hoá dịch vụ với số lượng lớn sẽ khiến nhà nước
có thể "`chết yểu`" bất kể là do nguyên nhân gì hay những kinh nghiệm đã có.
