=== Phê bình Diễn giải Lịch sử của chủ nghĩa Cộng sản

*Nguỵ biện 1*

Nguỵ biện đầu tiên của chủ nghĩa Cộng sản đó là cố gắng đơn giản hoá lịch sử.
Marx và Engels đã sử dụng một tiêu chí duy nhất, đơn giản đó là "`kinh tế`" để
thay đổi dòng chảy của lịch sử sinh sống loài người có từ hàng triệu năm,
ép chặt vào một con đường phát triển cố định, cứng nhắc, không thể lay chuyển,
có thể vẽ lại được quá khứ và dự đoán trước tương lai.
Tất nhiên kinh tế đóng một vai trò mạnh mẽ sống còn trong lịch
sử nhân loại, những cũng còn có rất nhiều các yếu tố cấu thành khác quan trọng
không kém như: khí hậu, sự phân bố tự nhiên và các đặc điểm vật lý nhân tạo, tiếp
cận nguồn nước, phát minh cơ học, khám phá khoa học, quan hệ quốc gia và chủng tộc,
lòng hiếu thảo trong gia đình, tôn giáo, khao khát phiêu lưu mạo hiểm, cảm xúc
của lòng trung thành và tình yêu tổ quốc.

Một số người Cộng sản thừa nhận lịch sử được đúc kết từ những ảnh hưởng khác nhau,
nhưng họ nhấn mạnh rằng Marx và Engels có chủ ý muốn gộp toàn bộ những ảnh hưởng
đó trong khái niệm _Kinh tế Định hướng_ của họ, bởi vì họ cho rằng tất cả những
thứ này ảnh hưởng trực tiếp hoặc gián tiếp tới đời sống kinh tế của nhân loại.
Tuy vậy thì những tác phẩm của Marx và Engels lạ thất bại khi phản ánh những diễn
giải này. Mà giả sử có lý giải thành công đi chăng nữa thì những người Marxist
hiện đại vẫn gặp khó bởi vì công thức diễn giải lịch sử của Cộng sản sẽ được hiểu
thành là: "`Mọi thứ quyết định tất cả`" dựa trên chính định nghĩa của họ - _Kinh tế
Định hướng_ ảnh hưởng đến toàn bộ đời sống nhân loại.
Đây chính là sự vô lý của cơ sở diễn giải lịch sử.

Một nhóm người Cộng sản khác cố gắng giải thoát Marx và Engels khỏi biên giới hạn
hẹp của khái niệm _Kinh tế Định hướng_ bằng cách đưa ra đề xuât rằng hoàn cảnh kinh tế
không hoàn toàn quyết định con đường đi của nhân loại, nó đơn thuần chỉ tạo điều
kiện cho con người bước tiếp sau khi hình thành một xu hướng cụ thể trong phát
triển xã hội. footnote:[See Shirokov-Mosley, ATextbook of Marxism, p. 22]
Mặc dù đề xuất này đã tiến gần hơn đến sự thật, những mặt khác thì nó lại giả định
yếu tố biến đổi của ý chí tự do góp phần tạo lập nên lịch sử, và điều này thì
lại bị Marx và Engels dứt khoát phủ nhận.
Thực tế thì khái niệm _Kinh tế Định hướng_ với nghĩa tuyệt đối, cố định và không
thể lay chuyển là nền tảng để Marx và Engels dự đoán về một xã hội phải đi theo
con đường phát triển chắc chắn diễn ra từ chủ nghĩa Tư bản đi lên chủ nghĩa Xã hội,
và từ chủ nghĩa Xã hội tiến lên chủ nghĩa Cộng sản. Đây chính là lý gỉải cho câu
nói của họ về chủ nghĩa Tư bản: "`Sự sụp đổ của họ và chiến thẳng của người vô sản
là không thể tránh khỏi như nhau.`" footnote:[Marx-Engels, Communist Manifesto, p. 29]

Hơn nữa, khi bất kì người Cộng sản nào cố gắng tranh cãi con đường phát triển
nhân loại không cố định và không thể tránh khỏi, thì anh ta đã phá huỷ hoàn toàn
nguyên tắc biện luận của Cách mạng Cộng sản: bùng phát bạo lực là "`cách đơn giản,
ngắn gọn, tập trung thẳng vào cái chết đau đớn của xã hội cũ`" - Marx nói.
footnote:[Karl Marx, quoted by J.E. LeRossignol in From Marx to Stalin, p. 321]
Một xã hội cũ kỹ trên thực tế chắc chắn sẽ chết, nên không cần phải hối tiếc,
xin lỗi, bào chữa gì về việc sử dụng bạo lực cho cái chết đó. Đây là lập luận
tranh cãi chủ chốt lý giải cho việc sử dụng bạo lực của Marx. Những lời biện
minh cho cuộc cách mạng sẽ bắt đầu mất đi sức mạnh nếu như cái chết của xã hội
cũ được thừa nhận chỉ như là một trong những khả năng xảy ra để tiến lên chủ nghĩa
Cộng sản mà thôi chứ không phải là không thể tránh khỏi. Hay nói một cách khác,
những lời biện hộ sẽ thành rác rưởi nếu như xã hội hiện tại không chết đi, mà thực
tế phát triển mạnh mẽ hơn trước qua từng thế hệ, đóng góp phúc lợi nhiều hơn cho
con người.

Những gì Cộng sản diễn giải về lịch sử trên cơ bản của khái niệm _Kinh tế Định
hướng_ cho thấy nó rất yếu và mong manh dễ vỡ ngay cả khi được đặt trong tay
chính những người bảo vệ nó. Các môn đồ của Marx sớm nhận ra sự yếu kém này, và
cố gắng vá nó lại, nhưng những miếng vá chỉ càng tạo thêm vết rạn mới trên bộ dạng
yếu đuối thân xác khô gầy của logic Cộng sản.

*Nguỵ biện 2*

Marx và Engels không chỉ đơn giản hoá lịch sử, mà họ còn dựa nguỵ biện thứ hai
để biện minh cho nguỵ biện thứ nhất. Họ nói rằng nhận thức của con người không
có khả năng đạo đức, tự do ý chí với hàm ý rằng con người không có khả năng lựa
chọn hướng đi cho con đường lịch sử, mà hoàn cảnh vật chất sẽ ép buộc nhận thức
con người, thúc đẩy theo một hướng xác định và con người không có tự do ý chí
cưỡng lại việc đó.

Điều này nghe như những thứ được giảng dạy của các nhà duy vật cơ học thế kỷ 19
khi tuyên bố rằng bộ não của con người giống như những chiếc bảng tính sáp, chỉ
biết thụ động nhận thông tin từ thế giới bên ngoài và tự động phản ứng
lại thông tin đó; nhưng Marx và Engels không muốn trường phái tư tưởng này được
hiểu như vậy, do đó họ nói những nhà duy vật "`bình dân`" này đã mắc lỗi.
Bộ não không hề thụ động giống như chiếc bảng tính sáp, mà nó là cơ thể sống, nó
không chỉ tiếp nhận thông tin, mà còn có khả năng xử lý thông qua quá trình tổng
hợp và phân tích. Và bây giờ thì câu chuyện hài bắt đầu được kể.

Họ tuyên bố sau khi bộ não xử lý thông tin từ thế giới bên ngoài, nó sẽ luôn luôn
quyết định làm _tất cả những gì cần thiết để bảo vệ giữ gìn, duy trì chủ thể dưới
ánh sáng soi đường của hoàn cảnh vật chất._ Bằng cách diễn giải khôn khéo tinh vi
như thế này, họ đã muốn khẳng định một cách đơn giản rằng: con người là nạn nhân
của môi trường vật chất thực dụng của chính anh ta. Ở điểm này chỉ có một chút
nhỏ khác biệt trong lối suy nghĩ, họ đã đi đến những kết luận chính xác, giống hệt những nhà duy vật cơ học "`bình dân`" - những người họ đã phủ nhận.

Nhắc lại một chút từ chương trước, Marx và Engels nhận định khái niệm mà chúng
ta gọi là "`tự do ý chí - free will`" không hơn không kém gì sự ý thức, nhận ra
các lực lượng vật chất thực dụng đang tác động lên chủ thế, thúc giục chủ thể
hành động. Việc nhận thức một cách "`cần thiết tự nhiên`" này làm cho con người
có cảm giác rằng họ đang lựa chọn cách hành động cho mình, nhưng thực tế thì họ
chỉ đang ngắm nhìn bản thân mình bị cuốn theo hoàn cảnh vật chất đang dẫn động họ.

Một lần nữa chúng ta thấy Marx và Engels lại đơn giản hoá mọi thứ. Sự phức tạp
của hành vi con người không thể được giải thích đơn giản dưới khái niệm "`cần thiết`"
phản ứng lại hoàn cảnh vật chất thực dụng. Rất thường xuyên con người từ chối hoàn
cảnh vật chất thực dụng để thoả mãn động cơ của mình, ví dụ như: khát khao tự biểu
đạt cá nhân, sức mạnh thúc đẩy của niềm tin tôn giáo, dẫn động của trách nhiệm đạo
đức, sự kiêu ngạo của bản thân, hay hiện thực hoá tham vọng cá nhân.

Nguỵ biện này chối bỏ việc nhận ra sự ảnh hưởng của đạo đức con người cũng như sức
mạnh để quyết định việc lựa chọn cá nhân. Đây chính là tử huyệt của chủ nghĩa
Marxist, lỗi xuất phát điểm cho những nguỵ biện khác được phát triển lên từ đây.
Những tuyên bố của chủ nghĩa Cộng sản về lập luận nhận thức cần phải được chứng
minh bằng cách ví dụ, chúng ta sẽ xem xét những nguỵ biện này được cấu thành như
thế nào khi Marx và Engels nỗ lực sử dụng nó để giải thích về các cấu trúc xã hội.
