=== Phê bình cách tiếp cận tiêu cực giải quyết vấn đề của CNCS

Để kết thúc thảo luận về những nguỵ biện cơ bản của chủ nghĩa Cộng sản chúng
có lẽ nên làm một tóm tắt bình luận về nguỵ biện quan trọng nhất trong tất cả những
nguỵ biện. Đây chính là học thuyết Cộng sản, mọi vấn đề có thể được giải quyết
bằng cách loại bỏ nguồn gốc khởi đầu của vấn đề, nơi vấn đề được hình thành nên.
Thậm chí Marx và Engels có thể không nhận ra điều này, nhưng các sinh viên sẽ ghi
chú lại làm thế nào cách tiếp cận này lại hoàn toàn thống trị toàn bộ những vấn
đề mà Marx cùng với Engels gánh vác trách nhiệm giải quyết.

Lấy ví dụ, các vấn đề của chính phủ. Marx và Engels sẽ giải quyết những vấn đề
này bằng cách làm việc cho đến ngày khi họ có thể loại bỏ chính phủ.
Các vấn đề về đạo đức sẽ được giải quyết bằng cách loại bỏ đạo đức.
Các vấn đề phát triển từ tôn giáo sẽ được giải quyết bằng cách loại bỏ tôn giáo.
Các vấn đề về hôn nhân, nhà cửa và gia đình sẽ được loại bỏ bằng cách loại bỏ
hôn nhân, nhà cửa và gia đình.

Những vấn đề phát sinh ra từ quyền sở hữu tài sản sẽ được giải quyết bằng cách
không cho phép bất kì ai có quyền sở hữu tài sản. Vấn đề bình đẳng lương thu nhập
sẽ được giải quyết bằng cách phá bỏ cơ chế tiền lương. Vấn đề gắn kết với tiền
tệ, thị trường và giá cả sẽ được giải quyết bằng cách loại bỏ tiền tệ, thị
trường và giá cả. Vấn đề cạnh tranh sản xuất và phân phối sẽ được giải quyết
bằng cách dùng vũ lực cấm đoán cạnh tranh.

Cuối cùng những người Cộng sản sẽ giải quyết được tất cả vấn đề của xã hội hiện
đại bằng cách sử dụng bạo lực cách mạng để phá huỷ xã hội hiện tại. Có vẻ như bóng
ma hy vọng của Cộng sản chỉ có thể lớn lên từ đám tro tàn cát bụi trên trái đất
này. Chủ nghĩa Cộng sản phải được xây dựng cho một mục đích - tiêu diệt, phá huỷ.
Chỉ sau khi xảy ra sự huỷ diệt mang tính vĩ mô, những người lãnh đạo Cộng sản mới
dám hy vọng rằng lúc đó họ có thể cho phép môn đồ của mình khả năng có được
sự tự do, bình đẳng và công lý.

Và đây chính là những lời hứa viển vông mơ hồ, u ám về tương lai mà chủ nghĩa
Cộng sản đưa ra cho thế giới ngày nay. Trong lúc đợi chờ ngày tươi sáng trở thành
hiện thực, lãnh đạo Cộng sản yêu cầu nhân loại cam chịu đại thảm hoạ gây ra
từ những cuộc bạo lực cách mạng, đàn áp thanh trừng các nhóm đối lập, tịch thu trưng
dụng của cải tài sản vô tội vạ. Chế độ Độc tài vô sản mô tả những việc như thế
này được "`dựa trên vũ lực và được luật pháp cho phép`", đàn áp tất cả tự do dân
sự: tự do báo chí, tự do ngôn luận và thành lập nhóm hội, thiết lập trại lao động
khổ sai, sử dụng cảnh sát chìm thường xuyên giám sát người dân, bắt buộc đi nghĩa
vụ quân sự dài hạn, nghèo đói không hiệu quả của cách làm nông nghiệp tập thể,
rủi ro lo sợ bị thanh trừng nếu bị phát hiện có biểu hiện lệch lạc, và cuối cùng
thì khả năng chịu đựng của trật tự kinh tế hứa hẹn một điều chắc chắn sẽ không đủ
tự cung cấp nhu cầu cuộc sống thiết yếu cho những thế hệ sau này.

Hơn bốn mươi năm đã đến và đi kể từ khi các nhà lãnh đạo Cộng sản lần đầu tiên
chiếm giữ được một quốc gia, chứng minh cho thế giới tò mò thấy những điều kỳ
diệu dị thường có thể được xây dựng nên. Từ một quốc gia họ đã mở rộng gọng kìm
cho tới khi một phần ba nhân loại đang phải cúi đầu trước những mệnh lệnh, nguyên
tắc cứng rắn đanh thép của họ. Những ai thoát khỏi chế độ chuyên chế đều mang theo
mình bằng chứng, hình ảnh ghê rợn của con người Marxist, những người đã sản sinh
ra một loại quái vật chính trị tàn ác, chứa đựng tất cả những thứ dị hợm kinh tởm
thu lượm được từ mọi hình thức thực tế tra tấn và hạ nhục con người, phát minh ra
kể từ buổi bình minh sơ khai của lịch sử nhân loại.

Trong khi giả vờ giải phóng nhân loại khỏi áp bức của chủ nghĩa tư bản, thì người
Marxist đã từ chối sự nồng hậu, khai sáng của nền văn minh thế kỷ 20, trái lại họ
đã mang đến hình thức nô lệ mới trên quy mô lớn chưa từng có của lịch sử loài người.
Trong khi tuyên bố thúc đẩy "`quyền của dân thường`", người Marxist
đã tàn sát đồng bào mình từ link:++https://en.wikipedia.org/wiki/Kulak[Kulak] cho
tới quý tộc với một số lượng lớn khó hiểu. Và trong khi tự miêu tả bản thân như
một tạo hoá hoàn hảo, mẫu mực của tự nhiên - sinh vật của khoa học, trí tuệ tối
thượng của vũ trụ, chủng người Marxist đã khai thác sự xảo trá của mình để pha
trộn thêm vào tội ác, những chủng người mà chúng ta cực kì hiếm gặp từ trước đến
nay, kể cả các bộ lạc săn mồi hung bạo nhất trong thời kì tiền lịch sử.

Chính vì những lý do này những người có nhận thức mô tả chủ nghĩa Cộng sản đã đảo
ngược và phủ nhận lại lịch sử. Nó đã biến người khác chống lại chính nó. Thay vì
giải quyết các vấn đề phức tạp của xã hội hiện đại, cách tiếp cận tiêu cực của
chủ nghĩa Marx đơn thuẩn chỉ làm sống lại những vấn đề nguyên thuỷ mà các thế hệ
trước đây đã giải quyết thành công thông qua đấu tranh nhân loại.

Để đánh giá đầy đủ, chính xác hơn những gì đã xảy ra, bây giờ chúng ta sẽ xem xét
đến các tình huống dẫn tới sự ra đời của quốc gia đầu tiên do Cộng sản kiểm soát
trong lịch sử thế giới.
