=== Phê bình nguồn gốc Nhà nước

*Nguỵ biện 4*

Marx và Engels đều tin rằng Nhà nước (dưới bất kì hình thức chính phủ có chủ có
chủ quyền nào) là cục thịt thừa của xã hội, do tầng lớp cai trị tạo ra chỉ để
bảo về lợi ích và đàn áp tầng lớp bị bóc lột nổi dậy. Họ không tin bất kì một
chính phủ nào đại diện cho lợi ích toàn bộ mọi người, hay thậm chí cả phúc lợi
cho phần đông dân chúng. Trong tuyên ngôn Cộng sản họ nói: "`Những kẻ điều hành
Nhà nước hiện đại là một Uỷ ban hội đồng quản lý công việc chung cho tất cả bọn
tư sản(tầng lớp sử hữu tài sản).`"
footnote:[Marx-Engels, Communist Manifesto, p. 15]

Những nhà xã hội học, tâm lý học, lịch sử gia và nhà khoa học chính trị chỉ ra
hoàn toàn sai khi coi chính phủ như là phần phụ loại bỏ đi của xã hội, trái lại
chính phủ chính là trái tim của cộng đồng sống. Xã hội sẽ không thể tồn tại nếu
như không được quản lý dưới một mức độ nào đó của chính quyền, sự xuất hiện của
chính quyền trong xã hội cấu thành nên cái gọi là "`chính phủ`". Con người tự
nhiên đã là xã hội, chính trị, sự hình thành chính phủ dẫn dắt tất cả các thành
viên trong cộng đồng hướng đến phúc lợi chung đơn thuần là biểu hiện vốn dĩ rất
tự nhiên của con người. Do đó một xã hội không có nhà nước (hay một nền văn minh
không có chính phủ) Max và Engels công khai mạnh mẽ ủng hộ đó sẽ là những đám đông
hạ lưu, vô tổ chức, thích gây sự và ưa bạo lực. _Và lúc đó sẽ không có xã hội nào cả_

*Nguỵ biện 5*

Marx và Engels cũng gặp phải khó khăn khi giải thích hình thức của một Nhà nước
chắc chắn được hình thành từ một số hình thức hoàn cảnh kinh tế cụ thể. Nếu như
điều này là đúng thì phương thức sản xuất giống như vậy sẽ luôn sản sinh ra một
hình thức cơ bản của chính phủ. Hãy thử nhìn lại lịch sử của Hy Lạp và Rome cổ
đại, trong cả hai quốc gia này phương thức sản xuất đều là chế độ nô lệ. Theo
lý giải của Marx thì hình thức của những chính phủ này phải còn tồn tại trong
khi phương thức sản xuất(chế độ nô lệ) vẫn còn đang hiệu quả.

Nhưng trái ngược với những mong đợi như lý thuyết của Marx, những chính phủ này
đã trải qua rất nhiều thay đổi mặc dù phương thức sản xuất - nô lệ không thay
đổi gì cả. Ở thủ đô Athen - Hy Lạp, có một loạt chế độ quân chủ nối nghiệp, theo
sau là nền cộng hoà của quý tộc và những người dân chủ, tiếp sau đó là chế độ
độc tài chuyên chế của ba mươi lãnh chúa, và cuối cùng là một nền dân chủ được
tái thiết thêm một lần nữa.
Tại Rome đã có hoàng gia đầu tiên được bầu chọn, tiếp theo là nền cộng hoà của
quý tộc cùng những người dân chủ, và sau đó trở thành chế độ quân chủ tuyệt đối
dưới thời Ceasars.
Đây là những sự kiện điển hình trong lịch sự cho thấy rằng hình thức chính phủ
thay đổi nhưng phương thức sản xuất thì vẫn giữ nguyên.

Bây giờ chúng ta minh hoạ nguỵ biện lý thuyết này của Cộng sản theo một cách khác.
Nếu như hình thức Nhà nước được cố định bởi _Kinh tế Định hướng_, vậy thì hình thức
của Nhà nước sẽ thay đổi khi phương thức sản xuất thay đổi. Tuy nhiên điều này
hầu như không xảy ra. Lấy lịch sử của Hoa Kỳ làm ví dụ. Hình thức của chính phủ
Hoa Kỳ về cơ bản là giữ nguyên giống như từ lúc được thiết lập:

"`Chính phủ của nền kinh tế nô lệ ở phía Nam có khác gì chính phủ của nền công
nghiệp ở phía Bắc? Chính phủ ở miền Nam có thay đổi gì không khi mà chế độ nô lệ
được bãi bỏ?`"

Phương thức sản xuất thay đổi, nhưng chính phủ không thay đổi. Hay nói một cách
khác, con người có thể tạo ra bất kì hình thức chính phủ nào họ muốn mà không cần
tham khảo phương thức sản xuất đang chiếm ưu thế. Có rất nhiều ví dụ lịch sử khác
phủ nhận rõ ràng khái niệm quan trọng này của Cộng sản.

*Nguỵ biện 6*

Liên quan đến sự hình thành của Nhà nước, Cộng sản vẫn bảo trì quan điểm rằng
các quy chuẩn luật pháp (code of law) được tạo ra để bảo vệ tầng lớp bóc lột;
tiếp theo là nếu như phương thức sản xuất thay đổi, quy chuẩn luật pháp sẽ phải
được cải tổ lại để khuyến khích phương thức sản xuất cụ thể mới. Một cách logic
điều này sẽ được hiểu: nếu như có cuộc cách mạng thay đổi phương thức sản xuất,
thì sẽ phải có cuộc cách mạng thay đổi hệ thống luật pháp. Sẽ không có mẫu quy
chuẩn luật pháp nào giống nhau có thể vận hành quốc gia dưới các phương thức sản
xuất khác nhau.

Một lần nữa lịch sử cho thấy lý thuyết của chủ nghĩa Cộng sản có nhiều mơ hồ khi
nó được áp dụng  vào một số tình huống cụ thể. Một ví dụ thuyết phục của lịch sử
Thế giới Phương Tây, nơi những nhà cách mạng thay đổi phương thức sản xuất thường
xuyên mà chỉ cần điều chỉnh một chút không đáng kể các quy chuẩn luật pháp phong
phú của họ. Xã hội tư bản hiện đại từ châu Âu đến Mỹ nhìn chung được quản lý bởi
những quy chuẩn luật pháp được thiết lập dựa trên nguyên tắc cơ bản thịnh hành
hàng thế kỉ trước khi Cách mạng Công nghiệp nổ ra.
Tại nước Anh, Luật Chung (Common Law) được phát triển suốt thời kì kinh tế phong
kiến, việc bãi bỏ chế độ phong kiến chỉ làm cho Luật Chung mạnh hơn, và càng mạnh
hơn nữa sau Cách mạng Công nghiệp.
Tại Mỹ việc bãi bỏ chế độ nô lệ không phá huỷ những quy chuẩn luật lệ cơ bản của
các bang cũng như toàn quốc gia. Những ví dụ đơn giản này minh chứng rõ ràng thực
tế lịch sử cho thấy chẳng có sự phụ thuộc cơ bản nào giữa phương thức sản xuất
của xã hội và những quy chuẩn luật pháp được tạo ra.  
