=== Tôn Giáo là gì?

*Nguỵ biện 7*

Chủ nghĩa Cộng sản tiếp tục cáo buộc tôn giáo không phải là nguồn gốc thánh thần
mà chỉ đơn thuần là công cụ con người tạo ra được sử dụng bởi tầng lớp cai trị
nhằm đàn áp tầng lớp bị bóc lột. Marx và Engels mô tả tôn giáo giống như liều
thuốc phiện của nhân loại, được làm ra để ru ngủ loài người vào trạng thái phục
tùng nhún nhường khiêm tốn, chấp nhận sự thắng thế của phương tiện sản xuất mà
tầng lớp cai trị mong muốn duy trì. Những sinh viên nghiên cứu lịch sử đều sẽ
đồng ý rằng đã xảy ra rất nhiều lần trong lịch sử những kẻ vô đạo đức hay thậm
chí các tổ chức tà giáo đã lợi dụng quyền lực tôn giáo, cũng như bao tổ chức khác
trong xã hội đã từng lợi dụng tôn giáo không ít lần.

Nhưng đây không phải là sự lợi dụng tôn giáo mà Marx cùng Engels bày tỏ phản đối
mạnh mẽ. Họ coi tôn giáo là sản phẩm của giai cấp cai trị, là công cụ và vũ khí
trong tay những kẻ đàn áp. Họ chỉ ra ba chức năng gói gọn lại của tôn giáo theo
quan điểm riêng của họ:

. Tôn giáo dạy con người tôn trọng quyền sở hữu tài sản.

. Tôn giáo dạy người nghèo bổn phận của họ đối với tài sản và đặc quyền của tầng
lớp cầm quyền.

. Tôn giáo nhồi sọ dần dần tư tưởng cam chịu cho tầng lớp bị bóc lột, làm tiêu
huỷ tinh thần cách mạng.

Sự nguỵ biện của những cáo buộc này rất rõ ràng đối với bất kì tín đồ Do Thái
hay Thiên Chúa giáo nào. Kinh thánh dạy tôn trọng tài sản đối với người giàu hay
người nghèo đều giống nhau, nhắc nhở người giàu trả lương đầy đủ cho người lao
động và chia sẻ sự giàu có của mình cho những người cần giúp. Kinh Cựu Ước cũng
phản đối người giàu có ích kỷ: "`Ðức Giê-hô-va xét đoán các trưởng lão của dân Ngài với các quan trưởng nó: Ấy chính các ngươi là kẻ đã nuốt vườn nho; của cướp bóc kẻ nghèo đương ở trong nhà các ngươi! Các ngươi có ý gì mà đè ép dân ta, giày vò mặt kẻ nghèo khó? Chúa, là Ðức Giê-hô-va vạn quân, phán vậy.`"
footnote:[Isaiah 3:14-15]

Kinh Tân Ước công khai lên án người giàu ích kỷ: "`Hỡi anh em là kẻ giàu có! Hãy khóc lóc, kêu la, vì cớ hoạn nạn sẽ đổ trên anh em. Kìa, tiền công con gặt gặt ruộng anh em, mà anh em đã ăn gian, nó kêu oan, và tiếng kêu của con gặt đã thấu đến tai Chúa các cơ binh.`"
footnote:[James 5:1-6]

"`Ta lại nói cùng các ngươi, lạc đà chui qua lỗ kim còn dễ hơn một người giàu vào nước Ðức Chúa Trời`"
footnote:[Matthew 19:24]

Đối với cáo buộc của Cộng sản nói rằng tôn giáo làm con người trở nên thụ động thì chúng
ta chỉ cần quan sát một điều: sức mạnh đức tin tôn giáo chắc chắn sẽ ngăn cản, không
cho phép những người theo tôn giáo chấp nhận sự đàn áp hay chấp hành những nhiệm vụ bắt buộc
của Cộng sản. Những người thực hành răn dạy triết lý Do Thái - Thiên Chúa giáo
không nói dối, không ăn cắp theo mệnh lệnh của người khác, không giết người,
không tham gia vào diệt chủng tàn độc của Cộng sản - tàn sát toàn bộ một dân tộc
hay tầng lớp một cách hệ thống.

Đây chính là bằng chứng rõ ràng từ nhiều ấn phẩm Cộng sản, những gì họ sợ ở tôn
giáo không phải là việc tôn giáo làm con người trở nên thụ động đối với tầng lớp
cai trị, mà chính là tôn giáo ngăn cản con người tiếp thu, trở nên thụ động đối
với những nguyên tắc của Cộng sản. Niềm tin tâm linh sâu sắc và vững chắc như một 
bức tường thành thách thức tất cả những thứ rao giảng và thực hành của chủ nghĩa
Cộng sản.

Hơn nữa, Cộng sản nhìn nhận hệ tư tưởng năng động của giáo lý Do Thái - Thiên
Chúa giáo giống như một sức mạnh ôn hoà cắt xuyên chiến lược sống còn của Cộng
sản đối với phong trào cách mạng toàn thế giới.
Như Anatole Lunarcharsky, cựu chính uỷ Nga tuyên bố:
"`Chúng ta ghét người Công giáo và Đạo Thiên Chúa. Những người giỏi nhất của họ phải được coi là kẻ thù xấu xa nhất của chúng ta. Họ thuyết giảng lòng yêu thương và vị tha đối với người xung quanh, điều này đi ngược với những nguyên tắc của chúng ta. Tình yêu Thiên Chúa cản trở sự phát triển Cách Mạng. Hãy vứt bỏ tình yêu thương của những người xung quanh! Những gì chúng ta cần là ghét bỏ....Chỉ có như vậy chúng ta mới chiếm hữu được vũ trụ này.`"
footnote:[Quoted in Congressional Record, Vol. 77, pp. 1539-1540]
