=== Phê bình lý thuyết đấu tranh giai cấp

*Nguỵ biện 9*

Nguỵ biện tiếp theo của Max và Engels tuyên bố phát hiện ra bí mật tiến bộ nhân
loại: đấu tranh giai cấp.

Nhắc lại một chút về tuyên bố này, họ nói khi con người nhận thức được chế
độ nô lệ thoả mãn phương thức sản xuất thì một xã hội sẽ được tạo ra với mục đích
bảo vệ quyền cho người sở hữu nô lệ. Họ cũng tin rằng xã hội và phương
thức sản xuất nô lệ sẽ không bao giờ thay đổi nếu như tình trạng lúc đó không
bị thách thức. Marx và Engels nhận thấy, cũng giống như các bạn sinh viên nghành
lịch sử, trật tự kinh tế chuyển từ chế độ nô lệ sang chế độ phong kiến, và sau đó từ
phong kiến sang chế độ tư bản. Vậy thì cái gì gây ra điều này? Họ khẳng định đó
là do _đấu tranh giai cấp_, những người nô lệ lật đổ giới chủ tạo ra một phương
thức sản xuất mới dựa trên nền chế độ phong kiến. Một xã hội mới phát triển bảo
vệ phương thức sản xuất này cho tới khi bần cố nông đứng lên lật đổ cường hào,
khởi tạo phương thức sản xuất mới đặc trưng cho chủ nghĩa tư bản thương mại tự do.
Xã hội hiện đại hình thành để bảo vệ chủ nghĩa tư bản - họ nói.

Các nhà phê bình chỉ ra Marx và Engels đã bỏ qua một số thực tế lịch sử rõ ràng
nhất. Ví dụ như các nền văn minh cổ đại Ai Cập, Hy Lạp và Rome mục rữa, sụp đổ
chẳng liên quan gì đến việc nô lệ vùng lên chống lại giới chủ:

"`Người nô lệ thời kì đó là những sinh vật tuân lệnh, khổ sở và bất lực nhất. Những cuộc nổi loạn và cằn nhằn âm ỉ của họ thường xuyên bị chấn áp tàn khốc. Đó không phải cái gọi là _đấu tranh giai cấp_ kiểu của người Marxist và không đem đến một sự chuyển giao lên chế độ phong kiến nào cả. Chính Engels nói vào cuối thời kì đế chế La Mã nô lệ khan hiếm và đắt đỏ; những trang trại đồn điền phụ thuộc vào sức lao động nô lệ không sinh lời nữa; nông trang quy mô nhỏ của thực dân và những người thuê đất làm ăn tương đối có lãi; nói một cách ngắn gọi, _chế độ nô lệ chết bởi vì nó không sinh lời nữa_. Sau đó xảy ra những cuộc xâm chiếm man rợ, đế chế La Mã sụp đổ, thiết lập nên chế độ phong kiến. Đây là kết quả của việc nền văn minh cao hơn chinh phục nền văn minh thấp kém hơn, và không hề xảy ra do bất kì lực lượng dẫn động nào của đấu tranh giai cấp.`"
footnote:[J.E.LeRossignol,FromMarxToStalin,pp.152-153]

Những vấn đề lịch sử tương tự tồn tại trong tuyên bố của Marx và Engels liên quan
đến việc chuyển giao xã hội từ chế độ phong kiến lên chủ nghĩa tư bản.

*Nguỵ biện 10*

Không chỉ thất bại khi lý giải tiến bộ trong quá khứ dựa trên lý luận cơ bản đấu
tranh giai cấp, mà chủ nghĩa Cộng sản còn thất bại dự đoán tương lai tầng lớp
theo chủ nghĩa phản kháng thù địch sẽ gia tăng dưới chế độ tư bản chủ nghĩa.
Nhưng hai giai cấp phản kháng đối đầu mạnh mẽ này (tư sản và vô sản) đã không phát
triển thành công suốt 100 năm như Marx và Engels tiên đoán - không thể tránh khỏi.

Chính trị viên Cộng sản làm đủ mọi cách để nhồi nhét ý thức giai cấp nhân tạo
vào đầu công nhân lao động, nhưng đấu tranh cơ bản giữa lao động và tư bản không
lật đổ chủ nghĩa tư bản, trái lại nó mang đến cho công nhân lao động nhiều bình
đẳng hơn, chia sẻ thành quả, trái ngọt của chủ nghĩa tư bản.
Ví dụ, trong suốt 20 năm công nhân lao động đã có được vị thế cao hơn tại Hoa Kỳ
hơn bao giờ hết. Những người Cộng sản cố gắng chiếm quyền lãnh đạo trong xu hướng
đổi mới này, nhưng khi công nhân kiếm được nhiều hơn họ trở nên độc lập hơn, không
chỉ khẳng định quyền của họ trong quan hệ với giới chủ, mà còn bãi bỏ những thể
loại chính trị viên ra khỏi lãnh đạo công đoàn lao động.
Một số cây viết Cộng sản thừa nhận sự thật cay đắng công nhân lao động không hưởng
ứng lại lời kêu gọi của Cộng sản lật đổ tư bản chủ nghĩa.

Vào cùng thời điểm đó các nhà lãnh đạo nghành công nghiệp và chính phủ phát triển
hệ thống triết lý, đồng ý cùng nhau rằng thu phục được sức mạnh của người lao động
là chìa khoá cơ bản giữ cho bánh xe các nghành công nghiệp chuyển động. Giới lao
động đã tiến gần hơn với vai trò quan trọng hơn bao giờ hết như một phần không
thể tách rời của chủ nghĩa tư bản. Những xu hướng này khiến Cộng sản thất bại hoàn
toàn đơn giản vì với sự phát triển, lao động đã trở thành bộ phận không thể
thay thế của chủ nghĩa tư bản chứ không còn là kẻ thù ý thức giai cấp.

*Nguỵ biện 11*

Một tiền đề khác của Cộng sản cũng thất bại khi đưa ra khẳng định dưới chế độ
tư bản tất của cải giàu có sẽ dần bị độc quyền, sở hữu bởi số rất ít người, còn
lại tầng lớp bị bóc lột vô sản sẽ chiếm phần lớn đa số trong xã hội. Nhưng sự thật
trớ trêu, dưới chế độ tư bản số lượng những người không có tài sản - vô sản lại
giảm xuống rõ rệt. Marx cho ra đời cuốn sách nặng nề dày cộp _Capital_
trong hoàn cảnh hết sức nghèo khổ, Marx nhìn những con người vô sản giống
như cuộc sống của chính mình, hoàn toàn không tài sản hay một xu dính túi.

Ngày nay tại các tiểu bang tư bản phát triển cao của Hoa Kỳ, những người có
thể xếp vào dạng vô sản theo định nghĩa của Marx là những người không có
đất, không có tiền gửi tiết kiệm, không có an sinh xã hội, không có trợ cấp hưu
trí, không có bảo hiểm nhân thọ, không có chứng khoán doanh nghiệp và không có
trái phiếu chính phủ, vì tất cả những thứ này thể hiện quyền sở hữu của cải sản
xuất, tiền hoặc các khoản vượt quá nhu cầu tiêu dùng trước mắt.
Một giai cấp vô sản như vậy cũng tồn tại ở Hoa Kỳ giống như đã xuất hiện
tại tất cả các quốc gia và ở mọi lứa tuổi, nhưng điều quan trọng là giai cấp vô
sản ở Hoa Kỳ chỉ chiếm thiểu số nhỏ, điều mà Marx hiếm khi muốn tuyên bố.
Dưới chủ nghĩa tư bản Mỹ, sự giàu có đã được phân phối rộng rãi trong dân
nhiều hơn bất kỳ quốc gia lớn nào trong lịch sử hàng trăm năm, góp phần làm giảm
mạnh mẽ tầng lớp vô sản trong xã hội.

Trái ngược với những gì chúng ta tìm thấy ở trên thì tại đất nước sản sinh ra chủ
nghĩa Cộng sản nơi số lượng thành phần vô sản lại chiếm đại đa số, và bị cai trị
dưới ách Độc tài Vô sản trong suốt hơn 35 năm.

*Nguỵ biện 12*

Lý thuyết tiền lương của Marx sụp đổ theo thời gian. Marx cho rằng kỹ thuật công
nghệ phát triển sẽ làm cho máy móc ngày càng hiện đại, hiệu quả hơn, con người
dần sẽ bị máy móc thay thế, cạnh tranh việc làm, tiền lương ngày càng bị giảm dần
đi. Nhưng thực tế cho thấy kỹ thuật công nghệ phát triển tạo ra nhiều việc làm
hơn ngoại trừ một số giai đoạn bị đình trệ, xu hướng dài hạn của chủ nghĩa tư bản
ngày càng tiến gần hơn đến giấc mơ kinh tế "`tất cả đều có việc làm`".

*Nguỵ biện 13*

Vì tin rằng tiền lương sẽ ngày càng ít đi nên Marx cho rằng sở hữu tài sản là cách
duy nhất đem lại cuộc sống đầy đủ, thứ phân biệt giữa người vô sản và giai cấp bóc
lột. Kết luận này lại nối thêm một sai lầm lớn nữa.
Lấy ví dụ thực tế ngày nay một người đi làm công ăn lương có thể kiếm được $10.000
một năm, trong khi đó người khác sống dựa vào thu nhập trên tài sản sở hữu của
mình thì chỉ kiếm được $2500 một năm. Nhìn vào trường hợp này sẽ thấy thật lố
bịch buồn cười, người vô sản chỉ đi làm thuê bán sức lao động lại có thu nhập tốt
hơn nhà tư sản sở hữu tài sản. Dưới chế độ tư bản chủ nghĩa việc sở hữu tài sản
chắc chắn không phải là cách duy nhất để có được độc lập kinh tế no đủ.

*Nguỵ biện 14*

Marx và Engels đã thất bại khi dự đoán tương lai của tầng lớp trung lưu dưới chế
độ tư bản, tầng lớp này sẽ bị biến mất dần, chuyển hoá thành giai cấp vô sản và
cuối cùng chỉ còn lại hai tầng lớp phản kháng đối đầu: những người tư bản và vô
sản. Nhưng điều ngược lại đã xảy ra, các nhà nghiên cứu kinh tế học chỉ ra tầng
lớp trung lưu (bao gồm những người không quá giàu hay nghèo) lại mọc lên nhanh
chóng, gia tăng về số lượng, giàu có và tỷ lệ với phần còn lại của dân số.
footnote:[Ralph E. Blodgett, Comparative Economic Systems, p, 735]

*Nguỵ biên 15*

Thêm một nguỵ biện nữa: đấu tranh giai cấp dẫn tới "`tiến bộ cần thiết`".
Marx và Engels cố gắng áp dụng triết lý biện chứng của mình trong lý thuyết này
để lý giải kết quả đấu tranh của các lực đối lập chắc chắn tạo ra tiến bộ mới
trong quá trình tiến hoá mới. Nhưng lý thuyết này lại không lý giải được sự
phát triển không hiệu quả tại rất nhiều quốc gia trong hàng thế kỉ như: Trung Quốc,
Ấn Độ, Ai Cập, Ả rập và dân số ở Đông Á. Nó cũng thất bại khi giải thích một trong
những thực tế lịch sử rõ ràng nhất cụ thể như sự sụp đổ của các nền văn minh.
Toàn bộ kinh nghiệm của loài người chỉ ra các quốc gia vươn lên đỉnh cao quyền
lực và sau đó chuyển sang giai đoạn đạo đức, trí tuệ suy đồi, đánh mất vị thế
văn hoá và ưu thế kinh tế. Những bằng chứng như thế này có thể tìm thấy
dễ dàng hơn rất nhiều so với đi tìm bằng chứng thuyết phục cho lý thuyết đấu
tranh giai cấp: nâng tầm con người ngày càng cao hơn qua các giai đoạn
"`tiến bộ cần thiết`" liên tiếp.

*Nguỵ biện 16*

Sự thất bại khi dự đoán những gì sẽ xảy ra ngay trong thời kì của Marx và Engels:
chủ nghĩa Cộng sản phải bắt đầu từ những quốc gia tư bản phát triển nhất bởi vì
ở đó đấu tranh giai cấp sẽ mạnh mẽ, sắc nét hơn khi chủ nghĩa tư bản mạnh lên.
Theo logic này họ nghĩ chủ nghĩa Cộng sản sẽ xuất hiện tại Đức đầu tiên.
footnote:[Marx-Engels, Communist Manifesto, p. 58]
Nhưng sau vài năm, Marx đã chuyển dự đoán của mình qua nước Anh.
footnote:[Marx is quoted by M. D'Arcy in Christian Morals, p. 172]

Thật trớ trêu chủ nghĩa Cộng sản (ít nhất là chế độ Độc tài vô sản) đã xuất hiện
đầu tiên tại nước Nga, một đất nước được xếp vào hàng kinh tế kém phát triển nhất
châu Âu. Hơn thế nữa chủ nghĩa Cộng sản được hình thành dưới cuộc đảo chính chứ
không phải xuất phát từ đấu tranh giai cấp của bộ phận tầng lớp công nhân lao động.
Cuộc đảo chính này là âm mưu bí mật của Lenin, người được Bộ tư lệnh tối cao Đức
hỗ trợ tiến vào nước Nga trong những tháng cuối của Thế chiến thứ nhất, hoạt động
cùng một nhóm cách mạng nhỏ, nhưng tinh nhuệ, chiếm lấy chính phủ lâm thời mà
trước đó đã buộc Tzar thoái vị, và cùng thời điểm đó đại diện cho công nhân lao
động cũng như bất kì tầng lớp nào khác để thiết lập nên hiến pháp dân chủ.

Chủ nghĩa Cộng sản đã không đến nước Nga giống như kết quả tự nhiên của đấu tranh
giai cấp, mà là theo kiểu độc tài, dùng sức mạnh quân đội của nhóm thiểu số.
Việc này lại dẫn chúng ta đến một nguỵ biện tiếp theo về "`Độc tài vô sản`".
