=== Lý thuyết đạo đức Cộng sản

*Nguỵ biện 8*

Những cây viết Cộng sản duy trì quan điểm các chuẩn mực đạo lý của Do Thái - Thiên
Chúa Giáo được coi là đạo đức "`giai cấp`", 10 điều răn của Chúa và nguyên tắc
đạo lý Thiên Chúa Giáo tạo ra chỉ nhằm để bảo vệ tài sản cá nhân và tầng lớp
sở hữu chúng. Ở đây chúng ta sẽ đề cập một vài diễn giải yêu thích của họ về 10
điều răn của Chúa bảo vệ quan điểm mà họ đưa ra.
Họ tin rằng lời răn "`Thảo kính cha mẹ - _Honor thy Father and thy Mother_`" của
người Do Thái thủa ban đầu nhấn mạnh ý rằng con cái là thuộc sở hữu riêng của
cha mẹ chúng.
"`Ngươi chớ giết người - _Thou shalt not kill_`" là niềm tin của  giai cấp cai trị
cho rằng cơ thể con người là tài sản riêng và do đó phải được  bảo về cũng giống
như các quyền sở hữu khác.
"`Ngươi chớ tà dâm - _Thou shalt not commit adultery_`" và
"`Ngươi chớ ham muốn vợ người - _Thou shalt not covet thy neighbor's wife_`"
cũng được cho rằng nó tạo ra để thực hiện ý tưởng người chồng là chủ ngôi nhà,
vợ anh ta là tài sản riêng chỉ thuộc về anh ta.

Câu cuối cùng lý giải cho hậu quả thảm hoạ xảy ra ở Nga khi Cộng sản lên nắm
quyền. Họ đã hạ thấp giá trị của người phụ nữ xuống đáy thấp nhất như thời nguyên
thuỷ, biến đổi những người phụ nữ này trở nên
"`bình đẳng với đàn ông`", ngăn cản phụ nữ trở thành tài sản tư hữu. Một số lãnh
đạo Cộng sản công khai cổ suý hoàn toàn chủ nghĩa tự do và thác loạn nhằm thay thế
hôn nhân gia đình. Đoạn lược trích từ một nghị định ban hành ở Liên Xô của Saralof
minh hoạ sự kiện này:

_"Bắt đầu từ ngày 1 tháng 3 năm 1919, bãi bỏ quyền sở hữu phụ nữ từ 17 đến 32 tuổi...tuy nhiên không áp dụng cho những người có 5 con. Chiểu theo nghị định này, phụ nữ không còn được coi là tài sản riêng cá nhân nữa, mà tất cả phụ nữ sẽ là tài sản của quốc gia. Việc phân phối, sử dụng và duy trì tài sản quốc hữu hoá này tuân theo các quyết định của tổ chức có trách nhiệm là đặc quyền riêng của nhóm Saralof vô chính phủ...Tất cả phụ nữ thuộc dạng tài sản quốc gia, trong ba ngày sau khi nghị định được thông báo, phải trình diện tại địa chỉ được ghi bên dưới, cung cấp các thông tin cần thiết..."_

_"Bất kì ai muốn sử dụng những người phụ nữ đã được quốc hữu hoá cần phải có giấy chứng nhận từ Hội đồng hành chính của tổ chức Công đoàn, hoặc chứng nhận là công nhân, binh sĩ hay nông dân nghèo thuộc tầng lớp lao động...Mỗi công nhân lao động phải đóng quỹ 2% lương thu nhập, còn những công dân nam giới khác cũng có thể hưởng thụ quyền sử dụng tài sản quốc gia này nếu đóng một khoản tương đương 250 francs Pháp cho quỹ công. Những phụ nữ thuộc dạng tài sản quốc gia chiểu theo nghị định sẽ nhận được lương hàng tháng tương đương 575 francs trích từ quỹ công..."_

_"Phụ nữ có thai không phải làm nhiệm vụ trước khi sinh 4 tháng và sau khi sinh 3 tháng...Trẻ em một tháng sau khi sinh sẽ được chuyển giao cho một tổ chức tin tưởng chăm sóc và giáo dục. Nhà nước sẽ chi trả tất cả chi phi giáo dục nuôi dưỡng cho đến khi chúng 17 tuổi...Tất cả những ai từ chối nghị định, không chịu hợp tác với nhà cầm quyền sẽ được coi là kẻ thù của mọi người, chống lại vô chính phủ, và sẽ lãnh chịu hậu quả "_
footnote:[Quoted by Gabriel M. Roschini in his article, "Contradictions Concerning the Status of Women in Soviet Russia," which appears in The Philosophy of Communism, by Giorgio La Pira and others, Fordham University Press, New York, 1952, pp. 97-98.]

Trong văn bản khác của một quan chức Liên Xô cũng minh họa việc "`giải phóng`" phụ
nữ dưới phiên bản đạo đức Cộng sản: "`Không có khái niệm đàn ông xâm hại phụ nữ ở đây. Ai nói như vậy là phủ nhận Cách mạng Cộng sản Tháng mười. Để bảo vệ phụ nữ bị xâm hại, hãy vạch mặt những kẻ tư sản, thành phần tư hữu.`"
footnote:[Outchit Gazeta, October 10, 1929. Quoted by Charles J. McFadden in The Philosophy of Communism, pp. 292-293 and note.]

Một điểm khác cần được thêm vào liên quan tới cáo buộc Cộng sản nói rằng đạo đức
thánh thiện răn dạy con người của Do Thái-Thiên Chúa giáo đại diện cho đạo đức
"`giai cấp`". Chẳng có gì phức tạp để minh hoạ cho cáo buộc phi lý này, cũng như thấy
được chủ nghĩa Nghĩa Cộng sản chính là môt ví dụ hoàn hảo nhất của đạo đức "`giai cấp`".
Trong 180 triệu người dân Nga chỉ có 3 triệu đảng viên Đảng cộng sản. Số nhỏ này
cưỡng ép hung bạo số đông còn lại phục tùng, chấp nhận đúng sai, tuân theo cuộc chơi
do chúng tự đặt ra.

Đạo đức Cộng sản tuân theo công thức đơn giản, cái gì ủng hộ nguyên tắc cộng sản
thì là tốt, còn những gì ngăn cản lại là xấu. Phân tích một chút ta sẽ thấy triết
lý này trở nên biến thái sang chiều hướng của chủ nghĩa cơ hội thực dụng - một
loại quy chuẩn không còn đạo đức gì cả. Những người không tuân theo điều lệ Đảng
phụng sự chủ nghĩa Cộng sản sẽ bị trừng phạt nghiêm trọng theo điều 131 và 133 của
hiến pháp Xô Viết. Đó chính là ví dụ hoàn hảo của đạo đức "`giai cấp`" mà người
Marxist gán cho chuẩn mực đạo đức của Do Thái - Thiên Chúa giáo, và thứ này xuất
hiện ngay trong chính kế hoạch hành động Cộng sản.
